CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `AUTO_CALC_BONUS`()
BEGIN
	DECLARE VV_PERIOD_NUM,VV_STEP_STATUS,VV_CHECK_STATUS INT;
	DECLARE VV_RESULT VARCHAR(200);
	DECLARE VV_ERR INT DEFAULT 1;
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET VV_ERR = 0;
	-- 锁表，防止运行时间过长同时调用奖金计算程序。
  SELECT * FROM LOCK_CALC_BONUS WHERE ID = 1 FOR UPDATE;
	-- 当前奖金计算程序运行状态。1表示计算中，0表示停止
	SELECT STEP_STATUS INTO VV_STEP_STATUS FROM LOCK_CALC_BONUS WHERE ID = 1;
	-- 获取可以进行奖金计算的最大周期。
  SELECT MAX(PERIOD_NUM) INTO VV_PERIOD_NUM FROM AR_PERIOD WHERE IS_PREPARE = 1;
	-- 周期值不等于0且奖金计算程序运行状态为停止，表示当前周期可以开始奖金计算。
	IF (IFNULL(VV_PERIOD_NUM,0) <> 0 AND VV_STEP_STATUS = 0) THEN
	  -- 修改周期的流转状态为业绩计算中。
		UPDATE AR_PERIOD SET IS_PREPARE = 2,CALC_RESULT = 'SUCCESS' WHERE PERIOD_NUM = VV_PERIOD_NUM;
		-- 修改奖金计算程序运行状态为计算中。
		UPDATE LOCK_CALC_BONUS SET STEP_STATUS = 1 WHERE ID = 1;
	  COMMIT;
		-- 数据检查，如果存在问题返回错误信息并停止计算。
		CALL CALC_CHECK(VV_PERIOD_NUM,VV_CHECK_STATUS,VV_RESULT);
		IF (VV_CHECK_STATUS = 1) THEN -- 检查通过
			-- 调用计算奖金的存储过程，开始计算奖金。
			CALL CALC_BONUS(VV_PERIOD_NUM);
		ELSE
		  -- 错误信息
			UPDATE AR_PERIOD T SET T.IS_PREPARE = 6,CALC_RESULT = VV_RESULT WHERE PERIOD_NUM = VV_PERIOD_NUM;
		END IF;
	  UPDATE LOCK_CALC_BONUS SET STEP_STATUS = 0 WHERE ID = 1;
		COMMIT;
	END IF;
	IF(VV_ERR = 0)THEN
	  UPDATE AR_PERIOD T SET T.IS_PREPARE = 6,T.CALC_RESULT = 'ERROR' WHERE PERIOD_NUM = VV_PERIOD_NUM;
	  UPDATE LOCK_CALC_BONUS SET STEP_STATUS = 0 WHERE ID = 1;
	  COMMIT;
	END IF;
END