CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_SFB`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
	DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字

	INSERT INTO AR_CALC_BE_SFB_MID1
	SELECT IV_PERIOD_NUM PERIOD_NUM,
				 IV_CALC_MONTH CALC_MONTH,
				 T.USER_ID,
				 T.STOCKIST_PV,
-- 				 IFNULL(T1.VALUE,0)/100 AS SFB_RATE,
-- 				 TRUNCATE(T.STOCKIST_PV * IFNULL(T1.VALUE,0)/100,2) BONUS_SFB,
				 U.COUNTRY_ID,
				 STOCKIST_PV_UNITY,
				 IFNULL(T1.VALUE,0)/100 AS SFB_RATE_UNITY,
				 TRUNCATE(T.STOCKIST_PV_UNITY * IFNULL(T1.VALUE,0)/100,2) BONUS_SFB_UNITY,
				 STOCKIST_PV_APP,
				 IFNULL(T2.VALUE,0)/100 AS SFB_RATE_APP,
				 TRUNCATE(T.STOCKIST_PV_APP * IFNULL(T2.VALUE,0)/100,2) BONUS_SFB_APP,
				 TRUNCATE(T.STOCKIST_PV_UNITY * IFNULL(T1.VALUE,0)/100,2)+TRUNCATE(T.STOCKIST_PV_APP * IFNULL(T2.VALUE,0)/100,2)+TRUNCATE(T.STOCKIST_PV_OTC * IFNULL(T3.VALUE,0)/100,2) BONUS_SFB,
				 STOCKIST_PV_OTC,
				 IFNULL(T3.VALUE,0)/100 AS SFB_RATE_OTC,
				 TRUNCATE(T.STOCKIST_PV_OTC * IFNULL(T3.VALUE,0)/100,2) BONUS_SFB_OTC
	  FROM (SELECT STOCKIST_ID USER_ID,
		             SUM(PV) STOCKIST_PV,
								 IFNULL(SUM(CASE WHEN TYPE_ID = 1 THEN PV END),0) STOCKIST_PV_UNITY,
								 IFNULL(SUM(CASE WHEN TYPE_ID = 2 THEN PV END),0) STOCKIST_PV_APP,
								 IFNULL(SUM(CASE WHEN TYPE_ID = 3 THEN PV END),0) STOCKIST_PV_OTC
		        FROM AR_PERF_ORDER_STOCKIST
					 GROUP BY STOCKIST_ID) T
	  LEFT JOIN AR_USER U ON T.USER_ID = U.ID
		LEFT JOIN AR_CONFIG T1 ON T1.CONFIG_NAME = CONCAT('stockistFeeRateUnity',U.COUNTRY_ID) AND T1.TYPE = 'bonus'
		LEFT JOIN AR_CONFIG T2 ON T2.CONFIG_NAME = CONCAT('stockistFeeRateApp',U.COUNTRY_ID) AND T2.TYPE = 'bonus'
		LEFT JOIN AR_CONFIG T3 ON T3.CONFIG_NAME = CONCAT('stockistFeeRateOtc',U.COUNTRY_ID) AND T3.TYPE = 'bonus'
	 WHERE T.STOCKIST_PV > 0;
  COMMIT;

	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	INSERT INTO AR_CALC_BONUS_SFB
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
	       T.PERIOD_NUM,
				 T.CALC_MONTH,
				 T.USER_ID,
				 T.STOCKIST_PV,
-- 				 T.SFB_RATE,
				 T.BONUS_SFB,
				 T.COUNTRY_ID,
				 T.STOCKIST_PV_UNITY,
				 T.BONUS_SFB_UNITY,
				 T.STOCKIST_PV_APP,
				 T.BONUS_SFB_APP,
				 T.STOCKIST_PV_OTC,
				 T.BONUS_SFB_OTC
	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,AR_CALC_BE_SFB_MID1 T
	 WHERE T.BONUS_SFB > 0;
	COMMIT;

END