CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_GPB`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
  DECLARE VV_PV_TOTAL
	  DECIMAL(16,2);
	DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字

	#参与计算季度分红奖衔级别为7/8/9级的明细
  INSERT INTO AR_CALC_BE_GPB_MID1
	SELECT T.PERIOD_NUM,
	       T.CALC_MONTH,
				 T.USER_ID,
				 T.LAYER_LV,
				 T.LAYER_CALC_ID,
				 T.LB_PV,
				 T.BONUS_HONOR_CALC_ID,
				 T.BONUS_HONOR_LV,
				 T.IS_ACTIVE,
				 U.IS_FOUNDER
	  FROM AR_CALC_LV_HONOR_PV T
	 INNER JOIN AR_USER U ON T.USER_ID = U.ID
	 WHERE T.LAYER_CALC_ID IN (70,80,90);
  COMMIT;

	-- 总业绩
	SELECT IFNULL(SUM(PV_PCS),0) INTO VV_PV_TOTAL FROM AR_PERF_MONTH T WHERE T.PERIOD_NUM = IV_PERIOD_NUM;

	#奖衔级别为7/8/9级对应的计奖比例
	INSERT INTO AR_CALC_BE_GPB_MID2
	SELECT T.CALC_ID LAYER_CALC_ID,
	       IFNULL(T1.MEMBER_TOTAL,0) MEMBER_TOTAL,
				 IFNULL(T1.LAYER_PV_TOTAL,0) LAYER_PV_TOTAL,
				 VV_PV_TOTAL PV_TOTAL,
				 IFNULL(T2.`VALUE`,0)/100 LAYER_RATE,
				 IFNULL(T2.`VALUE`,0)/200 MEMBER_LAYER_RATE,
				 IFNULL(T2.`VALUE`,0)/200 PV_LAYER_RATE,
				 CASE WHEN IFNULL(T1.MEMBER_TOTAL,0) = 0 THEN 0 ELSE TRUNCATE((VV_PV_TOTAL * IFNULL(T2.`VALUE`,0)/200) / IFNULL(T1.MEMBER_TOTAL,0),6) END ONE_MEMBER_BONUS,
				 CASE WHEN IFNULL(T1.LAYER_PV_TOTAL,0) = 0 THEN 0 ELSE TRUNCATE((VV_PV_TOTAL * IFNULL(T2.`VALUE`,0)/200) / IFNULL(T1.LAYER_PV_TOTAL,0),6) END ONE_PV_BONUS
	  FROM AR_HONOR_LEVEL T
		LEFT JOIN (SELECT LAYER_CALC_ID,
										  IS_FOUNDER,
										  SUM(1*(1+IS_FOUNDER)) MEMBER_TOTAL,
											SUM(LB_PV*(1+IS_FOUNDER)) LAYER_PV_TOTAL
		             FROM AR_CALC_BE_GPB_MID1
								GROUP BY LAYER_CALC_ID) T1 ON T1.LAYER_CALC_ID = T.CALC_ID
	  LEFT JOIN AR_CONFIG T2 ON T2.CONFIG_NAME = CONCAT('globalPoolBonus',T.CALC_ID)
	 WHERE T.CALC_ID IN (70,80,90);
	COMMIT;

	#奖衔级别为7/8/9级对应的计奖明细
	INSERT INTO AR_CALC_BE_GPB_DETAIL
	SELECT T.PERIOD_NUM,
	       T.CALC_MONTH,
				 T.USER_ID,
				 T.LAYER_LV,
				 T.LAYER_CALC_ID,
				 T.LB_PV,
				 T.BONUS_HONOR_CALC_ID,
				 T.BONUS_HONOR_LV,
				 T.IS_ACTIVE,
				 T.IS_FOUNDER,
				 T1.MEMBER_TOTAL,
				 T1.LAYER_PV_TOTAL,
				 T1.PV_TOTAL,
				 T1.LAYER_RATE,
				 T1.MEMBER_LAYER_RATE,
				 T1.PV_LAYER_RATE,
				 T1.ONE_MEMBER_BONUS,
				 T1.ONE_PV_BONUS,
				 TRUNCATE(T1.ONE_MEMBER_BONUS * (1+T.IS_FOUNDER),2) MEMBER_BONUS,
				 TRUNCATE(T1.ONE_PV_BONUS * (1+T.IS_FOUNDER) * T.LB_PV,2) PV_BONUS
	  FROM AR_CALC_BE_GPB_MID1 T
		INNER JOIN  AR_CALC_BE_GPB_MID2 T1 ON T1.LAYER_CALC_ID = T.LAYER_CALC_ID;
	COMMIT;

	#会员的得奖明细
	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	INSERT INTO AR_CALC_BONUS_GPB
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
	       T.PERIOD_NUM,
	       T.CALC_MONTH,
				 T.USER_ID,
				 T.IS_FOUNDER,
				 T.IS_ACTIVE,
				 SUM(MEMBER_BONUS) MEMBER_BONUS,
				 SUM(PV_BONUS) PV_BONUS,
				 TRUNCATE(SUM(MEMBER_BONUS)+SUM(PV_BONUS),2) BONUS_GPB
	  FROM AR_CALC_BE_GPB_DETAIL T,(SELECT @ROWNUM := 0 FROM DUAL) R
	 WHERE T.BONUS_HONOR_CALC_ID >= T.LAYER_CALC_ID
	 GROUP BY  T.PERIOD_NUM,T.CALC_MONTH,T.USER_ID,T.IS_FOUNDER,T.IS_ACTIVE;
	COMMIT;
END