CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BACKUP_COUNTRY_SHARE`(IN IV_PERIOD_NUM INT)
BEGIN
	DECLARE STR_SQL VARCHAR(500);
	DECLARE VV_COUNT,
	        VV_CURRENT
	  INT;

  SELECT COUNT(*) - 1
	  INTO VV_COUNT
	  FROM INFORMATION_SCHEMA.`TABLES`
	 WHERE TABLE_SCHEMA = (SELECT DATABASE())
	   AND TABLE_NAME NOT LIKE 'ZZ%'
		 AND TABLE_NAME IN (SELECT TABLE_NAME FROM BACKUP_TABLES WHERE TYPE = 'COUNTRY_SHARE');

  SET VV_CURRENT = 0;
	WHILE (VV_CURRENT <= VV_COUNT) DO
		SELECT CONCAT('DROP TABLE IF EXISTS ZZ',TABLE_NAME,'_',IV_PERIOD_NUM,';')
			INTO STR_SQL
			FROM INFORMATION_SCHEMA.`TABLES`
		 WHERE TABLE_SCHEMA = (SELECT DATABASE())
			 AND TABLE_NAME NOT LIKE 'ZZ%'
		   AND TABLE_NAME IN (SELECT TABLE_NAME FROM BACKUP_TABLES WHERE TYPE = 'COUNTRY_SHARE')
		 ORDER BY TABLE_NAME
		 LIMIT VV_CURRENT,1;

		PREPARE stmt1 FROM STR_SQL;
		##执行SQL语句
		EXECUTE stmt1;
		## 释放掉预处理段
		DEALLOCATE PREPARE stmt1 ;
		SELECT CONCAT('CREATE TABLE ZZ',TABLE_NAME,'_',IV_PERIOD_NUM,' SELECT * FROM ',TABLE_NAME,';')
			INTO STR_SQL
			FROM INFORMATION_SCHEMA.`TABLES`
		 WHERE TABLE_SCHEMA = (SELECT DATABASE())
			 AND TABLE_NAME NOT LIKE 'ZZ%'
		   AND TABLE_NAME IN (SELECT TABLE_NAME FROM BACKUP_TABLES WHERE TYPE = 'COUNTRY_SHARE')
		 ORDER BY TABLE_NAME
		 LIMIT VV_CURRENT,1;

		PREPARE stmt1 FROM STR_SQL;
		##执行SQL语句
		EXECUTE stmt1;
		## 释放掉预处理段
		DEALLOCATE PREPARE stmt1 ;

		SET VV_CURRENT = VV_CURRENT + 1;
  END WHILE;


END