CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_LV_HONOR_LAST`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
  DECLARE VV_MAX_LAYER,
	        VV_TOTAL,
					VV_COUNT
	  INT;
	DECLARE VV_USER_ID
	  VARCHAR(32);

	DECLARE VV_LB_PV
	  DECIMAL(16,2);
	/*--------------------------------------------表说明--------------------------------------------*/
	/*
	  AR_CALC_LV_HONOR_MID1：记录当前会员离自己最近的SE会员的ID
	  AR_CALC_LV_HONOR_MID2：所有SE自己第一层奖衔的计奖业绩明细
	  AR_CALC_LV_HONOR_MID3：所有SE自己第一层奖衔的计奖业绩
	  AR_CALC_LV_HONOR_MID4：自己是SE且有计奖业绩的会员
		AR_CALC_LV_HONOR_MID5：会员每层可以拿到的业绩(不是真实会员，此处还没有计算7/8/9时额外两条线的限制)
		AR_CALC_LV_HONOR_MID6：只看最长的线本人有多少代SE且最下面的SE有计奖业绩
		AR_CALC_LV_HONOR_MID7：每条线有多少个SE，不需要看是否存在计奖业绩
		AR_CALC_LV_HONOR_MID8：取最长的线有多少个SE，不需要看是否存在计奖业绩
		AR_CALC_LV_HONOR_MID9：会员的最新奖衔
		AR_CALC_LV_HONOR_MID10：会员的奖衔等级限制明细
	*/

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'1',NOW());
-- 	COMMIT;
	-- 记录当前会员离自己最近的SE会员的ID
	INSERT INTO AR_CALC_LV_HONOR_MID1
	SELECT PERIOD_NUM,-- 周期
				 CALC_MONTH,-- 月份
				 USER_ID,
				 PARENT_UID,
				 TOP_DEEP,
				 GPV,
				 GPV_REAL,
				 GPV_UNREAL,
				 SONS_NUM,
				 LAST_ELITE_CALC_ID,-- Elite级别
				 PARENT_UID AS PARENT_SE
	  FROM AR_CALC_LV_ELITE;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'2',NOW());
-- 	COMMIT;
	-- 找自己的第一个SE作为自己的PAREN_SE
	SELECT IFNULL(MAX(T.TOP_DEEP),-1) INTO VV_MAX_LAYER FROM AR_CALC_LV_HONOR_MID1 T;
	SET VV_TOTAL = VV_MAX_LAYER-1;
	WHILE VV_TOTAL >= 0 DO
	  -- 如果本人不是SE则将PAREN_SE是自己的改为自己的PARENT_UID
	  UPDATE AR_CALC_LV_HONOR_MID1 T
		 INNER JOIN (SELECT A.USER_ID,
		                    A.PARENT_UID
		               FROM AR_CALC_LV_HONOR_MID1 A
		              WHERE A.TOP_DEEP = VV_TOTAL
		                AND A.LAST_ELITE_CALC_ID <> 30) T1 ON T.PARENT_SE = T1.USER_ID
		   SET T.PARENT_SE = T1.PARENT_UID;
	  COMMIT;
		SET VV_TOTAL = VV_TOTAL - 1;
  END WHILE;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'3',NOW());
-- 	COMMIT;
	-- 计算自己向上贡献的第一层计奖业绩
	SET VV_TOTAL = VV_MAX_LAYER;
	WHILE VV_TOTAL > 0 DO
	  -- 所有SE自己第一层奖衔的计奖业绩明细
	  INSERT INTO AR_CALC_LV_HONOR_MID2
		SELECT T.PERIOD_NUM,-- 周期
				   T.CALC_MONTH,-- 月份
					 CASE WHEN T.PARENT_SE = T.PARENT_UID THEN T1.PARENT_SE
					      ELSE T.PARENT_SE END AS USER_ID,-- 获得业绩得用户
					 T.USER_ID AS SOURCE_USER_ID,-- 来源
					 T.GPV_REAL,
					 0 GPV_UNREAL,
					 T.TOP_DEEP
		  FROM AR_CALC_LV_HONOR_MID1 T
			LEFT JOIN AR_CALC_LV_HONOR_MID1 T1 ON T.PARENT_UID = T1.USER_ID
		 WHERE T.TOP_DEEP = VV_TOTAL;
		COMMIT;
	  INSERT INTO AR_CALC_LV_HONOR_MID2
		SELECT T.PERIOD_NUM,-- 周期
				   T.CALC_MONTH,-- 月份
					 T.PARENT_SE AS USER_ID,-- 获得业绩得用户
					 T.USER_ID AS SOURCE_USER_ID,-- 来源
					 0 GPV_REAL,
					 T.GPV_UNREAL,
					 T.TOP_DEEP
		  FROM AR_CALC_LV_HONOR_MID1 T
		 WHERE T.TOP_DEEP = VV_TOTAL
		   AND T.GPV_UNREAL > 0;
		COMMIT;
	  SET VV_TOTAL = VV_TOTAL - 1;
  END WHILE;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'4',NOW());
-- 	COMMIT;
	-- 所有SE自己第一层奖衔的计奖业绩
  INSERT INTO AR_CALC_LV_HONOR_MID3
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
				 IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID,
				 SUM(T.GPV_REAL + T.GPV_UNREAL) AS LB_PV
	  FROM AR_CALC_LV_HONOR_MID2 T
	 WHERE T.USER_ID <> '0'
	 GROUP BY T.USER_ID;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'5',NOW());
-- 	COMMIT;
	-- 自己是SE且有计奖业绩的会员
	INSERT INTO AR_CALC_LV_HONOR_MID4
	SELECT T.PERIOD_NUM,-- 周期
				 T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.PARENT_UID,
				 T.TOP_DEEP,
				 T.GPV,
				 T.GPV_REAL,
				 T.GPV_UNREAL,
				 T.SONS_NUM,
				 T.LAST_ELITE_CALC_ID,-- Elite级别
				 T.PARENT_SE,
				 IFNULL(T1.LB_PV,0) LB_PV
	  FROM AR_CALC_LV_HONOR_MID1 T
		LEFT JOIN AR_CALC_LV_HONOR_MID3 T1 ON T.USER_ID = T1.USER_ID
	 WHERE T1.LB_PV > 0;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'6',NOW());
-- 	COMMIT;
	--
	SELECT COUNT(1)
	  INTO VV_COUNT
		FROM AR_CALC_LV_HONOR_MID4 T
	 WHERE T.LB_PV > 0;
	SET VV_TOTAL = VV_COUNT - 1;
	WHILE VV_TOTAL >= 0 DO
	  SELECT T.USER_ID,LB_PV
		  INTO VV_USER_ID,VV_LB_PV
			FROM AR_CALC_LV_HONOR_MID4 T
		 LIMIT VV_TOTAL,1;
	  -- 会员每层可以拿到的业绩(不是真实会员，此处还没有计算7/8/9时额外两条线的限制)
	  INSERT INTO AR_CALC_LV_HONOR_MID5
		WITH RECURSIVE T_REC AS -- RECURSIVE为关键字，可以不列出字段列表
		(SELECT A.PERIOD_NUM,
		        A.CALC_MONTH,
						A.USER_ID,
			      A.PARENT_SE AS PARENT_UID,
						10 AS LAYER_CALC_ID
		   FROM AR_CALC_LV_HONOR_MID4 A
		  WHERE A.USER_ID = VV_USER_ID
		 UNION ALL
		 SELECT A1.PERIOD_NUM,
		        A1.CALC_MONTH,
						A1.USER_ID,
		        A1.PARENT_SE AS PARENT_UID,
						A2.LAYER_CALC_ID + 10 AS LAYER_CALC_ID
			 FROM AR_CALC_LV_HONOR_MID4 A1
		  INNER JOIN T_REC A2 ON A1.USER_ID = A2.PARENT_UID -- 递归生成的结果集T2的PARENT_ID与之前的源表ID关联
	  )SELECT T.PERIOD_NUM,
		        T.CALC_MONTH,
						T.USER_ID,
		        T.PARENT_UID,
						T.LAYER_CALC_ID,
						VV_LB_PV AS LB_PV
		   FROM T_REC T;
		COMMIT;
		SET VV_TOTAL = VV_TOTAL - 1;
  END WHILE;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'7',NOW());
-- 	COMMIT;
	-- 只看最长的线本人有多少代SE且最下面的SE有计奖业绩
	INSERT INTO AR_CALC_LV_HONOR_MID6
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,
		     IV_CALC_MONTH AS CALC_MONTH,
				 T.USER_ID,
				 MAX(T.LAYER_CALC_ID) AS LEGS_MAX_CALC_ID
	  FROM AR_CALC_LV_HONOR_MID5 T
	 GROUP BY T.USER_ID;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'8',NOW());
-- 	COMMIT;
	-- 计算每条线一个有多少个SE
	SELECT IFNULL(MAX(T.TOP_DEEP),0) INTO VV_MAX_LAYER FROM AR_CALC_LV_HONOR_MID1 T WHERE T.LAST_ELITE_CALC_ID = 30;
	SET VV_TOTAL = VV_MAX_LAYER;
  WHILE VV_TOTAL >= 0 DO
	  -- 每条线有多少个SE，不需要看是否存在计奖业绩
	  INSERT INTO AR_CALC_LV_HONOR_MID7
	  WITH RECURSIVE T_REC AS -- RECURSIVE为关键字，可以不列出字段列表
		(SELECT A.PERIOD_NUM,
		        A.CALC_MONTH,
						A.USER_ID,
			      A.PARENT_SE AS PARENT_UID,
						1 AS SE_NUM
		   FROM AR_CALC_LV_HONOR_MID1 A
		  WHERE A.TOP_DEEP = VV_TOTAL
			  AND A.LAST_ELITE_CALC_ID = 30
		 UNION ALL
		 SELECT A1.PERIOD_NUM,
		        A1.CALC_MONTH,
						A1.USER_ID,
		        A1.PARENT_SE AS PARENT_UID,
						A2.SE_NUM + 1 AS SE_NUM
			 FROM AR_CALC_LV_HONOR_MID4 A1
		  INNER JOIN T_REC A2 ON A1.USER_ID = A2.PARENT_UID -- 递归生成的结果集T2的PARENT_ID与之前的源表ID关联
	  )SELECT T.PERIOD_NUM,
		        T.CALC_MONTH,
						T.USER_ID,
		        T.PARENT_UID,
						T.SE_NUM
		   FROM T_REC T;
	  COMMIT;
		SET VV_TOTAL = VV_TOTAL - 1;
  END WHILE;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'9',NOW());
-- 	COMMIT;
	-- 取最长的线有多少个SE，不需要看是否存在计奖业绩
	INSERT INTO AR_CALC_LV_HONOR_MID8
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,
		     IV_CALC_MONTH AS CALC_MONTH,
				 T.USER_ID,
				 T.PARENT_UID,
	       MAX(T.SE_NUM) AS SE_NUM
	  FROM AR_CALC_LV_HONOR_MID7 T
	 GROUP BY T.USER_ID,T.PARENT_UID;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'10',NOW());
-- 	COMMIT;
	-- 会员的最新奖衔
	INSERT INTO AR_CALC_LV_HONOR_MID9
	SELECT T.PERIOD_NUM,-- 周期
				 T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.LEGS_MAX_CALC_ID,
				 IFNULL(T1.PASS_NUM,0) AS HONOR90_LEGS,
				 IFNULL(T2.PASS_NUM,0) AS HONOR80_LEGS,
				 IFNULL(T3.PASS_NUM,0) AS HONOR70_LEGS,
				 CASE WHEN T.LEGS_MAX_CALC_ID >= 90 AND IFNULL(T1.PASS_NUM,0) >= 3 THEN 90
				      WHEN T.LEGS_MAX_CALC_ID >= 80 AND IFNULL(T2.PASS_NUM,0) >= 3 THEN 80
				      WHEN T.LEGS_MAX_CALC_ID >= 70 AND IFNULL(T3.PASS_NUM,0) >= 3 THEN 70
							ELSE LEAST(T.LEGS_MAX_CALC_ID,60) END AS ORI_HONOR_CALC_ID
	  FROM AR_CALC_LV_HONOR_MID6 T
		LEFT JOIN (SELECT A.PARENT_UID AS USER_ID,
		                  COUNT(*) PASS_NUM
		             FROM AR_CALC_LV_HONOR_MID8 A
							  WHERE A.SE_NUM >= 3
								GROUP BY A.PARENT_UID) T1 ON T1.USER_ID = T.USER_ID
		LEFT JOIN (SELECT A.PARENT_UID AS USER_ID,
		                  COUNT(*) PASS_NUM
		             FROM AR_CALC_LV_HONOR_MID8 A
							  WHERE A.SE_NUM >= 2
								GROUP BY A.PARENT_UID) T2 ON T2.USER_ID = T.USER_ID
		LEFT JOIN (SELECT A.PARENT_UID AS USER_ID,
		                  COUNT(*) PASS_NUM
		             FROM AR_CALC_LV_HONOR_MID8 A
							  WHERE A.SE_NUM >= 1
								GROUP BY A.PARENT_UID) T3 ON T3.USER_ID = T.USER_ID;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'11',NOW());
-- 	COMMIT;
	-- 会员的奖衔等级限制明细
	INSERT INTO AR_CALC_LV_HONOR_MID10
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,
		     IV_CALC_MONTH AS CALC_MONTH,
				 T.ID AS USER_ID,
	       T.MEMBER_LV AS LAST_MEMBER_LV,
				 T1.CALC_ID AS LAST_MEMBER_CALC_ID,
				 T2.VALUE AS LIMIT_HONOR_CALC_ID,
				 T3.ID AS LIMIT_HONOR_LV
	  FROM AR_USER T
		LEFT JOIN AR_MEMBER_LEVEL T1 ON T1.ID = T.MEMBER_LV
		LEFT JOIN AR_CONFIG T2 ON T2.CONFIG_NAME = CONCAT('leadershipLimit',T1.CALC_ID) AND T2.TYPE = 'bonus'
		LEFT JOIN AR_HONOR_LEVEL T3 ON T3.CALC_ID = T2.VALUE;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'12',NOW());
-- 	COMMIT;
	-- 计算自己的Honor
	INSERT INTO AR_CALC_LV_HONOR_MID11
	SELECT T.PERIOD_NUM,-- 周期
				 T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.LEGS_MAX_CALC_ID,
				 T.HONOR90_LEGS,
				 T.HONOR80_LEGS,
				 T.HONOR70_LEGS,
				 T.ORI_HONOR_CALC_ID,
				 T1.ID AS ORI_HONOR_LV,
				 T2.LIMIT_HONOR_CALC_ID,
				 T2.LIMIT_HONOR_LV,
				 CASE WHEN T.ORI_HONOR_CALC_ID <= T2.LIMIT_HONOR_CALC_ID THEN T.ORI_HONOR_CALC_ID
				      ELSE T2.LIMIT_HONOR_CALC_ID END AS BONUS_HONOR_CALC_ID,
				 CASE WHEN T.ORI_HONOR_CALC_ID <= T2.LIMIT_HONOR_CALC_ID THEN T1.ID
				      ELSE T2.LIMIT_HONOR_LV END AS BONUS_HONOR_LV,
				 GREATEST(IFNULL(T3.SE_NUM,0)-1,0) AS SE_NUM
	  FROM AR_CALC_LV_HONOR_MID9 T
		LEFT JOIN AR_HONOR_LEVEL T1 ON T1.CALC_ID = T.ORI_HONOR_CALC_ID
		LEFT JOIN AR_CALC_LV_HONOR_MID10 T2 ON T2.USER_ID = T.USER_ID
		LEFT JOIN AR_CALC_LV_HONOR_MID8 T3 ON T3.USER_ID = T.USER_ID;
	COMMIT;


-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'13',NOW());
-- 	COMMIT;
	INSERT INTO AR_CALC_LV_HONOR
	SELECT T.PERIOD_NUM,-- 周期
				 T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.LEGS_MAX_CALC_ID,
				 T.HONOR90_LEGS,
				 T.HONOR80_LEGS,
				 T.HONOR70_LEGS,
				 T.ORI_HONOR_CALC_ID,
				 T.ORI_HONOR_LV,
				 T.LIMIT_HONOR_CALC_ID,
				 T.LIMIT_HONOR_LV,
				 T.BONUS_HONOR_CALC_ID,
				 T.BONUS_HONOR_LV,
				 T.SE_NUM,
				 LEAST(T.BONUS_HONOR_CALC_ID,T.SE_NUM*10) AS LAST_HONOR_CALC_ID,
				 T1.ID AS LAST_HONOR_LV
	  FROM AR_CALC_LV_HONOR_MID11 T
		LEFT JOIN AR_HONOR_LEVEL T1 ON T1.CALC_ID = LEAST(T.BONUS_HONOR_CALC_ID,T.SE_NUM*10);
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'14',NOW());
-- 	COMMIT;
	-- 计算自己1 Star Director到3 Star Crown的计奖业绩
	INSERT INTO AR_CALC_LV_HONOR_PV
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
				 IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID,
				 T1.ID AS LAYER_LV,
				 T.LAYER_CALC_ID,
				 T.LB_PV,
				 T2.BONUS_HONOR_CALC_ID,
				 T2.BONUS_HONOR_LV,
				 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE
	  FROM (SELECT A.USER_ID,
				         A.LAYER_CALC_ID,
								 SUM(A.LB_PV) AS LB_PV
				    FROM AR_CALC_LV_HONOR_MID5 A
		        LEFT JOIN AR_CALC_LV_HONOR A1 ON A.USER_ID = A1.USER_ID
	         WHERE A.LAYER_CALC_ID <= A1.ORI_HONOR_CALC_ID
	         GROUP BY A.USER_ID,A.LAYER_CALC_ID) T
		LEFT JOIN	AR_HONOR_LEVEL T1 ON T1.CALC_ID = T.LAYER_CALC_ID
		LEFT JOIN	AR_CALC_LV_HONOR T2 ON T2.USER_ID = T.USER_ID
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID;
	COMMIT;
END