CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_PE`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN

  DECLARE VV_PE_RATE DECIMAL(16,6);
	DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字

	/*--------------------------------------------表说明--------------------------------------------*/
	/*
	  AR_CALC_BE_PE_MID1：汇总Pro Elite奖金贡献的业绩
	*/

	SELECT IFNULL(MIN(T.VALUE),0) / 100 INTO VV_PE_RATE FROM AR_CONFIG T WHERE T.CONFIG_NAME = 'proEliteRate' AND T.TYPE = 'bonus';


	-- 汇总Pro Elite奖金贡献的业绩
	INSERT INTO AR_CALC_BE_PE_MID1
  SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
	       IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID,
				 IFNULL(SUM(T1.GPV_REAL),0) AS GPV_REAL
	  FROM AR_CALC_LV_ELITE T
		LEFT JOIN AR_CALC_LV_ELITE T1 ON T1.PARENT_UID = T.USER_ID
	 WHERE T.LAST_ELITE_CALC_ID >= 20
	 GROUP BY T.USER_ID;
	COMMIT;

	-- 计算Pro Elite奖金
	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	INSERT INTO AR_CALC_BONUS_PE
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
	       T.PERIOD_NUM,-- 周期
	       T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.GPV_REAL+T1.GPV_UNREAL AS GPV_REAL,
				 VV_PE_RATE AS PE_RATE,
				 TRUNCATE((T.GPV_REAL + T1.GPV_UNREAL) * VV_PE_RATE,2) AS BONUS_PE,
				 T2.COUNTRY_ID,
				 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE
	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,AR_CALC_BE_PE_MID1 T
		LEFT JOIN AR_CALC_LV_ELITE T1 ON T1.USER_ID = T.USER_ID
		LEFT JOIN AR_USER T2 ON T2.ID = T.USER_ID
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID;
	COMMIT;

	-- PE source
	INSERT INTO AR_CALC_BONUS_PE_SOURCE
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
	       IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID AS BONUS_USER_ID,
				 U.USER_NAME AS BONUS_USER_NAME,
				 U.REAL_NAME AS BONUS_REAL_NAME,
				 T1.USER_ID AS SOURCE_USER_ID,
				 U1.USER_NAME AS SOURCE_USER_NAME,
				 U1.REAL_NAME AS SOURCE_REAL_NAME,
				 T1.GPV_REAL AS SOURCE_GPV,
				 0 AS SOURCE_GPV_UNREAL,
				 VV_PE_RATE AS PE_RATE,
				 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE
	  FROM AR_CALC_LV_ELITE T
	 INNER JOIN AR_USER U ON U.ID = T.USER_ID
	 INNER JOIN AR_CALC_LV_ELITE T1 ON T1.PARENT_UID = T.USER_ID
	 INNER JOIN AR_USER U1 ON U1.ID = T1.USER_ID
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID
	 WHERE T.LAST_ELITE_CALC_ID >= 20 AND T1.GPV_REAL > 0
  UNION ALL
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
	       IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID AS BONUS_USER_ID,
				 U.USER_NAME AS BONUS_USER_NAME,
				 U.REAL_NAME AS BONUS_REAL_NAME,
				 T.USER_ID AS SOURCE_USER_ID,
				 U.USER_NAME AS SOURCE_USER_NAME,
				 U.REAL_NAME AS SOURCE_REAL_NAME,
				 0 AS SOURCE_GPV,
				 T.GPV_UNREAL AS SOURCE_GPV_UNREAL,
				 VV_PE_RATE AS PE_RATE,
				 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE
	  FROM AR_CALC_LV_ELITE T
	 INNER JOIN AR_USER U ON U.ID = T.USER_ID
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID
	 WHERE T.LAST_ELITE_CALC_ID >= 20 AND T.GPV_UNREAL > 0;

	COMMIT;


END