CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_PERIOD_STATUS`(IN IV_PERIOD_NUM INT,IN IV_STEP INT)
BEGIN
	/*变更周期表的状态*/
	IF(IV_STEP = 2) THEN
	  -- 业绩计算中
	  UPDATE AR_PERIOD T
		   SET T.IS_PERFING = 1,
					 T.IS_PERFED = 0,
					 T.PERF_STARTED_AT = UNIX_TIMESTAMP()
		 WHERE T.PERIOD_NUM = IV_PERIOD_NUM;
	  COMMIT;
  ELSEIF(IV_STEP = 3) THEN
	  -- 奖金计算中
	  UPDATE AR_PERIOD T
		   SET T.IS_PREPARE = 3,
			     T.IS_PERFING = 0,
					 T.IS_PERFED = 1,
					 T.PERFED_AT = UNIX_TIMESTAMP(),
			     T.IS_CALCING = 1,
					 T.IS_CALCULATED = 0,
					 T.CALCULATE_STARTED_AT = UNIX_TIMESTAMP()
		 WHERE T.PERIOD_NUM = IV_PERIOD_NUM;
	  COMMIT;
	ELSEIF(IV_STEP = 4) THEN
	  -- 计算完成
	  UPDATE AR_PERIOD T
		   SET T.IS_PREPARE = 4,
			     T.IS_CALCING = 0,
					 T.IS_CALCULATED = 1,
					 T.CALCULATED_AT = UNIX_TIMESTAMP()
		 WHERE T.PERIOD_NUM = IV_PERIOD_NUM;
	  COMMIT;
	END IF;

END