CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_PB`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
	/*
	PGBV＜300 20%
	300 <= PGBV <600 30%
	600 <= PGBV <1000 40%
	*/
	DECLARE VV_LV1_PV DECIMAL(16,2) DEFAULT(300);
	DECLARE VV_LV2_PV DECIMAL(16,2) DEFAULT(600);
	DECLARE VV_LV1 INT DEFAULT(10);
	DECLARE VV_LV2 INT DEFAULT(20);
	DECLARE VV_LV3 INT DEFAULT(30);
	DECLARE VV_LV1_RATE DECIMAL(16,6) DEFAULT(0.2);
	DECLARE VV_LV2_RATE DECIMAL(16,6) DEFAULT(0.3);
	DECLARE VV_LV3_RATE DECIMAL(16,6) DEFAULT(0.4);
	DECLARE VV_MAX_COUNT,
					VV_COUNT,
					VV_PB_LV,
					VV_SOURCE_PB_LV,
					VV_TEMP_PV,
					VV_ELITE_CALC_ID,
					VV_TOP_DEEP,
					VV_COUNT1 INT;
	DECLARE VV_SOURCE_PV,
					VV_PB_RATE,
					VV_SOURCE_PB_RATE,
					VV_TEMP_RATE DECIMAL(16,6);
	DECLARE VV_USER_ID,
					VV_SOURCE_USER_ID,
					VV_PARENT_UID,
					VV_TIME_STR -- 当前时间的年月日时分秒数字
					VARCHAR(32);
	/*--------------------------------------------表说明--------------------------------------------*/
	/*
	AR_CALC_PB_TOTAL_GPV：统计累计PGS值以及对应等级比例
	-- AR_CALC_BE_PB_MID1：可以参与计算PB奖的会员及对应得奖等级和比例
	AR_CALC_BE_PB_MID2：PB得奖情况
	*/
	-- 统计累计PGS值
	INSERT INTO AR_CALC_PB_TOTAL_GPV
	SELECT IV_PERIOD_NUM PERIOD_NUM,-- 周期
				 IV_CALC_MONTH CALC_MONTH,-- 月份
			   U.ID USER_ID,
				 IFNULL( R.PARENT_UID, 0 ) PARENT_UID,
				 IFNULL( R.TOP_DEEP, 0 ) TOP_DEEP,
				 IFNULL( G.TOTAL_GPV, 0 ) ORI_TOTAL_GPV,
				 IFNULL( N.GPV, 0 ) GPV,
				 IFNULL( N.PV_PCS, 0 ) PV_PCS,
				 IFNULL( G.TOTAL_GPV, 0 )+ IFNULL( N.GPV, 0 ) TOTAL_GPV,
				 IFNULL( N.ELITE_CALC_ID, 0 ) ELITE_CALC_ID,
				 U.COUNTRY_ID,
				 -- Performance Bonus对应级别 比较取最大
				 GREATEST(
				   -- 原始的比例
					 (CASE WHEN IFNULL(G.PB_RATE,0) = VV_LV3_RATE THEN VV_LV3
								WHEN IFNULL(G.PB_RATE,0) = VV_LV2_RATE THEN VV_LV2
								ELSE VV_LV1 END),
				   -- 当月TGS
					 IF(IFNULL(M.PV_PSS,0)>=VV_LV2_PV,VV_LV3,VV_LV1),
					 -- 截止当月PGS累计值
					 (CASE WHEN IFNULL( G.TOTAL_GPV, 0 )+ IFNULL( N.GPV, 0 ) >= VV_LV2_PV THEN VV_LV3
								 WHEN IFNULL( G.TOTAL_GPV, 0 )+ IFNULL( N.GPV, 0 ) >= VV_LV1_PV THEN VV_LV2
								 ELSE VV_LV1 END)
				 ) PB_LV,
				 -- Performance Bonus对应级别比例 比较取最大
				 GREATEST(
				   -- 原始的比例
					 IFNULL(G.PB_RATE,VV_LV1_RATE),
				   -- 当月TGS
					 IF(IFNULL(M.PV_PSS,0)>=VV_LV2_PV,VV_LV3_RATE,VV_LV1_RATE),
					 -- 截止当月PGS累计值
					 (CASE WHEN IFNULL( G.TOTAL_GPV, 0 )+ IFNULL( N.GPV, 0 ) >= VV_LV2_PV THEN VV_LV3_RATE
								 WHEN IFNULL( G.TOTAL_GPV, 0 )+ IFNULL( N.GPV, 0 ) >= VV_LV1_PV THEN VV_LV2_RATE
								 ELSE VV_LV1_RATE END )
				 ) PB_RATE
    FROM AR_USER U
		LEFT JOIN AR_USER_RELATION_NEW R ON U.ID = R.USER_ID
		LEFT JOIN AR_CALC_PB_TOTAL_GPV_PUSH G ON U.ID = G.USER_ID
		LEFT JOIN AR_CALC_BE_E_NET N ON U.ID = N.USER_ID
		LEFT JOIN AR_PERF_MONTH M ON U.ID = M.USER_ID;
		COMMIT;

	-- 可以参与计算PB奖的会员及对应得奖等级和比例
	-- 	INSERT INTO AR_CALC_BE_PB_MID1 SELECT
	-- 	IV_PERIOD_NUM PERIOD_NUM,-- 周期
	-- 	IV_CALC_MONTH CALC_MONTH,-- 月份
	-- 	T.USER_ID,
	-- 	T.PARENT_UID,
	-- 	T.TOP_DEEP,
	-- 	T.GPV,-- 小组业绩
	-- 	T.PV_PCS,-- 个人业绩
	-- 	CASE
	-- 			WHEN T.TOTAL_GPV >= VV_LV2_PV THEN
	-- 			VV_LV3
	-- 			WHEN T.TOTAL_GPV >= VV_LV1_PV THEN
	-- 			VV_LV2 ELSE VV_LV1
	-- 		END AS PB_LV,-- Performance Bonus对应级别
	-- 	CASE
	-- 			WHEN T.TOTAL_GPV >= VV_LV2_PV THEN
	-- 			VV_LV3_RATE
	-- 			WHEN T.TOTAL_GPV >= VV_LV1_PV THEN
	-- 			VV_LV2_RATE ELSE VV_LV1_RATE
	-- 		END AS PB_RATE,-- Performance Bonus对应级别比例
	-- 		T.TOTAL_GPV,
	-- 		T.COUNTRY_ID,
	-- 		T.ELITE_CALC_ID
	-- 	FROM
	-- 		AR_CALC_PB_TOTAL_GPV T;
	-- 	COMMIT;

	SELECT MAX( TOP_DEEP ) INTO VV_MAX_COUNT
		FROM AR_CALC_PB_TOTAL_GPV
	 WHERE PV_PCS > 0
		 AND GPV < 1000;

	SET VV_COUNT = VV_MAX_COUNT;

	WHILE VV_COUNT >= 0 DO
		INSERT INTO AR_CALC_BE_PB_MID2
		SELECT T.PERIOD_NUM,-- 周期
					 T.CALC_MONTH,-- 月份
					 T.USER_ID,
					 T.PARENT_UID,
					 T.TOP_DEEP,
					 T.GPV,-- 小组业绩
					 T.PV_PCS,-- 个人业绩
					 T.PB_LV,-- PERFORMANCE BONUS对应级别
					 T.PB_RATE, -- PERFORMANCE BONUS对应级别比例
					 T.TOTAL_GPV,
					 T.COUNTRY_ID,
					 T.ELITE_CALC_ID,
					 IF(T.GPV >= 1000 , 0 ,TRUNCATE(T.PV_PCS*T.PB_RATE,2) ) BONUS_ONESELF,
					 IF(T.GPV >= 1000 , 0 ,IF(PB_LV >= 20, 0 , TRUNCATE(T.PV_PCS*0.1,2)+IFNULL(T1.BONUS_20,0) )) BONUS_20,
					 IF(T.GPV >= 1000 , 0 ,IF(PB_LV = 30, 0 , TRUNCATE(T.PV_PCS*0.1,2)+IFNULL(T1.BONUS_30,0) )) BONUS_30,
					 IF(T.GPV >= 1000 , 0 ,TRUNCATE(T.PV_PCS*T.PB_RATE,2)+IF(T.PB_LV >= 20,IFNULL(T1.BONUS_20,0),0)+IF(T.PB_LV >= 30,IFNULL(T1.BONUS_30,0),0)) BONUS_PB,
					 T.GPV PB_PV
		  FROM AR_CALC_PB_TOTAL_GPV T
			LEFT JOIN (SELECT PARENT_UID USER_ID,
												SUM( BONUS_20 ) BONUS_20,
												SUM( BONUS_30 ) BONUS_30
									 FROM AR_CALC_BE_PB_MID2
								  WHERE TOP_DEEP = VV_COUNT + 1
									  AND ELITE_CALC_ID = 0
								  GROUP BY PARENT_UID
								) T1 ON T.USER_ID = T1.USER_ID
		 WHERE T.TOP_DEEP = VV_COUNT;
		COMMIT;

		SET VV_COUNT = VV_COUNT - 1;

	END WHILE;

	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');

	INSERT INTO AR_CALC_BONUS_PB
	SELECT CONCAT(VV_TIME_STR, LPAD( @ROWNUM := @ROWNUM + 1, 8, '0' )) AS ID,-- 年月日时分秒14+排序8
				 IV_PERIOD_NUM AS PERIOD_NUM,
				 IV_CALC_MONTH AS CALC_MONTH,
				 T.USER_ID,
				 T.BONUS_PB,
				 T.COUNTRY_ID AS COUNTRY_ID,
				 T.PB_PV
		FROM ( SELECT @ROWNUM := 0 FROM DUAL ) R,
			   AR_CALC_BE_PB_MID2 T
	 WHERE T.BONUS_PB > 0;
	COMMIT;
END