CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_LB`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
	DECLARE VV_TOTAL_PV
	  DECIMAL(16,2);
	DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字
	/*--------------------------------------------表说明--------------------------------------------*/
	/*
	  AR_CALC_BE_LB_MID1：每层奖衔总业绩
	  AR_CALC_BE_LB_MID2：每层奖衔对应的加权平分比例
	  AR_CALC_BE_LB_DETAIL：会员每层可得奖明细
	*/
	-- 每层奖衔总业绩
	INSERT INTO AR_CALC_BE_LB_MID1
	SELECT LAYER_CALC_ID,
				 SUM(LB_PV) AS TOTAL_LB_PV
	  FROM AR_CALC_LV_HONOR_PV T
	 GROUP BY LAYER_CALC_ID;

	 SELECT IFNULL(SUM(T.PV_PCS),0)
	   INTO VV_TOTAL_PV
	   FROM AR_PERF_MONTH T
	  WHERE T.PERIOD_NUM = IV_PERIOD_NUM;
	-- 每层奖衔对应的加权平分比例
	 INSERT INTO AR_CALC_BE_LB_MID2
	 SELECT T.LAYER_CALC_ID,
	        T.TOTAL_LB_PV,
	        VV_TOTAL_PV AS TOTAL_PV,
					IFNULL(T1.VALUE,0)/100 AS HONOR_RATE,
					TRUNCATE(IFNULL(T1.VALUE,0)/100 * VV_TOTAL_PV,6) AS HONOR_BONUS,
					TRUNCATE(TRUNCATE(IFNULL(T1.VALUE,0)/100 * VV_TOTAL_PV,6)/T.TOTAL_LB_PV,6) AS LB_RATE
	   FROM AR_CALC_BE_LB_MID1 T
		 LEFT JOIN AR_CONFIG T1 ON T1.CONFIG_NAME = CONCAT('leadershipRate',T.LAYER_CALC_ID)
		                       AND T1.TYPE = 'bonus'
	  WHERE T.TOTAL_LB_PV > 0;
	COMMIT;
	-- 会员每层可得奖明细
	INSERT INTO AR_CALC_BE_LB_DETAIL
	SELECT T.PERIOD_NUM,-- 周期
				 T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.LAYER_LV,
				 T.LAYER_CALC_ID,
				 T.LB_PV,
				 T.BONUS_HONOR_LV,
				 T.BONUS_HONOR_CALC_ID,
				 IFNULL(T1.TOTAL_LB_PV,0) AS TOTAL_LB_PV,
	       IFNULL(T1.TOTAL_PV,0) AS TOTAL_PV,
				 IFNULL(T1.HONOR_RATE,0) AS HONOR_RATE,
				 IFNULL(T1.HONOR_BONUS,0) AS HONOR_BONUS,
				 IFNULL(T1.LB_RATE,0) AS LB_RATE,
				 TRUNCATE(T.LB_PV * IFNULL(T1.LB_RATE,0),2) BONUS_LB
	  FROM AR_CALC_LV_HONOR_PV T
		LEFT JOIN AR_CALC_BE_LB_MID2 T1 ON T1.LAYER_CALC_ID = T.LAYER_CALC_ID;
	COMMIT;

	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	-- 会员的Leadership Bonus
	INSERT INTO AR_CALC_BONUS_LB
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
	       IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
				 IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID,
				 IFNULL(T1.LAST_HONOR_LV,'-1') AS LAST_HONOR_LV,
				 IFNULL(T1.LAST_HONOR_CALC_ID,-1) AS LAST_HONOR_CALC_ID,
				 T.ORI_BONUS_LB,
				 T.BONUS_LB,
				 IFNULL(T2.COUNTRY_ID,'-1') AS COUNTRY_ID,
				 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE
	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,
		     (SELECT A.USER_ID,
		             TRUNCATE(SUM(A.BONUS_LB),2) AS ORI_BONUS_LB,
				         TRUNCATE(IFNULL(SUM(CASE WHEN A.LAYER_CALC_ID <= A.BONUS_HONOR_CALC_ID THEN A.BONUS_LB END),0),2) AS BONUS_LB
		        FROM AR_CALC_BE_LB_DETAIL A
					 GROUP BY A.USER_ID) T
	  LEFT JOIN AR_CALC_LV_HONOR T1 ON T1.USER_ID = T.USER_ID
		LEFT JOIN AR_USER T2 ON T2.ID = T.USER_ID
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID
	 WHERE T.BONUS_LB > 0;
	COMMIT;
END