CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_COUNTRY_SHARE`(IN IV_PERIOD_NUM INT)
BEGIN
  DECLARE STR_SQL VARCHAR(500);
  DECLARE VV_COUNT,VV_COUNT1,VV_ORDER_NUMBER INT;
  DECLARE VV_USER_ID,VV_COUNTRY_ID VARCHAR(32);
  DECLARE VV_PV DECIMAL(16,2);
	TRUNCATE TABLE AR_PERF_ORDER_COUNTRY_SHARE;
	TRUNCATE TABLE AR_USER_RELATION_NEW_COUNTRY_SHARE;
	TRUNCATE TABLE AR_PERF_MONTH_COUNTRY_SHARE;
	TRUNCATE TABLE AR_CALC_DATA_CS_LOG;
	TRUNCATE TABLE AR_CALC_DATA_CS_MID1;
	TRUNCATE TABLE AR_CALC_DATA_CS_MID2;
	TRUNCATE TABLE AR_CALC_DATA_CS_MID3;
	TRUNCATE TABLE AR_CALC_DATA_CS_MID4;
	TRUNCATE TABLE AR_CALC_DATA_CS_DETAILS;

	-- 使用备份表中的订单表，推荐网关系表
	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'insert AR_PERF_ORDER_COUNTRY_SHARE',NOW());
	COMMIT;
	SET STR_SQL = CONCAT('INSERT INTO AR_PERF_ORDER_COUNTRY_SHARE SELECT T.* FROM ZZAR_PERF_ORDER_',IV_PERIOD_NUM,' T');
	PREPARE stmt1 FROM STR_SQL;
	##执行SQL语句
	EXECUTE stmt1;
	## 释放掉预处理段
	DEALLOCATE PREPARE stmt1;

	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'insert AR_USER_RELATION_NEW_COUNTRY_SHARE',NOW());
	COMMIT;
	SET STR_SQL = CONCAT('INSERT INTO AR_USER_RELATION_NEW_COUNTRY_SHARE SELECT T.* FROM ZZAR_USER_RELATION_NEW_',IV_PERIOD_NUM,' T');
	PREPARE stmt1 FROM STR_SQL;
	##执行SQL语句
	EXECUTE stmt1;
	## 释放掉预处理段
	DEALLOCATE PREPARE stmt1;

	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'insert AR_PERF_MONTH_COUNTRY_SHARE',NOW());
	COMMIT;
	SET STR_SQL = CONCAT('INSERT INTO AR_PERF_MONTH_COUNTRY_SHARE SELECT T.* FROM ZZAR_PERF_MONTH_',IV_PERIOD_NUM,' T');
	PREPARE stmt1 FROM STR_SQL;
	##执行SQL语句
	EXECUTE stmt1;
	## 释放掉预处理段
	DEALLOCATE PREPARE stmt1;

	-- 订单数据汇总
	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'insert AR_CALC_DATA_CS_MID1',NOW());
	COMMIT;
	INSERT INTO AR_CALC_DATA_CS_MID1
	SELECT IV_PERIOD_NUM PERIOD_NUM,
	       USER_ID,
	       IF(IFNULL(T.COUNTRY_ID,'') = '','1',T.COUNTRY_ID) COUNTRY_ID,
				 SUM(PV) PV,
				 COUNT(*) ORDER_NUMBER
	  FROM AR_PERF_ORDER_COUNTRY_SHARE T
	 GROUP BY T.USER_ID,IF(IFNULL(T.COUNTRY_ID,'') = '','1',T.COUNTRY_ID);
	COMMIT;

	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'insert AR_CALC_DATA_CS_MID2',NOW());
	COMMIT;
	INSERT INTO AR_CALC_DATA_CS_MID2
	SELECT PERIOD_NUM,
	       USER_ID
	  FROM AR_CALC_DATA_CS_MID1 T
	 GROUP BY T.USER_ID,T.PERIOD_NUM;
	COMMIT;

	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'insert AR_CALC_DATA_CS_MID3',NOW());
	COMMIT;
	SELECT COUNT(1) - 1 INTO VV_COUNT FROM AR_CALC_DATA_CS_MID2;
	-- 当月个人团队业绩明细（推荐网）
	WHILE VV_COUNT >= 0 DO
		INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,VV_COUNT,NOW());
		COMMIT;
	  -- 第VV_COUNT+1条数据中用户的业绩
		SELECT T.USER_ID
		  INTO VV_USER_ID
	    FROM AR_CALC_DATA_CS_MID2 T
			LIMIT VV_COUNT,1;
	  -- 第VV_COUNT+1条数据中用户的业绩向上贡献团队业绩
		INSERT INTO AR_CALC_DATA_CS_MID3-- 当月用户个人团队业绩来源
	  WITH RECURSIVE T_REC AS
		(SELECT A.USER_ID,
			      A.PARENT_UID
		   FROM AR_USER_RELATION_NEW_COUNTRY_SHARE A
		  WHERE A.USER_ID = VV_USER_ID
		 UNION ALL
		 SELECT A1.USER_ID,
		        A1.PARENT_UID
			 FROM AR_USER_RELATION_NEW_COUNTRY_SHARE A1
		  INNER JOIN T_REC A2 ON A2.PARENT_UID = A1.USER_ID
	  )SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
						T.USER_ID,-- 用户
						T.PARENT_UID,
						CM1.COUNTRY_ID AS SOURCE_COUNTRY_ID,
					  CM1.USER_ID AS SOURCE_USER_ID,-- 业绩来源的用户
					  CM1.PV AS SOURCE_PV_PCS,-- 业绩
						CM1.ORDER_NUMBER AS SOURCE_ORDER_NUMBER
	     FROM T_REC T
			INNER JOIN AR_CALC_DATA_CS_MID1 CM1 ON CM1.USER_ID = VV_USER_ID;
		COMMIT;
		-- 循环计数减一
	  SET VV_COUNT = VV_COUNT - 1;
  END WHILE;

	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'insert AR_CALC_DATA_CS_MID4',NOW());
	COMMIT;
	INSERT INTO AR_CALC_DATA_CS_MID4
	SELECT T.PERIOD_NUM,
	       T.USER_ID,
	       T.PARENT_UID,
				 T.SOURCE_COUNTRY_ID COUNTRY_ID,
				 SUM(T.SOURCE_PV_PCS) AS PV,
				 SUM(T.SOURCE_ORDER_NUMBER) AS ORDER_NUMBER,
				 COUNT(DISTINCT T.SOURCE_USER_ID) AS USER_NUMBER
	  FROM AR_CALC_DATA_CS_MID3 T
	 GROUP BY T.PERIOD_NUM,T.USER_ID,T.PARENT_UID,T.SOURCE_COUNTRY_ID;
	COMMIT;

	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'insert AR_CALC_DATA_CS_DETAILS',NOW());
	COMMIT;
	INSERT INTO AR_CALC_DATA_CS_DETAILS
	SELECT T.PERIOD_NUM,
	       T.USER_ID,
	       T.PARENT_UID,
				 T.COUNTRY_ID,
				 C.`CODE` AS COUNTRY_CODE,
				 T.PV,
				 T.ORDER_NUMBER,
				 T.USER_NUMBER,
				 CASE WHEN IFNULL(T1.PV_PSS,0) = 0 THEN 0 ELSE TRUNCATE(T.PV/T1.PV_PSS,4) END PV_RATE
	  FROM AR_CALC_DATA_CS_MID4 T
	  LEFT JOIN AR_COUNTRY C ON T.COUNTRY_ID = C.ID
		LEFT JOIN AR_PERF_MONTH_COUNTRY_SHARE T1 ON T.USER_ID = T1.USER_ID;
	COMMIT;

	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'backup',NOW());
	COMMIT;
	CALL CALC_BACKUP_COUNTRY_SHARE(IV_PERIOD_NUM);
	INSERT INTO AR_CALC_DATA_CS_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (IV_PERIOD_NUM,'end',NOW());
	COMMIT;
END