CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_REM_DATA_copy`(IV_PERIOD_NUM INT)
BEGIN
	DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字
  -- 清理数据
	/*初始化推荐网体对应的层数*/
	-- 中间表

  /*月业绩*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_PV_MID1;
	TRUNCATE TABLE AR_CALC_PV_MID2;
	TRUNCATE TABLE AR_CALC_PV_MID3;
	TRUNCATE TABLE AR_CALC_PV_MID4;
	TRUNCATE TABLE AR_CALC_PV_MID5;
	TRUNCATE TABLE AR_CALC_PV_MID6;
	TRUNCATE TABLE AR_CALC_PV_MID7;
	TRUNCATE TABLE AR_CALC_PV_MID8;
  -- 结果表
	TRUNCATE TABLE AR_PERF_MONTH;

	/*续约【业务系统处理】*/
	-- 中间表
	-- TRUNCATE TABLE AR_CALC_EFFECT_MID1;

	/*Elite奖*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_BE_E_MID1;
	TRUNCATE TABLE AR_CALC_BE_E_NET;
	-- 结果表
	TRUNCATE TABLE AR_CALC_BONUS_E;

	/*Elite级别及相关业绩*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_LV_ELITE_MID1;
	TRUNCATE TABLE AR_CALC_LV_ELITE_MID2;
	TRUNCATE TABLE AR_CALC_LV_ELITE_MID3;
	TRUNCATE TABLE AR_CALC_LV_ELITE_MID4;
	TRUNCATE TABLE AR_CALC_LV_ELITE_MID5;
	TRUNCATE TABLE AR_CALC_LV_ELITE_MID6;
	TRUNCATE TABLE AR_CALC_LV_ELITE_MID7;
	-- 结果表
	TRUNCATE TABLE AR_CALC_LV_ELITE;
	TRUNCATE TABLE AR_CALC_LV_ELITE_REAL;

	/*Pro Elite奖*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_BE_PE_MID1;
	-- 结果表
	TRUNCATE TABLE AR_CALC_BONUS_PE;

	/*Super Elite奖*/
		-- 中间表
	TRUNCATE TABLE AR_CALC_LV_ELITE_1;
	-- 结果表
	TRUNCATE TABLE AR_CALC_BONUS_SE;

	/*最新奖衔级别及相关业绩*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID1;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID2;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID3;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID4;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID5;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID6;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID7;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID8;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID9;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID10;
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID11;
	-- 结果表
	TRUNCATE TABLE AR_CALC_LV_HONOR;
	TRUNCATE TABLE AR_CALC_LV_HONOR_PV;

	/*Leadership奖*/
	-- 中间表：
	TRUNCATE TABLE AR_CALC_BE_LB_MID1;
	TRUNCATE TABLE AR_CALC_BE_LB_MID2;
	-- 结果表
	TRUNCATE TABLE AR_CALC_BE_LB_DETAIL;
	TRUNCATE TABLE AR_CALC_BONUS_LB;

  /*Leadership奖按国家*/
	-- 中间表：
	TRUNCATE TABLE AR_CALC_LV_HONOR_MID1_1;
  TRUNCATE TABLE AR_CALC_LV_HONOR_MID2_1;
  TRUNCATE TABLE AR_CALC_LV_HONOR_MID3_1;
  TRUNCATE TABLE AR_CALC_LV_HONOR_MID4_1;
  TRUNCATE TABLE AR_CALC_LV_HONOR_MID5_1;
	TRUNCATE TABLE AR_CALC_LV_HONOR_PV_1;
	TRUNCATE TABLE AR_CALC_BE_LB_MID1_1;
	TRUNCATE TABLE AR_CALC_BE_LB_MID2_1;
	-- 结果表
	TRUNCATE TABLE AR_CALC_BE_LB_DETAIL_COUNTRY;
	TRUNCATE TABLE AR_CALC_BONUS_LB_COUNTRY;

	/*Team奖*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_BE_TB_MID1;
	TRUNCATE TABLE AR_CALC_BE_TB_MID2;
	TRUNCATE TABLE AR_CALC_BE_TB_MID3;
	-- 结果表
	TRUNCATE TABLE AR_CALC_BONUS_TB;

	/*最高奖衔*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_LV_HONOR_HIGH_MID1;
	TRUNCATE TABLE AR_CALC_LV_HONOR_HIGH_MID2;
	TRUNCATE TABLE AR_CALC_LV_HONOR_HIGH_MID3;
	TRUNCATE TABLE AR_CALC_LV_HONOR_HIGH_MID4;
	-- 结果表
	TRUNCATE TABLE AR_CALC_LV_HONOR_HIGH;

	/*Performance积分*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_BE_PB_MID1;
	-- 结果表
	TRUNCATE TABLE AR_CALC_BE_PB_DETAIL;
	TRUNCATE TABLE AR_CALC_BONUS_PB;

	/*Stockist fees奖*/
	-- 结果表
	TRUNCATE TABLE AR_CALC_BE_SFB_MID1;
	TRUNCATE TABLE AR_CALC_BONUS_SFB;

	/*Global pool Bonus奖*/
	-- 结果表
	TRUNCATE TABLE AR_CALC_BE_GPB_MID1;
	TRUNCATE TABLE AR_CALC_BE_GPB_MID2;
	TRUNCATE TABLE AR_CALC_BE_GPB_DETAIL;
	TRUNCATE TABLE AR_CALC_BONUS_GPB;

	/*Car Room Bonus奖*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_BE_CRB_MID1;
  TRUNCATE TABLE AR_CALC_BE_CRB_MID2_1;
  TRUNCATE TABLE AR_CALC_BE_CRB_MID2_2;
  TRUNCATE TABLE AR_CALC_BE_CRB_MID3_1;
  TRUNCATE TABLE AR_CALC_BE_CRB_MID3_2;
  TRUNCATE TABLE AR_CALC_BE_CRB_MID4_1;
  TRUNCATE TABLE AR_CALC_BE_CRB_MID4_2;
	-- 结果表
  TRUNCATE TABLE AR_CALC_BE_CRB_DETAIL_C;
  TRUNCATE TABLE AR_CALC_BE_CRB_DETAIL_R;
  TRUNCATE TABLE AR_CALC_BE_CRB_C;
  TRUNCATE TABLE AR_CALC_BE_CRB_R;
  TRUNCATE TABLE AR_CALC_BONUS_CRB;

	/*总奖*/
	-- 中间表
	TRUNCATE TABLE AR_CALC_BE_BE_MID1;
	TRUNCATE TABLE AR_CALC_BE_BE_MID2;
	-- 结果表
	TRUNCATE TABLE AR_CALC_BONUS;
		-- 不活跃奖金明细表
	TRUNCATE TABLE AR_INACTIVE_DETAILS;
	-- 续约初始化新增用户默认当月的介于业绩和奖衔级别
	UPDATE AR_USER_PERF
	   SET PERIOD_NUM = IV_PERIOD_NUM,
	       IS_ACTIVE =0,
		     TOTAL_1L = 0,
				 TOTAL_2L = 0,
				 MEMBERS_1L = 0,
				 MEMBERS_2L = 0;
	COMMIT;
	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	INSERT INTO AR_USER_PERF
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
				 IV_PERIOD_NUM AS PERIOD_NUM,
				 T.ID AS USER_ID,-- USER_ID,
				 0,-- SURPLUS_1L,
				 0,-- SURPLUS_2L,
				 0,-- TOTAL_1L,
				 0,-- TOTAL_2L,
				 0,-- MEMBERS_1L,
				 0,-- MEMBERS_2L,
				 0,-- 1MON_HONOR,
				 0,-- 2MON_HONOR,
				 0,-- 3MON_HONOR,
				 0,-- 4MON_HONOR,
				 0,-- 5MON_HONOR,
				 0,-- 6MON_HONOR,
				 NULL AS EFFECT_MONTH,
				 0 AS EFFECT_PV,
				 0 AS EFFECT_ACTIVE,
				 UNIX_TIMESTAMP() AS CREATE_AT,
				 0 AS IS_ACTIVE
	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,AR_USER T
		LEFT JOIN AR_USER_PERF T1 ON T.ID = T1.USER_ID
	 WHERE T1.USER_ID IS NULL;
  COMMIT;


END