CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BONUS_copy`(IV_PERIOD_NUM INT)
BEGIN
  -- 计算业绩和奖金

	/*定义变量*/
	DECLARE VV_CALC_MONTH -- 结算周期的月份
    TINYINT;-- 类型
	DECLARE VV_CALC_YEAR -- 结算周期的年份
	  INT;-- 类型
	DECLARE VV_CALC_ID -- 结算周期的年份
	  VARCHAR(32);-- 类型

	/*清除程序运行日志和结余表【当前操作在测试库会删除】*/
	TRUNCATE TABLE AR_CALC_BE_LOG;
	-- TRUNCATE TABLE AR_USER_PERF;

	/*变量赋值*/
	-- 结算周期对应的计算月和结算年
	SELECT T.CALC_YEAR,
	       T.CALC_MONTH,
				 T.CALC_ID
		INTO VV_CALC_YEAR,
		     VV_CALC_MONTH,
				 VV_CALC_ID
		FROM AR_PERIOD T
	 WHERE T.PERIOD_NUM = IV_PERIOD_NUM;

	/*开始*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'start',NOW());
	COMMIT;

	/*周期表的状态变更*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'modify period 2',NOW());
	COMMIT;
	CALL CALC_PERIOD_STATUS(IV_PERIOD_NUM,2);

	/*清理数据，更新结余表*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'clean data',NOW());
	COMMIT;
	CALL CALC_BE_REM_DATA(IV_PERIOD_NUM);

	/*初始化推荐网体对应的层数2个网体*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'modify net layer',NOW());
	COMMIT;
	CALL CALC_BE_NET();

	/*月业绩，更新结余表的活跃状态*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc month pv',NOW());
	COMMIT;
	CALL CALC_PV(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*周期表的状态变更*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'modify period 3',NOW());
	COMMIT;
	CALL CALC_PERIOD_STATUS(IV_PERIOD_NUM,3);

	/*续约【业务系统处理】*/
  -- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'',NOW());
  -- 	COMMIT;
	-- CALL CALC_EFFECT(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*Elite奖*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc elite bonus',NOW());
	COMMIT;
	CALL CALC_BE_E(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*Elite级别及相关业绩*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc elite level and pv',NOW());
	COMMIT;
	CALL CALC_LV_ELITE(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*Pro Elite奖*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc pro elite bonus',NOW());
	COMMIT;
	CALL CALC_BE_PE(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*Super Elite奖*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc super elite bonus',NOW());
	COMMIT;
	CALL CALC_BE_SE_COUNTRY(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*最新奖衔级别及相关业绩*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc last honor level and pv',NOW());
	COMMIT;
	CALL CALC_LV_HONOR_LAST(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*Leadership奖*/
-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc leadership bonus',NOW());
-- 	COMMIT;
-- 	CALL CALC_BE_LB(IV_PERIOD_NUM,VV_CALC_MONTH);

  /*Leadership奖按国家*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc leadership bonus',NOW());
	COMMIT;
	CALL CALC_BE_LB_COUNTRY(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*Team奖*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc team bonus',NOW());
	COMMIT;
	CALL CALC_BE_TB(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*最高奖衔*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc highest honor',NOW());
	COMMIT;
	CALL CALC_LV_HONOR_HIGH(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*Performance积分*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc performance bonus',NOW());
	COMMIT;
	CALL CALC_BE_PB(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*Stockist fees奖*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc stockist fees bonus',NOW());
	COMMIT;
	CALL CALC_BE_SFB(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*季度分红奖*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc global pool bonus',NOW());
	COMMIT;
	CALL CALC_BE_GPB(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*车房奖*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc car room bonus',NOW());
	COMMIT;
	CALL CALC_BE_CRB(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*总奖*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc total bonus',NOW());
	COMMIT;
	CALL CALC_BE(IV_PERIOD_NUM,VV_CALC_MONTH);

	/*计算但不发奖的会员明细*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc inactive details',NOW());
	COMMIT;
 	CALL CALC_INACTIVE_DETAILS(IV_PERIOD_NUM);

	/*备份*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'calc backup',NOW());
	COMMIT;
	CALL CALC_BACKUP(IV_PERIOD_NUM);

	/*周期表的状态变更*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'modify period 4',NOW());
	COMMIT;
	CALL CALC_PERIOD_STATUS(IV_PERIOD_NUM,4);

	/*结束*/
	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (VV_CALC_ID,'end',NOW());
	COMMIT;

END