CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_LB_COUNTRY`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
  DECLARE   VV_MAX_LAYER,
	        VV_TOTAL,
					VV_COUNT,
          VV_COUNT1,
					VV_COUNT2 INT;

	DECLARE VV_USER_ID,
	        VV_COUNTRY_ID,
					VV_TIME_STR,
					VV_REGION VARCHAR(32);

	DECLARE VV_LB_PV,
	        VV_TOTAL_PV DECIMAL(16,2);

	/*--------------------------------------------表说明--------------------------------------------*/
	/*
	  AR_CALC_BE_LB_MID1_1：每层奖衔总业绩
	  AR_CALC_BE_LB_MID2_1：每层奖衔对应的加权平分比例
	  AR_CALC_BE_LB_DETAIL_COUNTRY：会员每层可得奖明细
	*/

INSERT INTO AR_CALC_LV_HONOR_MID1_1
	SELECT PERIOD_NUM,-- 周期
				 CALC_MONTH,-- 月份
				 USER_ID,
				 PARENT_UID,
				 TOP_DEEP,
				 GPV,
				 GPV_REAL,
				 GPV_UNREAL,
				 SONS_NUM,
				 LAST_ELITE_CALC_ID,-- Elite级别
				 PARENT_UID AS PARENT_SE
	  FROM AR_CALC_LV_ELITE;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'2',NOW());
-- 	COMMIT;
	-- 找自己的第一个SE作为自己的PAREN_SE
	SELECT IFNULL(MAX(T.TOP_DEEP),-1) INTO VV_MAX_LAYER FROM AR_CALC_LV_HONOR_MID1_1 T;
	SET VV_TOTAL = VV_MAX_LAYER-1;
	WHILE VV_TOTAL >= 0 DO
	  -- 如果本人不是SE则将PAREN_SE是自己的改为自己的PARENT_UID
	  UPDATE AR_CALC_LV_HONOR_MID1_1 T
		 INNER JOIN (SELECT A.USER_ID,
		                    A.PARENT_UID
		               FROM AR_CALC_LV_HONOR_MID1_1 A
		              WHERE A.TOP_DEEP = VV_TOTAL
		                AND A.LAST_ELITE_CALC_ID <> 30) T1 ON T.PARENT_SE = T1.USER_ID
		   SET T.PARENT_SE = T1.PARENT_UID;
	  COMMIT;
		SET VV_TOTAL = VV_TOTAL - 1;
  END WHILE;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'3',NOW());
-- 	COMMIT;
	-- 计算自己向上贡献的第一层计奖业绩
	SET VV_TOTAL = VV_MAX_LAYER;
	WHILE VV_TOTAL > 0 DO
	  -- 所有SE自己第一层奖衔的计奖业绩明细
	  INSERT INTO AR_CALC_LV_HONOR_MID2_1
		SELECT T.PERIOD_NUM,-- 周期
				   T.CALC_MONTH,-- 月份
					 CASE WHEN T.PARENT_SE = T.PARENT_UID THEN T1.PARENT_SE
					      ELSE T.PARENT_SE END AS USER_ID,-- 获得业绩得用户
					 T.USER_ID AS SOURCE_USER_ID,-- 来源
					 T.GPV_REAL, -- 自己的推荐人是SE就需要把自己业绩贡献给推荐人的第一个SE
					 0 GPV_UNREAL,
					 T.TOP_DEEP,
					 U.COUNTRY_ID
		  FROM AR_CALC_LV_HONOR_MID1_1 T
			LEFT JOIN AR_CALC_LV_HONOR_MID1_1 T1 ON T.PARENT_UID = T1.USER_ID
			LEFT JOIN AR_USER U ON U.ID = T.USER_ID
		 WHERE T.TOP_DEEP = VV_TOTAL;
		COMMIT;
	  INSERT INTO AR_CALC_LV_HONOR_MID2_1
		SELECT T.PERIOD_NUM,-- 周期
				   T.CALC_MONTH,-- 月份
					 T.PARENT_SE AS USER_ID,-- 获得业绩得用户
					 T.USER_ID AS SOURCE_USER_ID,-- 来源
					 0 GPV_REAL,
					 T.GPV_UNREAL, -- 虚拟业绩直接给自己第一个SE
					 T.TOP_DEEP,
					 U.COUNTRY_ID
		  FROM AR_CALC_LV_HONOR_MID1_1 T
			LEFT JOIN AR_USER U ON U.ID = T.USER_ID
		 WHERE T.TOP_DEEP = VV_TOTAL
		   AND T.GPV_UNREAL > 0;
		COMMIT;
	  SET VV_TOTAL = VV_TOTAL - 1;
  END WHILE;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'4',NOW());
-- 	COMMIT;
	-- 所有SE自己第一层奖衔的计奖业绩
  INSERT INTO AR_CALC_LV_HONOR_MID3_1
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
				 IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID,
				 IFNULL(SUM(T.GPV_REAL + T.GPV_UNREAL),0) AS LB_PV,
				 T.COUNTRY_ID
	  FROM AR_CALC_LV_HONOR_MID2_1 T
	 WHERE T.USER_ID <> '0'
	 GROUP BY T.USER_ID,T.COUNTRY_ID;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'5',NOW());
-- 	COMMIT;
	-- 自己是SE且有计奖业绩的会员
	INSERT INTO AR_CALC_LV_HONOR_MID4_1
	SELECT T.PERIOD_NUM,-- 周期
				 T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.PARENT_UID,
				 T.TOP_DEEP,
				 T.GPV,
				 T.GPV_REAL,
				 T.GPV_UNREAL,
				 T.SONS_NUM,
				 T.LAST_ELITE_CALC_ID,-- Elite级别
				 T.PARENT_SE,
				 T1.LB_PV,
				 T1.COUNTRY_ID
	  FROM AR_CALC_LV_HONOR_MID3_1 T1
		LEFT JOIN AR_CALC_LV_HONOR_MID1_1 T ON T.USER_ID = T1.USER_ID
	 WHERE T1.LB_PV > 0;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'6',NOW());
-- 	COMMIT;
	--
	SELECT COUNT(1)
	  INTO VV_COUNT
		FROM AR_CALC_LV_HONOR_MID4_1 T
	 WHERE T.LB_PV > 0;

	SET VV_TOTAL = VV_COUNT - 1;

	WHILE VV_TOTAL >= 0 DO
	  SELECT T.USER_ID,T.LB_PV,T.COUNTRY_ID
		  INTO VV_USER_ID,VV_LB_PV,VV_COUNTRY_ID
			FROM AR_CALC_LV_HONOR_MID4_1 T
		 LIMIT VV_TOTAL,1;

	  -- 会员每层可以拿到的业绩(不是真实会员，此处还没有计算7/8/9时额外两条线的限制)
	  INSERT INTO AR_CALC_LV_HONOR_MID5_1
		WITH RECURSIVE T_REC AS -- RECURSIVE为关键字，可以不列出字段列表
		(SELECT A.PERIOD_NUM,
		        A.CALC_MONTH,
						A.USER_ID,
			      A.PARENT_SE AS PARENT_UID,
						10 AS LAYER_CALC_ID
		   FROM AR_CALC_LV_HONOR_MID4_1 A
		  WHERE A.USER_ID = VV_USER_ID AND COUNTRY_ID = VV_COUNTRY_ID
		 UNION ALL
		 SELECT A1.PERIOD_NUM,
		        A1.CALC_MONTH,
						A1.USER_ID,
		        A1.PARENT_SE AS PARENT_UID,
						A2.LAYER_CALC_ID + 10 AS LAYER_CALC_ID
			 FROM AR_CALC_LV_HONOR_MID4 A1 -- AR_CALC_LV_HONOR_MID4_1表是按照国家（大区）进行计算汇总的计奖业绩。AR_CALC_LV_HONOR_MID4表是按照总业绩计算汇总的计奖业绩。拿奖资格是按照总业绩来处理的。所以此处使用AR_CALC_LV_HONOR_MID4是因为按照总业绩是有计奖业绩，但是按照单国家（大区）是没有计奖业绩的。
		  INNER JOIN T_REC A2 ON A1.USER_ID = A2.PARENT_UID -- 递归生成的结果集T2的PARENT_ID与之前的源表ID关联
	  )SELECT T.PERIOD_NUM,
		        T.CALC_MONTH,
						T.USER_ID,
		        T.PARENT_UID,
						T.LAYER_CALC_ID,
						VV_LB_PV AS LB_PV,
						VV_COUNTRY_ID,
						VV_USER_ID AS SOURCE_USER_ID
		   FROM T_REC T;
		COMMIT;
		SET VV_TOTAL = VV_TOTAL - 1;
  END WHILE;

	-- 计算自己1 Star Director到3 Star Crown的计奖业绩
	INSERT INTO AR_CALC_LV_HONOR_PV_1
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
				 IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID,
				 T1.ID AS LAYER_LV,
				 T.LAYER_CALC_ID,
				 T.LB_PV,
				 T2.BONUS_HONOR_CALC_ID,
				 T2.BONUS_HONOR_LV,
				 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE,
				 T.COUNTRY_ID
	  FROM (SELECT A.USER_ID,
				         A.LAYER_CALC_ID,
								 SUM(A.LB_PV) AS LB_PV,
								 A.COUNTRY_ID
				    FROM AR_CALC_LV_HONOR_MID5_1 A
		        LEFT JOIN AR_CALC_LV_HONOR A1 ON A.USER_ID = A1.USER_ID
	         WHERE A.LAYER_CALC_ID <= A1.ORI_HONOR_CALC_ID
	         GROUP BY A.USER_ID,A.LAYER_CALC_ID,A.COUNTRY_ID) T
		LEFT JOIN	AR_HONOR_LEVEL T1 ON T1.CALC_ID = T.LAYER_CALC_ID
		LEFT JOIN	AR_CALC_LV_HONOR T2 ON T2.USER_ID = T.USER_ID
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID;

-- 多个国家合并成一个区域
	SELECT COUNT(1) INTO VV_COUNT2 FROM (SELECT COUNTRY_ID FROM AR_CALC_LV_HONOR_MID5_1 GROUP BY COUNTRY_ID) M;
	SET VV_COUNT1 = 0;
	WHILE VV_COUNT1 < VV_COUNT2 DO -- 按国家循环

		SELECT COUNTRY_ID INTO VV_COUNTRY_ID FROM AR_CALC_LV_HONOR_MID5_1 GROUP BY COUNTRY_ID LIMIT VV_COUNT1,1;

		SET VV_REGION = '';

		SELECT T.VALUE INTO VV_REGION FROM AR_CONFIG T WHERE T.CONFIG_NAME = CONCAT('Country',VV_COUNTRY_ID);

		IF VV_REGION IS NOT NULL AND VV_REGION != '' THEN
		   UPDATE AR_CALC_LV_HONOR_PV_1 SET COUNTRY_ID = VV_REGION WHERE COUNTRY_ID = VV_COUNTRY_ID;
		END IF;

		SET VV_COUNT1 = VV_COUNT1 + 1;
  END WHILE;


-- 开始奖金计算


	SELECT COUNT(1) INTO VV_COUNT2 FROM (SELECT COUNTRY_ID FROM AR_CALC_LV_HONOR_PV_1 GROUP BY COUNTRY_ID) M;

	SET VV_COUNT1 = 0;

	WHILE VV_COUNT1 < VV_COUNT2 DO -- 按国家循环

		SELECT COUNTRY_ID INTO VV_COUNTRY_ID FROM AR_CALC_LV_HONOR_PV_1 GROUP BY COUNTRY_ID LIMIT VV_COUNT1,1;

	-- 每层奖衔总业绩
	INSERT INTO AR_CALC_BE_LB_MID1_1
	SELECT
	O.LAYER_CALC_ID,
	SUM(O.LB_PV) AS TOTAL_LB_PV,
	O.COUNTRY_ID
	FROM
	AR_CALC_LV_HONOR_PV_1 O
	WHERE O.COUNTRY_ID = VV_COUNTRY_ID
	GROUP BY O.LAYER_CALC_ID;

	IF VV_COUNTRY_ID IN (SELECT `VALUE` FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus') THEN

	SELECT IFNULL(SUM(T.PV_PCS),0)
	   INTO VV_TOTAL_PV
	   FROM AR_PERF_MONTH T
	  WHERE T.PERIOD_NUM = IV_PERIOD_NUM
		AND COUNTRY_ID IN (SELECT SUBSTRING(CONFIG_NAME,8) FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus' AND `VALUE`=VV_COUNTRY_ID); -- 这个国家总业绩

	ELSE

	SELECT IFNULL(SUM(T.PV_PCS),0)
	   INTO VV_TOTAL_PV
	   FROM AR_PERF_MONTH T
	  WHERE T.PERIOD_NUM = IV_PERIOD_NUM AND COUNTRY_ID = VV_COUNTRY_ID; -- 这个国家总业绩

	END IF;

	-- 每层奖衔对应的加权平分比例
	 INSERT INTO AR_CALC_BE_LB_MID2_1
	 SELECT T.LAYER_CALC_ID,
	        T.TOTAL_LB_PV,
	        VV_TOTAL_PV AS TOTAL_PV,
					IFNULL(T1.VALUE,0)/100 AS HONOR_RATE,
					TRUNCATE(IFNULL(T1.VALUE,0)/100 * VV_TOTAL_PV,6) AS HONOR_BONUS,
					TRUNCATE(TRUNCATE(IFNULL(T1.VALUE,0)/100 * VV_TOTAL_PV,6)/T.TOTAL_LB_PV,6) AS LB_RATE,
					T.COUNTRY_ID
	   FROM AR_CALC_BE_LB_MID1_1 T
		 LEFT JOIN AR_CONFIG T1 ON T1.CONFIG_NAME = CONCAT('leadershipRate',T.LAYER_CALC_ID)
		                       AND T1.TYPE = 'bonus'
	  WHERE T.TOTAL_LB_PV > 0 AND T.COUNTRY_ID = VV_COUNTRY_ID;
	COMMIT;

	-- 会员每层可得奖明细 20250203 add AR_CALC_BE_LB_DETAIL_COUNTRY1
	INSERT INTO AR_CALC_BE_LB_DETAIL_COUNTRY1
	SELECT T.PERIOD_NUM,-- 周期
				 T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.LAYER_LV,
				 T.LAYER_CALC_ID,
				 SUM(T.LB_PV),
				 T.BONUS_HONOR_LV,
				 T.BONUS_HONOR_CALC_ID,
				 T1.TOTAL_LB_PV AS TOTAL_LB_PV,
	       T1.TOTAL_PV AS TOTAL_PV,
				 T1.HONOR_RATE AS HONOR_RATE,
				 T1.HONOR_BONUS AS HONOR_BONUS,
				 T1.LB_RATE AS LB_RATE,
				 SUM(TRUNCATE(T.LB_PV * IFNULL(T1.LB_RATE,0),2)) BONUS_LB,
				 T.COUNTRY_ID
	  FROM AR_CALC_LV_HONOR_PV_1 T
		LEFT JOIN AR_CALC_BE_LB_MID2_1 T1 ON T1.LAYER_CALC_ID = T.LAYER_CALC_ID
		WHERE T.COUNTRY_ID = VV_COUNTRY_ID AND T1.COUNTRY_ID = VV_COUNTRY_ID GROUP BY T.USER_ID,T.LAYER_LV,T.COUNTRY_ID;
	COMMIT;

	SET VV_COUNT1 = VV_COUNT1 + 1;
  END WHILE;

    	-- 多国家大区改为会员所在国家  20250203 drop sql
--   UPDATE AR_CALC_BE_LB_DETAIL_COUNTRY A
--   LEFT JOIN AR_USER U ON A.USER_ID = U.ID
--   SET A.COUNTRY_ID = U.COUNTRY_ID
--   WHERE
--     A.COUNTRY_ID IN ( SELECT DISTINCT `VALUE` FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus' )
--     AND U.COUNTRY_ID IN ( SELECT DISTINCT SUBSTRING(CONFIG_NAME,8) FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus');

  INSERT INTO AR_CALC_BE_LB_DETAIL_COUNTRY
  SELECT T.PERIOD_NUM,-- 周期
				 T.CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.LAYER_LV,
				 T.LAYER_CALC_ID,
				 T.LB_PV,
				 T.BONUS_HONOR_LV,
				 T.BONUS_HONOR_CALC_ID,
				 T.TOTAL_LB_PV,
	       T.TOTAL_PV,
				 T.HONOR_RATE,
				 T.HONOR_BONUS,
				 T.LB_RATE,
				 T.BONUS_LB,
				 IF(T.COUNTRY_ID = AC.`VALUE`,U.COUNTRY_ID,T.COUNTRY_ID) COUNTRY_ID
    FROM AR_CALC_BE_LB_DETAIL_COUNTRY1 T
    LEFT JOIN AR_USER U ON T.USER_ID = U.ID
    LEFT JOIN (SELECT DISTINCT SUBSTRING(CONFIG_NAME,8) COUNTRY_ID,`VALUE` FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus') AC ON AC.COUNTRY_ID = U.COUNTRY_ID;
  COMMIT;

	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	-- 会员的Leadership Bonus
	INSERT INTO AR_CALC_BONUS_LB_COUNTRY
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
	       IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
				 IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID,
				 IFNULL(T1.LAST_HONOR_LV,'-1') AS LAST_HONOR_LV,
				 IFNULL(T1.LAST_HONOR_CALC_ID,-1) AS LAST_HONOR_CALC_ID,
				 T.ORI_BONUS_LB,
				 T.BONUS_LB,
				 IFNULL(T2.COUNTRY_ID,'-1') AS COUNTRY_ID,
				 T.COUNTRY_ID AS BONUS_COUNTRY_ID,
				 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE
	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,
		     (SELECT A.USER_ID,
				         A.COUNTRY_ID,
		             TRUNCATE(SUM(A.BONUS_LB),2) AS ORI_BONUS_LB,
				         TRUNCATE(IFNULL(SUM(CASE WHEN A.LAYER_CALC_ID <= A.BONUS_HONOR_CALC_ID THEN A.BONUS_LB END),0),2) AS BONUS_LB
		        FROM AR_CALC_BE_LB_DETAIL_COUNTRY A
					 GROUP BY A.USER_ID,A.COUNTRY_ID) T
	  LEFT JOIN AR_CALC_LV_HONOR T1 ON T1.USER_ID = T.USER_ID
		LEFT JOIN AR_USER T2 ON T2.ID = T.USER_ID
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID
	 WHERE T.BONUS_LB > 0;
	COMMIT;

	-- 汇总

	INSERT INTO AR_CALC_BE_LB_DETAIL
	SELECT O.PERIOD_NUM,-- 周期
				 O.CALC_MONTH,-- 月份
				 O.USER_ID,
				 O.LAYER_LV,
				 O.LAYER_CALC_ID,
				 SUM(O.LB_PV),
				 O.BONUS_HONOR_LV,
				 O.BONUS_HONOR_CALC_ID,
				 SUM(O.TOTAL_LB_PV) AS TOTAL_LB_PV,
	       SUM(O.TOTAL_PV) AS TOTAL_PV,
				 O.HONOR_RATE AS HONOR_RATE,
				 SUM(O.HONOR_BONUS) AS HONOR_BONUS,
				 SUM(O.BONUS_LB)/SUM(O.LB_PV) AS LB_RATE,
				 SUM(O.BONUS_LB)
  FROM
	AR_CALC_BE_LB_DETAIL_COUNTRY O  GROUP BY O.USER_ID,O.LAYER_CALC_ID;
	COMMIT;

	INSERT INTO AR_CALC_BONUS_LB
	SELECT ID,-- 年月日时分秒14+排序8
	       IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
				 IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T.USER_ID,
				 T.LAST_HONOR_LV AS LAST_HONOR_LV,
				 T.LAST_HONOR_CALC_ID AS LAST_HONOR_CALC_ID,
				 SUM(T.ORI_BONUS_LB),
				 SUM(T.BONUS_LB),
				 T.COUNTRY_ID,
				 T.IS_ACTIVE
	  FROM AR_CALC_BONUS_LB_COUNTRY T GROUP BY T.USER_ID;
	COMMIT;

	INSERT INTO AR_CALC_BE_LB_MID3
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
	       IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 T2.USER_ID AS BONUS_USER_ID,
				 U2.USER_NAME AS BONUS_USER_NAME,
				 U2.REAL_NAME AS BONUS_REAL_NAME,
				 T1.SOURCE_USER_ID,-- 来源
				 U1.USER_NAME AS SOURCE_USER_NAME,
				 U1.REAL_NAME AS SOURCE_REAL_NAME,
				 T2.LAYER_CALC_ID AS BONUS_LAYER, -- 得奖层次
				 T1.GPV_REAL AS SOURCE_GPV_REAL, -- 小组业绩
				 T1.GPV_UNREAL AS SOURCE_GPV_UNREAL, -- 虚拟业绩
				 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE,
				 U1.COUNTRY_ID AS SOURCE_COUNTRY_ID,
				 -- 如果贡献国家存在大区，需要判定贡献国家对应的大区和得奖会员国家对应的大区是否一致，如果一致使用得奖会员的国家，否则贡献国家对应的大区的默认国家
				 IF(RC1.COUNTRY_ID IS NOT NULL,IF(RC1.REGION = RC2.REGION,U2.COUNTRY_ID,RC1.REGION),U1.COUNTRY_ID) BONUS_COUNTRY_ID,
				 H.ORI_HONOR_LV,
				 H.ORI_HONOR_CALC_ID,
				 H.BONUS_HONOR_LV,
				 H.BONUS_HONOR_CALC_ID
	  FROM AR_CALC_LV_HONOR_MID2_1 T1 -- 所有SE会员各国家的第一层奖衔的计奖业绩明细
	 INNER JOIN (SELECT SOURCE_USER_ID,USER_ID,LAYER_CALC_ID
	               FROM AR_CALC_LV_HONOR_MID5_1 -- 会员每层可以拿到的业绩
							  GROUP BY SOURCE_USER_ID,USER_ID,LAYER_CALC_ID) T2 ON T1.USER_ID = T2.SOURCE_USER_ID
	 INNER JOIN AR_USER U1 ON T1.SOURCE_USER_ID = U1.ID
	 INNER JOIN AR_USER U2 ON T2.USER_ID = U2.ID
	  LEFT JOIN (SELECT `VALUE` AS REGION, SUBSTRING(CONFIG_NAME,8) COUNTRY_ID FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus') RC1 ON RC1.COUNTRY_ID = U1.COUNTRY_ID
	  LEFT JOIN (SELECT `VALUE` AS REGION, SUBSTRING(CONFIG_NAME,8) COUNTRY_ID FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus') RC2 ON RC2.COUNTRY_ID = U2.COUNTRY_ID
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T2.USER_ID
		LEFT JOIN AR_CALC_LV_HONOR H ON H.USER_ID = T2.USER_ID;
	COMMIT;

	INSERT INTO AR_CALC_BONUS_LB_COUNTRY_SOURCE
	SELECT T.PERIOD_NUM,-- 周期
	       T.CALC_MONTH,-- 月份
				 T.BONUS_USER_ID,
				 T.BONUS_USER_NAME,
				 T.BONUS_REAL_NAME,
				 T.SOURCE_USER_ID,-- 来源
				 T.SOURCE_USER_NAME,
				 T.SOURCE_REAL_NAME,
				 T.BONUS_LAYER, -- 得奖层次
				 T.SOURCE_GPV_REAL, -- 小组业绩
				 T.SOURCE_GPV_UNREAL, -- 虚拟业绩
				 T.IS_ACTIVE,
				 T.SOURCE_COUNTRY_ID,
				 T.BONUS_COUNTRY_ID,
				 T.ORI_HONOR_LV,
				 T.ORI_HONOR_CALC_ID,
				 T.BONUS_HONOR_LV,
				 T.BONUS_HONOR_CALC_ID
	  FROM AR_CALC_BE_LB_MID3 T
	 WHERE (T.SOURCE_GPV_REAL > 0 OR T.SOURCE_GPV_UNREAL > 0)
	   AND T.BONUS_LAYER <= T.BONUS_HONOR_CALC_ID;
	COMMIT;
END