CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_COUNTRY_SHARE_LB`(IN IV_PERIOD_NUM INT)
BEGIN
	DECLARE STR_SQL VARCHAR(2000);

	TRUNCATE TABLE AR_USER_COUNTRY_SHARE;
	TRUNCATE TABLE AR_CALC_BONUS_LB_COUNTRY_SHARE;
	TRUNCATE TABLE AR_COUNTRY_SHARE_LB;

	SET STR_SQL = CONCAT('INSERT INTO AR_USER_COUNTRY_SHARE SELECT T.* FROM ZZAR_USER_',IV_PERIOD_NUM,' T');
	PREPARE stmt1 FROM STR_SQL;
	##执行SQL语句
	EXECUTE stmt1;
	## 释放掉预处理段
	DEALLOCATE PREPARE stmt1;

	SET STR_SQL = CONCAT('INSERT INTO AR_CALC_BONUS_LB_COUNTRY_SHARE SELECT T.* FROM ZZAR_CALC_BONUS_LB_',IV_PERIOD_NUM,' T');
	PREPARE stmt1 FROM STR_SQL;
	##执行SQL语句
	EXECUTE stmt1;
	## 释放掉预处理段
	DEALLOCATE PREPARE stmt1;


	SET STR_SQL = CONCAT('INSERT INTO AR_COUNTRY_SHARE_LB
	SELECT
		C.USER_ID,
		U.USER_NAME,
		U.REAL_NAME,
	CASE WHEN C.COUNTRY_ID = 1 THEN ''Malaysia''
			 WHEN C.COUNTRY_ID = 10 THEN ''United States of America''
			 WHEN C.COUNTRY_ID = 2 THEN ''Thailand''
			 WHEN C.COUNTRY_ID = 233 THEN ''United Arab Emirates''
			 WHEN C.COUNTRY_ID = 3 THEN ''Brunei''
			 WHEN C.COUNTRY_ID = 4 THEN ''Singapore''
			 WHEN C.COUNTRY_ID = 5 THEN ''Taiwan''
			 WHEN C.COUNTRY_ID = 6 THEN ''Hong Kong''
			 WHEN C.COUNTRY_ID = 7 THEN ''Cambodia''
			 WHEN C.COUNTRY_ID = 8 THEN ''Philippines''
			 WHEN C.COUNTRY_ID = 9 THEN ''Indonesia''	END `ORDER_COUNTRY_BV_SUM`,
	 CASE WHEN U.COUNTRY_ID = 1 THEN ''Malaysia''
			 WHEN U.COUNTRY_ID = 10 THEN ''United States of America''
			 WHEN U.COUNTRY_ID = 2 THEN ''Thailand''
			 WHEN U.COUNTRY_ID = 233 THEN ''United Arab Emirates''
			 WHEN U.COUNTRY_ID = 3 THEN ''Brunei''
			 WHEN U.COUNTRY_ID = 4 THEN ''Singapore''
			 WHEN U.COUNTRY_ID = 5 THEN ''Taiwan''
			 WHEN U.COUNTRY_ID = 6 THEN ''Hong Kong''
			 WHEN U.COUNTRY_ID = 7 THEN ''Cambodia''
			 WHEN U.COUNTRY_ID = 8 THEN ''Philippines''
			 WHEN U.COUNTRY_ID = 9 THEN ''Indonesia''	END USER_COUNTRY,
		C.PV `BV`,
		C.ORDER_NUMBER,
		C.USER_NUMBER,
		C.PV_RATE `LB_INTERNATIONAL_RATE`,
		L.BONUS_LB,
		L.BONUS_LB * C.PV_RATE BONUS_LB_GLOBAL
FROM
	ZZAR_CALC_DATA_CS_DETAILS_',IV_PERIOD_NUM,' C
	LEFT JOIN ZZAR_USER_',IV_PERIOD_NUM,' U ON U.ID = C.USER_ID
	LEFT JOIN ZZAR_CALC_BONUS_LB_',IV_PERIOD_NUM,' L ON L.USER_ID = C.USER_ID
	WHERE L.BONUS_LB > 0');
	PREPARE stmt1 FROM STR_SQL;
	##执行SQL语句
	EXECUTE stmt1;
	## 释放掉预处理段
	DEALLOCATE PREPARE stmt1;


END