CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_LV_ELITE_HIGHEST`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
  -- 20241121

  DECLARE IV_ELITE_NA VARCHAR(32);

  SELECT
    ID
    INTO
    IV_ELITE_NA
  FROM
    AR_ELITE_LEVEL
    WHERE CALC_ID = 0;


  INSERT INTO AR_CALC_LV_ELITE_HIGH
      SELECT
        IV_PERIOD_NUM,
        IV_CALC_MONTH,
        U.ID AS USER_ID,
        IFNULL(U.HIGHEST_ELITE_LV,IV_ELITE_NA) AS ORI_HIGHEST_ELITE_LV,
        IFNULL(E.CALC_ID,0) AS ORI_HIGHEST_ELITE_CALC_ID,
        IFNULL(CE.LAST_ELITE_LV,IV_ELITE_NA) AS LAST_ELITE_LV,
        IFNULL(CE.LAST_ELITE_CALC_ID,0) AS LAST_ELITE_CALC_ID,
        CASE WHEN E.CALC_ID < IFNULL(CE.LAST_ELITE_CALC_ID,0)
          THEN IFNULL(CE.LAST_ELITE_LV,IV_ELITE_NA) ELSE IFNULL(U.HIGHEST_ELITE_LV,IV_ELITE_NA) END AS HIGHEST_ELITE_LV,
        CASE WHEN E.CALC_ID < IFNULL(CE.LAST_ELITE_CALC_ID,0)
          THEN IFNULL(CE.LAST_ELITE_CALC_ID,0) ELSE IFNULL(E.CALC_ID,0) END AS HIGHEST_ELITE_CALC_ID
      FROM
      AR_USER U
      LEFT JOIN AR_ELITE_LEVEL E ON E.ID = U.HIGHEST_ELITE_LV
      LEFT JOIN AR_CALC_LV_ELITE CE ON CE.USER_ID = U.ID;
END