CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_CRB`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
	DECLARE VV_MAX_LAYER,
				  VV_MIN_LAYER,
					VV_LAYER,
					VV_COUNT
	  INT;
	DECLARE VV_TOTAL_PV DECIMAL(16,6);
	DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字

-- 	SELECT MAX(T.TOP_DEEP)+5,MIN(T.TOP_DEEP)
-- 	  INTO VV_MAX_LAYER,VV_MIN_LAYER
-- 	  FROM AR_CALC_LV_ELITE T
-- 	 INNER JOIN (SELECT DISTINCT USER_ID FROM AR_MEMBER_CRB) T1 ON T.USER_ID = T1.USER_ID
-- 	 INNER JOIN AR_CALC_LV_ELITE_MID2 T2 ON T.USER_ID = T2.USER_ID AND T2.ELITE_CALC_ID = 10;
-- 	SET VV_LAYER = VV_MAX_LAYER;
-- 	WHILE VV_LAYER >= VV_MIN_LAYER DO
-- 	  INSERT INTO AR_CALC_BE_CRB_MID1
-- 	  SELECT T.PERIOD_NUM,
-- 		       T.CALC_MONTH,
-- 		       T.USER_ID,
-- 					 T.PARENT_UID,
-- 		       T.USER_ID AS SOURCE_USER_ID,
-- 					 T.GPV_REAL,
-- 					 1 AS LAYER,
-- 					 T.TOP_DEEP,
-- 					 0 IS_UNREAL
-- 		  FROM AR_CALC_LV_ELITE T
-- 		 WHERE T.TOP_DEEP = VV_LAYER;
-- 	  COMMIT;
-- 		SET VV_COUNT = 2;
-- 		WHILE VV_COUNT <=6 DO
-- 	    INSERT INTO AR_CALC_BE_CRB_MID1
-- 	    SELECT T.PERIOD_NUM,
-- 		         T.CALC_MONTH,
-- 					   T.PARENT_UID AS USER_ID,
-- 					   T1.PARENT_UID AS PARENT_UID,
-- 		         T.SOURCE_USER_ID AS SOURCE_USER_ID,
-- 					   T.GPV_REAL,
-- 					   VV_COUNT AS LAYER,
-- 					   T.TOP_DEEP,
-- 					   0 IS_UNREAL
-- 		    FROM AR_CALC_BE_CRB_MID1 T
-- 			 INNER JOIN AR_CALC_LV_ELITE T1 ON T.PARENT_UID = T1.USER_ID
-- 		   WHERE T.TOP_DEEP = VV_LAYER
-- 			   AND T.LAYER = VV_COUNT - 1
-- 				 AND T.PARENT_UID > 0;
-- 		  COMMIT;
-- 			INSERT INTO AR_CALC_BE_CRB_MID1
-- 			SELECT T.PERIOD_NUM,
-- 						 T.CALC_MONTH,
-- 						 T.USER_ID AS USER_ID,
-- 						 T.PARENT_UID AS PARENT_UID,
-- 						 T.USER_ID AS SOURCE_USER_ID,
-- 						 T1.GPV_UNREAL GPV_REAL,
-- 						 VV_COUNT AS LAYER,
-- 						 T.TOP_DEEP,
-- 						 1 IS_UNREAL
-- 				FROM AR_CALC_BE_CRB_MID1 T
-- 			 INNER JOIN AR_CALC_LV_ELITE T1 ON T.USER_ID = T1.USER_ID
-- 			 WHERE T.TOP_DEEP = VV_LAYER
-- 				 AND T.LAYER = VV_COUNT - 1
-- 				 AND T.IS_UNREAL = 0
-- 				 AND T1.GPV_UNREAL > 0;
-- 			COMMIT;
-- 			SET VV_COUNT = VV_COUNT + 1;
--     END WHILE;
--
-- 		SET VV_LAYER = VV_LAYER - 1;
--   END WHILE;
  INSERT INTO AR_CALC_BE_CRB_MID1
  WITH RECURSIVE T_REC AS (
		SELECT M.PERIOD_NUM,
					M.CALC_MONTH,
					M.USER_ID,
					M.PARENT_UID,
					1 AS LAYER,
					M.GPV GPV_REAL,
					M.USER_ID BONUS_ID,
					M.PARENT_UID BONUS_PARENT_ID,
					1 AS LAYER_UNREAL
				FROM
					AR_CALC_LV_ELITE_MID2 M
				WHERE
					M.USER_ID IN (SELECT DISTINCT USER_ID FROM AR_MEMBER_CRB)
		UNION ALL
		SELECT T1.PERIOD_NUM,
					T1.CALC_MONTH,
					T1.USER_ID,
					T1.PARENT_UID,
					CASE WHEN T1.GPV_REAL > 0 THEN T2.LAYER_UNREAL + 1 ELSE 0 END AS LAYER,
					T1.GPV_REAL,
					T2.BONUS_ID,
					T2.BONUS_PARENT_ID,
					CASE WHEN T1.GPV_REAL > 0 THEN T2.LAYER_UNREAL + 1 ELSE T2.LAYER_UNREAL END AS LAYER_UNREAL
				FROM AR_CALC_LV_ELITE_MID2 T1
			 INNER JOIN T_REC T2 ON T1.PARENT_UID = T2.USER_ID)
		SELECT T.PERIOD_NUM,
					T.CALC_MONTH,
					T.BONUS_ID USER_ID,
					T.BONUS_PARENT_ID PARENT_UID,
					T.USER_ID SOURCE_USER_ID,
					T.GPV_REAL,
					T.LAYER,
					0 TOP_DEEP,
					0 IS_UNREAL
		 FROM T_REC T
		WHERE T.LAYER BETWEEN 1 AND 6;
  COMMIT;


	INSERT INTO AR_CALC_BE_CRB_MID2_1
	SELECT T.PERIOD_NUM,
		     T.CALC_MONTH,
				 T.USER_ID,
	       T.PARENT_UID,
				 T.SOURCE_USER_ID,
				 T.GPV_REAL,
				 T.LAYER,
				 T.TOP_DEEP,
				 T1.END_PERIOD_NUM,
				 T1.BONUS_CAPPING,
				 T.IS_UNREAL
	  FROM AR_CALC_BE_CRB_MID1 T
	 INNER JOIN AR_MEMBER_CRB T1 ON T.USER_ID = T1.USER_ID AND T1.TYPE = 'CAR';
	COMMIT;

	INSERT INTO AR_CALC_BE_CRB_MID2_2
	SELECT T.PERIOD_NUM,
		     T.CALC_MONTH,
				 T.USER_ID,
	       T.PARENT_UID,
				 T.SOURCE_USER_ID,
				 T.GPV_REAL,
				 T.LAYER,
				 T.TOP_DEEP,
				 T1.END_PERIOD_NUM,
				 T1.BONUS_CAPPING,
				 T.IS_UNREAL
	  FROM AR_CALC_BE_CRB_MID1 T
	 INNER JOIN AR_MEMBER_CRB T1 ON T.USER_ID = T1.USER_ID AND T1.TYPE = 'ROOM';
	COMMIT;

	INSERT INTO AR_CALC_BE_CRB_MID3_1
	SELECT LAYER,
				 SUM(GPV_REAL) TOTAL_GPV
	  FROM AR_CALC_BE_CRB_MID2_1
	 GROUP BY LAYER;
	COMMIT;
	INSERT INTO AR_CALC_BE_CRB_MID3_2
	SELECT LAYER,
				 SUM(GPV_REAL) TOTAL_GPV
	  FROM AR_CALC_BE_CRB_MID2_2
	 GROUP BY LAYER;
	COMMIT;

	-- # 1:Malaysia,3:Brunei,4:Singapore
	SELECT IFNULL(SUM(T.PV),0)/2 INTO VV_TOTAL_PV FROM AR_PERF_ORDER T
	 WHERE T.COUNTRY_ID IN ('1','3','4');

	INSERT INTO AR_CALC_BE_CRB_MID4_1
	SELECT SUBSTR(T.CONFIG_NAME,8,1) LAYER,
				 T.`VALUE`/100 LAYER_RATE,
				 VV_TOTAL_PV CB_PV,
				 TRUNCATE(VV_TOTAL_PV * T.`VALUE`/100,6) LAYER_BONUS,
				 IFNULL(T1.TOTAL_GPV,0) TOTAL_GPV,
				 CASE WHEN IFNULL(T1.TOTAL_GPV,0) = 0 THEN 0 ELSE TRUNCATE(TRUNCATE(VV_TOTAL_PV * T.`VALUE`/100,6) / IFNULL(T1.TOTAL_GPV,0),6) END CB_RATE
	  FROM AR_CONFIG T
	  LEFT JOIN AR_CALC_BE_CRB_MID3_1 T1 ON SUBSTR(T.CONFIG_NAME,8,1) = T1.LAYER
	 WHERE T.CONFIG_NAME LIKE 'carRate%';
  COMMIT;

	INSERT INTO AR_CALC_BE_CRB_MID4_2
	SELECT SUBSTR(T.CONFIG_NAME,9,1) LAYER,
				 T.`VALUE`/100 LAYER_RATE,
				 VV_TOTAL_PV RB_PV,
				 TRUNCATE(VV_TOTAL_PV * T.`VALUE`/100,6) LAYER_BONUS,
				 IFNULL(T1.TOTAL_GPV,0) TOTAL_GPV,
				 CASE WHEN IFNULL(T1.TOTAL_GPV,0) = 0 THEN 0 ELSE TRUNCATE(TRUNCATE(VV_TOTAL_PV * T.`VALUE`/100,6) / IFNULL(T1.TOTAL_GPV,0),6) END RB_RATE
	  FROM AR_CONFIG T
	  LEFT JOIN AR_CALC_BE_CRB_MID3_2 T1 ON SUBSTR(T.CONFIG_NAME,9,1) = T1.LAYER
	 WHERE T.CONFIG_NAME LIKE 'roomRate%';
  COMMIT;

	INSERT INTO AR_CALC_BE_CRB_DETAIL_C
	SELECT T.PERIOD_NUM,
		     T.CALC_MONTH,
				 T.USER_ID,
	       T.PARENT_UID,
				 T.SOURCE_USER_ID,
				 T.GPV_REAL,
				 T.LAYER,
				 T.TOP_DEEP,
				 T.END_PERIOD_NUM,
				 T.BONUS_CAPPING,
				 T1.LAYER_RATE,
				 T1.CB_PV,
				 T1.LAYER_BONUS,
				 T1.TOTAL_GPV,
				 T1.CB_RATE,
				 TRUNCATE(T.GPV_REAL * T1.CB_RATE,2) BONUS_CB,
				 T2.IS_ACTIVE,
				 T.IS_UNREAL
	  FROM AR_CALC_BE_CRB_MID2_1 T
	 INNER JOIN AR_CALC_BE_CRB_MID4_1 T1 ON T.LAYER = T1.LAYER
	 INNER JOIN AR_USER_PERF T2 ON T.USER_ID = T2.USER_ID;
  COMMIT;

	INSERT INTO AR_CALC_BE_CRB_DETAIL_R
	SELECT T.PERIOD_NUM,
		     T.CALC_MONTH,
				 T.USER_ID,
	       T.PARENT_UID,
				 T.SOURCE_USER_ID,
				 T.GPV_REAL,
				 T.LAYER,
				 T.TOP_DEEP,
				 T.END_PERIOD_NUM,
				 T.BONUS_CAPPING,
				 T1.LAYER_RATE,
				 T1.RB_PV,
				 T1.LAYER_BONUS,
				 T1.TOTAL_GPV,
				 T1.RB_RATE,
				 TRUNCATE(T.GPV_REAL * T1.RB_RATE,2) BONUS_RB,
				 T2.IS_ACTIVE,
				 T.IS_UNREAL
	  FROM AR_CALC_BE_CRB_MID2_2 T
	 INNER JOIN AR_CALC_BE_CRB_MID4_2 T1 ON T.LAYER = T1.LAYER
	 INNER JOIN AR_USER_PERF T2 ON T.USER_ID = T2.USER_ID;
  COMMIT;

	INSERT INTO AR_CALC_BE_CRB_C
	SELECT T.PERIOD_NUM,
		     T.CALC_MONTH,
				 T.USER_ID,
				 T.END_PERIOD_NUM,
				 T.BONUS_CAPPING,
				 T.IS_ACTIVE,
				 SUM(BONUS_CB) ORI_BONUS_CB,
				 CASE WHEN T.END_PERIOD_NUM < T.PERIOD_NUM THEN 0
				      ELSE CASE WHEN SUM(BONUS_CB) <= T.BONUS_CAPPING THEN SUM(BONUS_CB)
							          ELSE T.BONUS_CAPPING END
						   END BONUS_CB,
				 IFNULL(SUM(CASE WHEN T.LAYER = 1 THEN T.GPV_REAL END),0) LAYER_1,
				 IFNULL(SUM(CASE WHEN T.LAYER = 2 THEN T.GPV_REAL END),0) LAYER_2,
				 IFNULL(SUM(CASE WHEN T.LAYER = 3 THEN T.GPV_REAL END),0) LAYER_3,
				 IFNULL(SUM(CASE WHEN T.LAYER = 4 THEN T.GPV_REAL END),0) LAYER_4,
				 IFNULL(SUM(CASE WHEN T.LAYER = 5 THEN T.GPV_REAL END),0) LAYER_5,
				 IFNULL(SUM(CASE WHEN T.LAYER = 6 THEN T.GPV_REAL END),0) LAYER_6
	  FROM AR_CALC_BE_CRB_DETAIL_C T
	 GROUP BY T.PERIOD_NUM,T.CALC_MONTH,T.USER_ID,T.END_PERIOD_NUM,T.BONUS_CAPPING,T.IS_ACTIVE;
	COMMIT;

	INSERT INTO AR_CALC_BE_CRB_R
	SELECT T.PERIOD_NUM,
		     T.CALC_MONTH,
				 T.USER_ID,
				 T.END_PERIOD_NUM,
				 T.BONUS_CAPPING,
				 T.IS_ACTIVE,
				 SUM(BONUS_RB) ORI_BONUS_RB,
				 CASE WHEN T.END_PERIOD_NUM < T.PERIOD_NUM THEN 0
				      ELSE CASE WHEN SUM(BONUS_RB) <= T.BONUS_CAPPING THEN SUM(BONUS_RB)
							          ELSE T.BONUS_CAPPING END
							 END BONUS_RB,
				 IFNULL(SUM(CASE WHEN T.LAYER = 1 THEN T.GPV_REAL END),0) LAYER_1,
				 IFNULL(SUM(CASE WHEN T.LAYER = 2 THEN T.GPV_REAL END),0) LAYER_2,
				 IFNULL(SUM(CASE WHEN T.LAYER = 3 THEN T.GPV_REAL END),0) LAYER_3,
				 IFNULL(SUM(CASE WHEN T.LAYER = 4 THEN T.GPV_REAL END),0) LAYER_4,
				 IFNULL(SUM(CASE WHEN T.LAYER = 5 THEN T.GPV_REAL END),0) LAYER_5,
				 IFNULL(SUM(CASE WHEN T.LAYER = 6 THEN T.GPV_REAL END),0) LAYER_6
	  FROM AR_CALC_BE_CRB_DETAIL_R T
	 GROUP BY T.PERIOD_NUM,T.CALC_MONTH,T.USER_ID,T.END_PERIOD_NUM,T.BONUS_CAPPING,T.IS_ACTIVE;
	COMMIT;

	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	INSERT INTO AR_CALC_BONUS_CRB
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
	       T.PERIOD_NUM,
		     T.CALC_MONTH,
				 T.USER_ID,
				 CASE WHEN T1.IS_ACTIVE IS NOT NULL THEN T1.IS_ACTIVE ELSE T2.IS_ACTIVE END IS_ACTIVE,
				 T1.BONUS_CAPPING BONUS_CAPPING_C,
				 T1.ORI_BONUS_CB,
				 T1.BONUS_CB,
				 T2.BONUS_CAPPING BONUS_CAPPING_R,
				 T2.ORI_BONUS_RB,
				 T2.BONUS_RB,
				 IFNULL(T1.BONUS_CB,0)+IFNULL(T2.BONUS_RB,0) BONUS_CRB
	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,(SELECT PERIOD_NUM,CALC_MONTH,USER_ID FROM AR_CALC_BE_CRB_C WHERE PERIOD_NUM <= END_PERIOD_NUM AND BONUS_CB > 0
		      UNION
					SELECT PERIOD_NUM,CALC_MONTH,USER_ID FROM AR_CALC_BE_CRB_R WHERE PERIOD_NUM <= END_PERIOD_NUM AND BONUS_RB > 0) T
		LEFT JOIN AR_CALC_BE_CRB_C T1 ON T.USER_ID = T1.USER_ID
		LEFT JOIN AR_CALC_BE_CRB_R T2 ON T.USER_ID = T2.USER_ID;
	COMMIT;

END