CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_SE_COUNTRY`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
  DECLARE VV_COUNT,VV_END,VV_START,VV_ID,VV_COUNT1,
					VV_COUNT2 INT;
	DECLARE VV_TOTAL_PV DECIMAL(16,3);
	DECLARE VV_SE_RATE DECIMAL(16,6);
	DECLARE VV_BONUS_SE DECIMAL(16,2);

	DECLARE VV_TIME_STR,VV_COUNTRY,VV_COUNTRY_ID,VV_REGION
	  VARCHAR(32);-- 当前时间的年月日时分秒数字
		-- 所有Super Elite平分总业绩的比例
	SELECT IFNULL(MIN(T.VALUE),0) / 100
	  INTO VV_SE_RATE
	  FROM AR_CONFIG T
   WHERE T.CONFIG_NAME = 'superEliteRate'
	   AND T.TYPE = 'bonus';

  INSERT INTO AR_CALC_LV_ELITE_1
  SELECT T.*,U.COUNTRY_ID,U.COUNTRY_ID FROM AR_CALC_LV_ELITE T LEFT JOIN AR_USER U ON U.ID = T.USER_ID;


  -- 多个国家合并成一个区域
	SELECT COUNT(1) INTO VV_COUNT2 FROM (SELECT COUNTRY_ID FROM AR_CALC_LV_ELITE_1 GROUP BY COUNTRY_ID) M;
	SET VV_COUNT1 = 0;
	WHILE VV_COUNT1 < VV_COUNT2 DO -- 按国家循环

		SELECT COUNTRY_ID INTO VV_COUNTRY_ID FROM AR_CALC_LV_ELITE_1 GROUP BY COUNTRY_ID LIMIT VV_COUNT1,1;

		SET VV_REGION = '';

		SELECT T.VALUE INTO VV_REGION FROM AR_CONFIG T WHERE T.CONFIG_NAME = CONCAT('Country',VV_COUNTRY_ID);

		IF VV_REGION IS NOT NULL AND VV_REGION != '' THEN
		   UPDATE AR_CALC_LV_ELITE_1 SET BONUS_COUNTRY = VV_REGION WHERE COUNTRY_ID = VV_COUNTRY_ID;
		END IF;

		SET VV_COUNT1 = VV_COUNT1 + 1;
  END WHILE;


	-- 循环的次数
	SELECT COUNT(*)
	  INTO VV_END
	  FROM (SELECT T.BONUS_COUNTRY
	  FROM AR_CALC_LV_ELITE_1 T
   WHERE T.LAST_ELITE_CALC_ID = 30
	 GROUP BY T.BONUS_COUNTRY)K;

	SET VV_ID = 0;
  -- 开始次数
	SET VV_START = 0;

  WHILE VV_START < VV_END DO

	SELECT K.BONUS_COUNTRY
	  INTO VV_COUNTRY
	  FROM (SELECT T.BONUS_COUNTRY
	        FROM AR_CALC_LV_ELITE_1 T
         WHERE T.LAST_ELITE_CALC_ID = 30
	       GROUP BY T.BONUS_COUNTRY) K
	 LIMIT VV_START,1;

-- 	Super Elite每个国家人数
	SELECT COUNT(1)
	  INTO VV_COUNT
	  FROM AR_CALC_LV_ELITE_1 T
   WHERE T.LAST_ELITE_CALC_ID = 30 AND T.BONUS_COUNTRY = VV_COUNTRY;


	 IF VV_COUNTRY IN (SELECT `VALUE` FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus') THEN

	SELECT IFNULL(SUM(T.PV),0)
	   INTO VV_TOTAL_PV
	   FROM AR_PERF_ORDER T
	  WHERE T.PERIOD_NUM = IV_PERIOD_NUM
		AND T.COUNTRY_ID IN (SELECT SUBSTRING(CONFIG_NAME,8) FROM AR_CONFIG WHERE CONFIG_NAME LIKE 'Country%' AND TYPE = 'bonus' AND `VALUE`=VV_COUNTRY); -- 这个国家总业绩

	ELSE

	SELECT IFNULL(SUM(T.PV),0)
	   INTO VV_TOTAL_PV
	   FROM AR_PERF_ORDER T
	  WHERE T.PERIOD_NUM = IV_PERIOD_NUM AND COUNTRY_ID = VV_COUNTRY; -- 这个国家总业绩

	END IF;

-- 	-- 当期各国家总业绩
-- 	SELECT IFNULL(SUM(T.PV),0) -- IFNULL(SUM(T.PV_PCS),0)
-- 	  INTO VV_TOTAL_PV
-- 	  FROM AR_PERF_ORDER T-- AR_PERF_MONTH T
-- -- 	  LEFT JOIN AR_USER U ON U.ID = T.USER_ID
--    WHERE T.PERIOD_NUM = IV_PERIOD_NUM AND T.COUNTRY_ID = VV_COUNTRY;

  -- 每个Super Elite得的SE奖
	SET VV_BONUS_SE = TRUNCATE(VV_TOTAL_PV * VV_SE_RATE/VV_COUNT,2);

	-- 计算Super Elite奖
		IF (VV_BONUS_SE > 0) THEN
			SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
			INSERT INTO AR_CALC_BONUS_SE
			SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
						 T.PERIOD_NUM,-- 周期
						 T.CALC_MONTH,-- 月份
						 T.USER_ID,
						 VV_BONUS_SE AS BONUS_SE,
						 T.COUNTRY_ID, -- 会员所属国家
						 IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE,
						 T.BONUS_COUNTRY -- 奖金计算国家
				FROM (SELECT @ROWNUM:= VV_ID  FROM DUAL) R,AR_CALC_LV_ELITE_1 T
				LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID
			 WHERE T.LAST_ELITE_CALC_ID = 30 AND T.BONUS_COUNTRY = VV_COUNTRY;
			COMMIT;
		END IF;
		SET VV_ID = VV_ID + VV_COUNT;
		SET VV_START = VV_START + 1;
	END WHILE;
END