CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_INACTIVE_DETAILS`(IN IV_PERIOD_NUM INT)
BEGIN
	INSERT INTO AR_INACTIVE_DETAILS
	SELECT
			 A.PERIOD_NUM,
       A.USER_ID,
			 U.USER_NAME,
			 U.REAL_NAME,
			 ML.LEVEL_NAME LAST_MEMBER_LV,
			 EL.LEVEL_NAME LAST_ELITE_LV,
			 HL1.LEVEL_NAME LAST_HONOR_LV,
			 HL2.LEVEL_NAME HIGEST_HONOR_LV,
			 PM.PV_PCS,
			 IFNULL(PB.BONUS_PB,0) BONUS_PB,
			 IFNULL(E.BONUS_E,0) BONUS_E,
			 IFNULL(PE.BONUS_PE,0) BONUS_PE,
			 IFNULL(SE.BONUS_SE,0) BONUS_SE,
			 IFNULL(LB.BONUS_LB,0) BONUS_LB,
			 IFNULL(LBD.LB10,0) LB10,
			 IFNULL(LBD.LB20,0) LB20,
			 IFNULL(LBD.LB30,0) LB30,
			 IFNULL(LBD.LB40,0) LB40,
			 IFNULL(LBD.LB50,0) LB50,
			 IFNULL(LBD.LB60,0) LB60,
			 IFNULL(LBD.LB70,0) LB70,
			 IFNULL(LBD.LB80,0) LB80,
			 IFNULL(LBD.LB90,0) LB90,
			 IFNULL(TB.BONUS_TB,0) BONUS_TB,
			 IFNULL(SFB.BONUS_SFB,0) BONUS_SFB,
			 IFNULL(GPB.BONUS_GPB,0) BONUS_GPB,
			 IFNULL(CRB.BONUS_CRB,0) BONUS_CRB,
			 U.COUNTRY_ID,
			 IFNULL(EAB.BONUS_EAB,0) BONUS_EAB
  FROM (
			 -- PE
			 SELECT USER_ID,PERIOD_NUM FROM AR_CALC_BONUS_PE WHERE IS_ACTIVE = 0
			 UNION
			 -- SE
			 SELECT USER_ID,PERIOD_NUM FROM AR_CALC_BONUS_SE WHERE IS_ACTIVE = 0
			 UNION
			 -- LB
			 SELECT T.USER_ID,T.PERIOD_NUM
			 	FROM AR_CALC_BE_LB_DETAIL T
			  INNER JOIN AR_USER_PERF T1 ON T.USER_ID = T1.USER_ID
			  WHERE T1.IS_ACTIVE = 0
			 		AND T.BONUS_HONOR_CALC_ID >= T.LAYER_CALC_ID
				GROUP BY T.USER_ID,T.PERIOD_NUM
			 UNION
			 -- GPB
			 SELECT USER_ID,PERIOD_NUM FROM AR_CALC_BONUS_GPB WHERE IS_ACTIVE = 0
			 UNION
			 -- CRB
			 SELECT USER_ID,PERIOD_NUM FROM AR_CALC_BONUS_CRB WHERE IS_ACTIVE = 0
			 UNION
			 -- EAB
			 SELECT USER_ID,PERIOD_NUM FROM AR_CALC_BONUS_EAB WHERE IS_ACTIVE = 0
			 ) A
  LEFT JOIN AR_USER U ON A.USER_ID = U.ID
	LEFT JOIN AR_MEMBER_LEVEL ML ON U.MEMBER_LV = ML.ID
	LEFT JOIN AR_CALC_LV_ELITE CLE ON A.USER_ID = CLE.USER_ID
	LEFT JOIN AR_ELITE_LEVEL EL ON IFNULL(CLE.LAST_ELITE_CALC_ID,0) = EL.CALC_ID
	LEFT JOIN AR_CALC_LV_HONOR CLH ON A.USER_ID = CLH.USER_ID
	LEFT JOIN AR_HONOR_LEVEL HL1 ON IFNULL(CLH.LAST_HONOR_CALC_ID,0) = HL1.CALC_ID
	LEFT JOIN AR_CALC_LV_HONOR_HIGH CLHH ON A.USER_ID = CLHH.USER_ID
	LEFT JOIN AR_HONOR_LEVEL HL2 ON IFNULL(CLHH.HIGHEST_HONOR_CALC_ID,0) = HL2.CALC_ID
	LEFT JOIN AR_PERF_MONTH PM ON A.USER_ID = PM.USER_ID
  LEFT JOIN AR_CALC_BONUS_PB PB ON A.USER_ID = PB.USER_ID
  LEFT JOIN AR_CALC_BONUS_E E ON A.USER_ID = E.USER_ID
  LEFT JOIN AR_CALC_BONUS_PE PE ON A.USER_ID = PE.USER_ID
  LEFT JOIN AR_CALC_BONUS_SE SE ON A.USER_ID = SE.USER_ID
  LEFT JOIN AR_CALC_BONUS_LB LB ON A.USER_ID = LB.USER_ID
  LEFT JOIN AR_CALC_BONUS_TB TB ON A.USER_ID = TB.USER_ID
  LEFT JOIN AR_CALC_BONUS_SFB SFB ON A.USER_ID = SFB.USER_ID
  LEFT JOIN AR_CALC_BONUS_GPB GPB ON A.USER_ID = GPB.USER_ID
  LEFT JOIN AR_CALC_BONUS_CRB CRB ON A.USER_ID = CRB.USER_ID
	LEFT JOIN (
	          SELECT USER_ID,
	          SUM(CASE WHEN LAYER_CALC_ID = 10 THEN BONUS_LB END) LB10,
						SUM(CASE WHEN LAYER_CALC_ID = 20 THEN BONUS_LB END) LB20,
						SUM(CASE WHEN LAYER_CALC_ID = 30 THEN BONUS_LB END) LB30,
						SUM(CASE WHEN LAYER_CALC_ID = 40 THEN BONUS_LB END) LB40,
						SUM(CASE WHEN LAYER_CALC_ID = 50 THEN BONUS_LB END) LB50,
						SUM(CASE WHEN LAYER_CALC_ID = 60 THEN BONUS_LB END) LB60,
						SUM(CASE WHEN LAYER_CALC_ID = 70 THEN BONUS_LB END) LB70,
						SUM(CASE WHEN LAYER_CALC_ID = 80 THEN BONUS_LB END) LB80,
						SUM(CASE WHEN LAYER_CALC_ID = 90 THEN BONUS_LB END) LB90
       FROM AR_CALC_BE_LB_DETAIL
			WHERE LAYER_CALC_ID <= BONUS_HONOR_CALC_ID
			GROUP BY USER_ID
			    ) LBD ON A.USER_ID = LBD.USER_ID
		 LEFT JOIN AR_CALC_BONUS_EAB EAB ON A.USER_ID = EAB.USER_ID
		WHERE A.PERIOD_NUM = IV_PERIOD_NUM;
	COMMIT;
END