CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_EFFECT`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
	DECLARE VV_EFFECT_PV DECIMAL(16,2);
	DECLARE VV_TIME_STR VARCHAR(32);

	SELECT IFNULL(MIN(T.VALUE),0) INTO VV_EFFECT_PV FROM AR_CONFIG T WHERE T.CONFIG_NAME = 'effectivePV' AND T.TYPE = 'bonus';

	INSERT INTO AR_CALC_EFFECT_MID1
	SELECT T.USER_ID,
	       CASE WHEN (T.EFFECT_PV + IFNULL(T1.PV_PCS,0)) >= VV_EFFECT_PV THEN IV_CALC_MONTH
					    ELSE T.EFFECT_MONTH END AS EFFECT_MONTH,
				 CASE WHEN (T.EFFECT_PV + IFNULL(T1.PV_PCS,0)) >= VV_EFFECT_PV THEN 0
					    ELSE T.EFFECT_PV + IFNULL(T1.PV_PCS,0) END AS EFFECT_PV,
				 CASE WHEN ADD_MONTHS(DATE(CONCAT(CASE WHEN T.EFFECT_PV + IFNULL(T1.PV_PCS,0) >= VV_EFFECT_PV THEN IV_CALC_MONTH
																							 ELSE T.EFFECT_MONTH END,'01')),11) >= DATE(CONCAT(IV_CALC_MONTH,'01')) THEN 1
							ELSE 0 END AS EFFECT_ACTIVE
	  FROM AR_USER_PERF T
	 INNER JOIN AR_PERF_MONTH T1 ON T.USER_ID = T1.USER_ID;
	COMMIT;

	UPDATE AR_USER_PERF T
	 INNER JOIN AR_CALC_EFFECT_MID1 T1 ON T.USER_ID = T1.USER_ID
	   SET T.EFFECT_MONTH = T1.EFFECT_MONTH,
	       T.EFFECT_PV = T1.EFFECT_PV,
	       T.EFFECT_ACTIVE = T1.EFFECT_ACTIVE;
	COMMIT;

	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');

	INSERT INTO AR_USER_PERF
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
				 T1.USER_ID,-- USER_ID,
				 0,-- PV_1L,
				 0,-- PV_2L,
				 0,-- CREATED_AT,
				 0,-- SURPLUS_1L,
				 0,-- SURPLUS_2L,
				 0,-- 1MON_HONOR,
				 0,-- 2MON_HONOR,
				 0,-- 3MON_HONOR,
				 0,-- 4MON_HONOR,
				 0,-- 5MON_HONOR,
				 0,-- 6MON_HONOR,
				 IV_CALC_MONTH AS EFFECT_MONTH,
				 CASE WHEN IFNULL(T2.PV_PCS,0) >= VV_EFFECT_PV THEN 0
							ELSE IFNULL(T2.PV_PCS,0) END AS EFFECT_PV,
				 1 AS EFFECT_ACTIVE,
				 UNIX_TIMESTAMP() AS CREATE_AT
	  FROM AR_USER T
		LEFT JOIN AR_USER_PERF T1 ON T.USER_ID = T1.USER_ID
		LEFT JOIN AR_PERF_MONTH T2 ON T.USER_ID = T2.USER_ID
	 WHERE T1.USER_ID IS NULL;
	COMMIT;
END