CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_SE`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
  DECLARE VV_COUNT
	    INT;
	DECLARE VV_TOTAL_PV DECIMAL(16,3);
	DECLARE VV_SE_RATE DECIMAL(16,6);
	DECLARE VV_BONUS_SE DECIMAL(16,2);

	DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字
	-- Super Elite人数
	SELECT COUNT(1)
	  INTO VV_COUNT
	  FROM AR_CALC_LV_ELITE T
   WHERE T.LAST_ELITE_CALC_ID = 30;
	-- 当期总业绩
	SELECT IFNULL(SUM(T.PV_PCS),0)
	  INTO VV_TOTAL_PV
	  FROM AR_PERF_MONTH T
   WHERE T.PERIOD_NUM = IV_PERIOD_NUM;
	-- 所有Super Elite平分总业绩的比例
	SELECT IFNULL(MIN(T.VALUE),0) / 100
	  INTO VV_SE_RATE
	  FROM AR_CONFIG T
   WHERE T.CONFIG_NAME = 'superEliteRate'
	   AND T.TYPE = 'bonus';
  -- 每个Super Elite得的SE奖
	SET VV_BONUS_SE =  CASE WHEN VV_COUNT = 0 THEN 0 ELSE TRUNCATE(VV_TOTAL_PV * VV_SE_RATE/VV_COUNT,2) END;

	-- 计算Super Elite奖
	IF (VV_BONUS_SE > 0) THEN
		SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
		INSERT INTO AR_CALC_BONUS_SE
		SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
					 T.PERIOD_NUM,-- 周期
					 T.CALC_MONTH,-- 月份
					 T.USER_ID,
					 VV_BONUS_SE AS BONUS_SE,
					 T1.COUNTRY_ID,
				   IFNULL(T3.IS_ACTIVE,0) AS IS_ACTIVE
			FROM (SELECT @ROWNUM := 0 FROM DUAL) R,AR_CALC_LV_ELITE T
			LEFT JOIN AR_USER T1 ON T1.ID = T.USER_ID
		  LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID
		 WHERE T.LAST_ELITE_CALC_ID = 30;
		COMMIT;
	END IF;
END