CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_E`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
  /*定义变量*/
  DECLARE VV_ARRIVE_PV1 INT DEFAULT(1000);-- 合格小组业绩阈值
	DECLARE VV_ARRIVE_PV2 INT DEFAULT(2000);-- 合格小组业绩符合虚拟直属的阈值
	DECLARE VV_CALC_MONTH INT DEFAULT(202304);-- 2023.11.1 – 2024.4.30;Elite附加奖励100eSAC，150USD

	DECLARE VV_COUNT,-- 查询计数
					VV_TOTAL,-- 循环累计值
					VV_MAX_LAYER-- 个人消费的用户在推荐网中层数最大（网体越往下越大）
	INT;-- 类型

	DECLARE VV_TIME_STR-- 当前时间的年月日时分秒数字
  VARCHAR(32);

	DECLARE VV_E_RATE -- Elite奖的比例
	DECIMAL(16,6);

	/*--------------------------------------------表说明--------------------------------------------*/
	/*
	  AR_CALC_BE_E_MID1：Elite奖金
	  AR_CALC_BE_E_NET：Elite奖计算网体及相关业绩
	*/
  /*Elite*/
	SELECT IFNULL(MIN(T.VALUE),0)/100 INTO VV_E_RATE FROM AR_CONFIG T WHERE T.CONFIG_NAME = 'eliteRate' AND T.TYPE = 'bonus';


-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'1',NOW());
-- 	COMMIT;
  INSERT INTO AR_CALC_BE_E_NET
	SELECT T.PERIOD_NUM,
         T.CALC_MONTH,
				 T.USER_ID,
				 T1.PARENT_UID,
				 T1.TOP_DEEP,
				 T.PV_PCS AS GPV,
				 0 AS GPV_REAL,
				 T.PV_PCS,
				 0 AS ELITE_CALC_ID,
				 T.COUNTRY_ID
		FROM AR_PERF_MONTH T
		LEFT JOIN AR_USER_RELATION_NEW T1 ON T1.USER_ID = T.USER_ID
	 WHERE T.PERIOD_NUM = IV_PERIOD_NUM
	   AND T.PV_PSS > 0;
	COMMIT;


-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'2',NOW());
-- 	COMMIT;
	SELECT IFNULL(MAX(T.TOP_DEEP),-1) INTO VV_MAX_LAYER FROM AR_CALC_BE_E_NET T;
	WHILE VV_MAX_LAYER >= 0 DO
	  UPDATE AR_CALC_BE_E_NET T-- Elite奖计算网体及相关业绩
	    LEFT JOIN (SELECT A.PARENT_UID AS USER_ID,
												SUM(A.GPV) AS GPV
									 FROM AR_CALC_BE_E_NET A
									WHERE A.TOP_DEEP = VV_MAX_LAYER + 1
									  AND A.GPV > 0 -- 小组业绩
										AND A.GPV_REAL = 0 -- 真实的小组业绩。如果没有合格，自身的小组业绩为0，并向上贡献
										AND A.ELITE_CALC_ID = 0
									GROUP BY A.PARENT_UID) T1 ON T1.USER_ID = T.USER_ID-- 向上贡献的小组业绩
	    LEFT JOIN (SELECT A.PARENT_UID AS USER_ID
				           FROM AR_CALC_BE_E_NET A
									WHERE A.TOP_DEEP = VV_MAX_LAYER + 1
										AND ELITE_CALC_ID = 10
				          GROUP BY PARENT_UID) T2 ON T2.USER_ID = T.USER_ID-- 是否是连带合格
	     SET T.GPV_REAL = (CASE WHEN T.GPV+IFNULL(T1.GPV,0) >= VV_ARRIVE_PV1 OR T2.USER_ID IS NOT NULL THEN T.GPV+IFNULL(T1.GPV,0) ELSE 0 END),
				   T.ELITE_CALC_ID = (CASE WHEN T.GPV+IFNULL(T1.GPV,0) >= VV_ARRIVE_PV1 OR T2.USER_ID IS NOT NULL THEN 10 ELSE 0 END),
					 T.GPV = T.GPV+IFNULL(T1.GPV,0)
		 WHERE T.TOP_DEEP = VV_MAX_LAYER;
    COMMIT;

		-- 计算业绩贡献过程
		INSERT INTO AR_CALC_BE_E_MID2
		-- 当前层存在个人业绩的用户默认贡献给自己
		SELECT A.USER_ID AS SOURCE_USER_ID,
		       U.USER_NAME AS SOURCE_USER_NAME,
					 U.REAL_NAME AS SOURCE_REAL_NAME,
					 A.USER_ID AS BONUS_USER_ID,
		       U.USER_NAME AS BONUS_USER_NAME,
					 U.REAL_NAME AS BONUS_REAL_NAME,
					 A.PV_PCS AS SOURCE_PV,
					 VV_MAX_LAYER AS BONUS_LAYER
			FROM AR_CALC_BE_E_NET A
		 INNER JOIN AR_USER U ON U.ID = A.USER_ID
		 WHERE A.TOP_DEEP = VV_MAX_LAYER
			 AND A.PV_PCS >0
		-- 当前层的下级存在需要贡献的记录全部向上推一层
		UNION ALL
		SELECT A.SOURCE_USER_ID,
		       A.SOURCE_USER_NAME,
					 A.SOURCE_REAL_NAME,
					 B.PARENT_UID AS BONUS_USER_ID,
		       U.USER_NAME AS BONUS_USER_NAME,
					 U.REAL_NAME AS BONUS_REAL_NAME,
					 A.SOURCE_PV,
					 VV_MAX_LAYER AS BONUS_LAYER
			FROM AR_CALC_BE_E_MID2 A
		 INNER JOIN (SELECT USER_ID,
												PARENT_UID
										 FROM AR_CALC_BE_E_NET
										WHERE TOP_DEEP = VV_MAX_LAYER + 1
											AND GPV > 0 -- 小组业绩
											AND GPV_REAL = 0 -- 真实的小组业绩。如果没有合格，自身的小组业绩为0，并向上贡献
											AND ELITE_CALC_ID = 0
										GROUP BY USER_ID, PARENT_UID) B ON A.BONUS_USER_ID = B.USER_ID
		  LEFT JOIN AR_USER U ON U.ID = B.PARENT_UID
		 WHERE A.BONUS_LAYER = VV_MAX_LAYER + 1;
	  COMMIT;

		SET VV_MAX_LAYER = VV_MAX_LAYER - 1;
	END WHILE;
	-- 计算奖金
-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'3',NOW());
-- 	COMMIT;
	INSERT INTO AR_CALC_BE_E_MID1
	SELECT T.PERIOD_NUM,-- 周期
	       T.CALC_MONTH,
				 T.USER_ID,
				 T.PARENT_UID,
				 T.TOP_DEEP,
				 T.GPV_REAL,-- 真实的小组业绩。如果没有合格，自身的小组业绩为0，并向上贡献
				 VV_E_RATE AS E_RATE,-- Elite奖金比例
				 TRUNCATE(T.GPV_REAL*VV_E_RATE,2) AS BONUS_E, -- Elite奖金
				 T.COUNTRY_ID
	  FROM AR_CALC_BE_E_NET T
	 WHERE T.GPV_REAL > 0
	   AND T.ELITE_CALC_ID = 10;
	COMMIT;


-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'4',NOW());
-- 	COMMIT;
	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	INSERT INTO AR_CALC_BONUS_E
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
	       T.PERIOD_NUM,-- 周期
	       T.CALC_MONTH,
				 T.USER_ID,
				 T.PARENT_UID,
				 T.TOP_DEEP,
				 T.GPV_REAL,-- 真实的小组业绩。如果没有合格，自身的小组业绩为0，并向上贡献
				 T.E_RATE,-- Elite奖金比例
				 T.BONUS_E, -- Elite奖金
				 T.COUNTRY_ID
	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,AR_CALC_BE_E_MID1 T
	 WHERE T.BONUS_E > 0;
	COMMIT;


	INSERT INTO AR_CALC_BONUS_E_SOURCE
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
	       IV_CALC_MONTH AS CALC_MONTH,-- 月份
				 R.BONUS_USER_ID,
				 R.BONUS_USER_NAME,
				 R.BONUS_REAL_NAME,
				 R.SOURCE_USER_ID,
				 R.SOURCE_USER_NAME,
				 R.SOURCE_REAL_NAME,
				 R.SOURCE_PV,
				 R.BONUS_LAYER
    FROM (SELECT *,
                ROW_NUMBER() OVER (PARTITION BY SOURCE_USER_ID ORDER BY BONUS_LAYER ) as rn
            FROM AR_CALC_BE_E_MID2
         ) R
   WHERE rn = 1;


END