CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_CHECK`(IN IV_PERIOD_NUM INT,INOUT IV_CHECK_STATUS INT,INOUT IV_RESULT VARCHAR(200))
CALC_CHECK: BEGIN
	DECLARE VV_COUNT,
	        VV_COUNT1,
					VV_COUNT2
				 INT;
--   TRUNCATE TABLE AA_LOG;
-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('START',NOW());COMMIT;
	SET IV_CHECK_STATUS = 1;
	SET IV_RESULT = 'SUCCESS';
	-- 1.是否存在断网
	-- 1.1安置网
-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('1.1安置网',NOW());COMMIT;
	WITH RECURSIVE T_REC AS
		            (SELECT M.USER_ID,
			                  M.PARENT_UID,
											  0 AS NODE_LEVEL
		               FROM AR_USER_RELATION_NEW M
								  WHERE M.USER_ID = '35'
                  UNION ALL
		             SELECT T1.USER_ID,
		                    T1.PARENT_UID,
										 	  T2.NODE_LEVEL + 1 -- 结点层级
		               FROM AR_USER_RELATION_NEW T1
		              INNER JOIN T_REC T2 ON T1.PARENT_UID = T2.USER_ID -- 从上向下
                )SELECT COUNT(USER_ID) INTO VV_COUNT1 FROM T_REC;

	SELECT COUNT(USER_ID) INTO VV_COUNT2 FROM AR_USER_RELATION_NEW;

	IF(VV_COUNT1 <> VV_COUNT2)THEN
	  SET IV_CHECK_STATUS = 0;
	  SET IV_RESULT = '推荐网出现断层';
		LEAVE CALC_CHECK;
	END IF;

	-- 1.2推荐网
-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('1.2推荐网',NOW());COMMIT;
  WITH RECURSIVE T_REC AS
		            (SELECT M.USER_ID,
			                  M.PARENT_UID,
											  0 AS NODE_LEVEL
		               FROM AR_USER_NETWORK_NEW M
								  WHERE M.PARENT_UID = '0'
                  UNION ALL
		             SELECT T1.USER_ID,
		                    T1.PARENT_UID,
										 	  T2.NODE_LEVEL + 1 -- 结点层级
		               FROM AR_USER_NETWORK_NEW T1
		              INNER JOIN T_REC T2 ON T1.PARENT_UID = T2.USER_ID -- 从上向下
                )SELECT COUNT(USER_ID) INTO VV_COUNT1 FROM T_REC;

	SELECT COUNT(USER_ID) INTO VV_COUNT2 FROM AR_USER_NETWORK_NEW;

	IF(VV_COUNT1 <> VV_COUNT2)THEN
	  SET IV_CHECK_STATUS = 0;
	  SET IV_RESULT = '安置网出现断层';
		LEAVE CALC_CHECK;
	END IF;

	-- 2.网体中的会员是否在会员表中都存在
	-- 2.1推荐网
-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('2.1推荐网',NOW());COMMIT;
	SELECT COUNT(T1.USER_ID)
	  INTO VV_COUNT
	  FROM AR_USER_RELATION_NEW T1
		LEFT JOIN AR_USER U ON T1.USER_ID = U.ID
	 WHERE U.ID IS NULL;

	IF(VV_COUNT > 0)THEN
	  SET IV_CHECK_STATUS = 0;
	  SET IV_RESULT = '推荐网中的会员在用户表中不存在';
		LEAVE CALC_CHECK;
	END IF;

	-- 2.2安置网
-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('2.2安置网',NOW());COMMIT;
	SELECT COUNT(T1.USER_ID)
	  INTO VV_COUNT
	  FROM AR_USER_NETWORK_NEW T1
		LEFT JOIN AR_USER U ON T1.USER_ID = U.ID
	 WHERE U.ID IS NULL;

	IF(VV_COUNT > 0)THEN
	  SET IV_CHECK_STATUS = 0;
	  SET IV_RESULT = '安置网中的会员在用户表中不存在';
		LEAVE CALC_CHECK;
	END IF;

	-- 3.订单表（计奖订单和店铺订单）中的会员是否在网体中都存在
	-- 3.1推荐网计奖订单
-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('3.1推荐网计奖订单',NOW());COMMIT;
	SELECT COUNT(O.USER_ID)
	  INTO VV_COUNT
	  FROM AR_PERF_ORDER O
		LEFT JOIN AR_USER_RELATION_NEW U ON O.USER_ID = U.USER_ID
	 WHERE U.USER_ID IS NULL;

	IF(VV_COUNT > 0)THEN
	  SET IV_CHECK_STATUS = 0;
	  SET IV_RESULT = '订单表的会员在推荐网体中不存在';
		LEAVE CALC_CHECK;
	END IF;

	-- 3.2安置网计奖订单
-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('3.2安置网计奖订单',NOW());COMMIT;
	SELECT COUNT(O.USER_ID)
	  INTO VV_COUNT
	  FROM AR_PERF_ORDER O
		LEFT JOIN AR_USER_NETWORK_NEW U ON O.USER_ID = U.USER_ID
	 WHERE U.USER_ID IS NULL;

	IF(VV_COUNT > 0)THEN
	  SET IV_CHECK_STATUS = 0;
	  SET IV_RESULT = '订单表的会员在安置网体中不存在';
		LEAVE CALC_CHECK;
	END IF;

	-- 3.3用户表店铺订单
-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('3.3用户表店铺订单',NOW());COMMIT;
	SELECT COUNT(O.USER_ID)
	  INTO VV_COUNT
	  FROM AR_PERF_ORDER_STOCKIST O
		LEFT JOIN AR_USER U ON O.USER_ID = U.ID
	 WHERE U.ID IS NULL;

	IF(VV_COUNT > 0)THEN
	  SET IV_CHECK_STATUS = 0;
	  SET IV_RESULT = '店铺订单的会员在用户表中不存在';
		LEAVE CALC_CHECK;
	END IF;

-- 	INSERT INTO AA_LOG (TEXT,CREATED) VALUES ('END',NOW());COMMIT;

END