CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_EAB_copy1`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
/*定义变量*/
DECLARE VV_COUNT,VV_END,VV_START,VV_ID,VV_COUNT1,
VV_COUNT2 INT;
DECLARE VV_ARRIVE_PV INT DEFAULT(1000); -- 合格PGS阈值
DECLARE VV_EAB_RATE DECIMAL(16,6); -- EAB奖的比例
DECLARE VV_COUNTRY,VV_COUNTRY_ID,VV_REGION,VV_TIME_STR -- 当前时间的年月日时分秒数字
VARCHAR(32);

	SELECT
		IFNULL( MIN( T.VALUE ), 0 )/ 100 INTO VV_EAB_RATE
	FROM
		AR_CONFIG T
	WHERE
		T.CONFIG_NAME = 'eabRate'
		AND T.TYPE = 'bonus';
-- COMMIT;

	INSERT INTO AR_CALC_BE_EAB_MID1 SELECT
	T.PERIOD_NUM,-- 周期
	T.CALC_MONTH,
	T.USER_ID,
	T.GPV,
	0 AS BONUS_EAB,
	T.COUNTRY_ID,
	T.COUNTRY_ID AS COUNTRY_ID_1
	FROM
		AR_CALC_BE_E_NET T
	WHERE
		T.GPV >= 1000;
	COMMIT;

	INSERT INTO AR_CALC_BE_EAB_MID2 SELECT
	M.COUNTRY_ID,
	M.COUNTRY_ID AS COUNTRY_ID_1,
	IFNULL( N.PV, 0 ),
	Q.NUMS
	FROM
		AR_CALC_BE_EAB_MID1 M
		LEFT JOIN (
		SELECT
			IFNULL( SUM( T.PV ), 0 ) AS PV,
			T.COUNTRY_ID
		FROM
			AR_PERF_ORDER T
		WHERE
			T.PERIOD_NUM = IV_PERIOD_NUM
		GROUP BY
			T.COUNTRY_ID
		) N ON M.COUNTRY_ID = N.COUNTRY_ID
		LEFT JOIN ( SELECT COUNT(*) AS NUMS, COUNTRY_ID FROM AR_CALC_BE_EAB_MID1 GROUP BY COUNTRY_ID ) Q ON Q.COUNTRY_ID = M.COUNTRY_ID
	GROUP BY
		M.COUNTRY_ID;

-- 多个国家合并成一个区域
SELECT COUNT(1) INTO VV_COUNT2 FROM (SELECT COUNTRY_ID FROM AR_CALC_BE_EAB_MID1 GROUP BY COUNTRY_ID) M;

SET VV_COUNT1 = 0;

WHILE VV_COUNT1 < VV_COUNT2 DO -- 按国家循环

SELECT COUNTRY_ID INTO VV_COUNTRY_ID FROM AR_CALC_BE_EAB_MID1 GROUP BY COUNTRY_ID LIMIT VV_COUNT1,1;

SET VV_REGION = '';

SELECT T.VALUE INTO VV_REGION FROM AR_CONFIG T WHERE T.CONFIG_NAME = CONCAT('Country',VV_COUNTRY_ID);

IF VV_REGION IS NOT NULL AND VV_REGION != '' THEN
UPDATE AR_CALC_BE_EAB_MID1 SET COUNTRY_ID_1 = VV_REGION WHERE COUNTRY_ID_1 = VV_COUNTRY_ID;
UPDATE AR_CALC_BE_EAB_MID2 SET COUNTRY_ID_1 = VV_REGION WHERE COUNTRY_ID_1 = VV_COUNTRY_ID;
END IF;

SET VV_COUNT1 = VV_COUNT1 + 1;

END WHILE;

INSERT INTO AR_CALC_BE_EAB_MID3
SELECT
COUNTRY_ID_1 AS COUNTRY_ID,
SUM(IFNULL(PV,0)) AS PV,
SUM(NUMS) AS NUMS,
SUM(IFNULL(PV,0)) * VV_EAB_RATE AS BONUS_TOTAL,
SUM(IFNULL(PV,0)) * VV_EAB_RATE / SUM(NUMS) AS BONUS_EAB
FROM AR_CALC_BE_EAB_MID2 GROUP BY COUNTRY_ID_1;

UPDATE AR_CALC_BE_EAB_MID1 M INNER JOIN AR_CALC_BE_EAB_MID3 N ON M.COUNTRY_ID_1 = N.COUNTRY_ID
SET M.BONUS_EAB = N.BONUS_EAB;

SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');

	INSERT INTO AR_CALC_BONUS_EAB SELECT
	CONCAT(
		VV_TIME_STR,
	LPAD( @ROWNUM := @ROWNUM + 1, 8, '0' )) AS ID,-- 年月日时分秒14+排序8
	T.PERIOD_NUM,-- 周期
	T.CALC_MONTH,
	T.USER_ID,
	T.GPV,
	T.BONUS_EAB,
	T.COUNTRY_ID,
	IFNULL( T3.IS_ACTIVE, 0 ) AS IS_ACTIVE
	FROM
		( SELECT @ROWNUM := 0 FROM DUAL ) R,
		AR_CALC_BE_EAB_MID1 T
		LEFT JOIN AR_USER_PERF T3 ON T3.USER_ID = T.USER_ID
	WHERE
		T.BONUS_EAB > 0;
COMMIT;
END