CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_SFB_1`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
	DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字

	INSERT INTO AR_CALC_BE_SFB_MID1
	SELECT T.PERIOD_NUM,
				 T.CALC_MONTH,
				 T.USER_ID,
				 T.STOCKIST_PV,
				 IFNULL(T1.VALUE,0)/100 AS SFB_RATE,
				 TRUNCATE(T.STOCKIST_PV * IFNULL(T1.VALUE,0)/100,2) BONUS_SFB,
				 T.COUNTRY_ID
	  FROM AR_PERF_MONTH T
		LEFT JOIN AR_CONFIG T1 ON T1.CONFIG_NAME = CONCAT('stockistFeeRate',T.COUNTRY_ID)
												  AND T1.TYPE = 'bonus'
	 WHERE T.STOCKIST_PV > 0;
  COMMIT;

	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	INSERT INTO AR_CALC_BONUS_SFB
	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
	       T.PERIOD_NUM,
				 T.CALC_MONTH,
				 T.USER_ID,
				 T.STOCKIST_PV,
				 T.SFB_RATE,
				 T.BONUS_SFB,
				 T.COUNTRY_ID
	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,AR_CALC_BE_SFB_MID1 T
	 WHERE T.BONUS_SFB > 0;
	COMMIT;

END