CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_LV_HONOR_HIGH_V1`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN

DECLARE VV_COUNT INT;
	/*--------------------------------------------表说明--------------------------------------------*/
	/*
	  AR_CALC_LV_HONOR_HIGH_MID1：将列转行显示每个会员在每个月的最新奖衔
	  AR_CALC_LV_HONOR_HIGH_MID2：最近3个月连续获得的奖衔
	  AR_CALC_LV_HONOR_HIGH_MID3：最近6个月中4个月不连续获得的奖衔
	  AR_CALC_LV_HONOR_HIGH_MID4：会员的最高奖衔信息
	*/

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'1',NOW());
-- 	COMMIT;
	-- 将最后面5个月的最新奖衔向前推一个月
	UPDATE AR_USER_PERF T
	   SET T.6MON_HONOR = T.5MON_HONOR,
		     T.5MON_HONOR = T.4MON_HONOR,
		     T.4MON_HONOR = T.3MON_HONOR,
		     T.3MON_HONOR = T.2MON_HONOR,
		     T.2MON_HONOR = T.1MON_HONOR,
		     T.1MON_HONOR = 0;
  COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'2',NOW());
-- 	COMMIT;
	-- 更新第1个月的最新奖衔
	UPDATE AR_USER_PERF T
	 INNER JOIN AR_CALC_LV_HONOR T1 ON T1.USER_ID = T.USER_ID
	   SET T.1MON_HONOR = T1.LAST_HONOR_CALC_ID;
  COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'3',NOW());
-- 	COMMIT;
	-- 将列转行显示每个会员在每个月的最新奖衔
	INSERT INTO AR_CALC_LV_HONOR_HIGH_MID1
	SELECT T.USER_ID,
	       LEAST(T.1MON_HONOR,T.2MON_HONOR,T.3MON_HONOR) AS MON_HONOR3
	  FROM AR_USER_PERF T;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'4',NOW());
-- 	COMMIT;
	-- 最近3个月连续获得的奖衔
	INSERT INTO AR_CALC_LV_HONOR_HIGH_MID2
	SELECT T.USER_ID,
	       T.1MON_HONOR,
	       T.2MON_HONOR,
	       T.3MON_HONOR,
	       T.4MON_HONOR,
	       T.5MON_HONOR,
	       T.6MON_HONOR
	  FROM AR_USER_PERF T;
	COMMIT;
	SET VV_COUNT = 1;
	WHILE VV_COUNT <= 2 DO
	  UPDATE AR_CALC_LV_HONOR_HIGH_MID2 T
		 INNER JOIN AR_CALC_LV_HONOR_HIGH_MID2 T1 ON T1.USER_ID = T.USER_ID
		   SET T.1MON_HONOR = T1.2MON_HONOR,
			     T.2MON_HONOR = T1.1MON_HONOR
		 WHERE T.1MON_HONOR < T.2MON_HONOR;
    COMMIT;
	  UPDATE AR_CALC_LV_HONOR_HIGH_MID2 T
		 INNER JOIN AR_CALC_LV_HONOR_HIGH_MID2 T1 ON T1.USER_ID = T.USER_ID
		   SET T.2MON_HONOR = T1.3MON_HONOR,
			     T.3MON_HONOR = T1.2MON_HONOR
		 WHERE T.2MON_HONOR < T.3MON_HONOR;
    COMMIT;
	  UPDATE AR_CALC_LV_HONOR_HIGH_MID2 T
		 INNER JOIN AR_CALC_LV_HONOR_HIGH_MID2 T1 ON T1.USER_ID = T.USER_ID
		   SET T.3MON_HONOR = T1.4MON_HONOR,
			     T.4MON_HONOR = T1.3MON_HONOR
		 WHERE T.3MON_HONOR < T.4MON_HONOR;
    COMMIT;
	  UPDATE AR_CALC_LV_HONOR_HIGH_MID2 T
		 INNER JOIN AR_CALC_LV_HONOR_HIGH_MID2 T1 ON T1.USER_ID = T.USER_ID
		   SET T.4MON_HONOR = T1.5MON_HONOR,
			     T.5MON_HONOR = T1.4MON_HONOR
		 WHERE T.4MON_HONOR < T.5MON_HONOR;
    COMMIT;
		IF (VV_COUNT <= 1) THEN
	  UPDATE AR_CALC_LV_HONOR_HIGH_MID2 T
		 INNER JOIN AR_CALC_LV_HONOR_HIGH_MID2 T1 ON T1.USER_ID = T.USER_ID
		   SET T.5MON_HONOR = T1.6MON_HONOR,
			     T.6MON_HONOR = T1.5MON_HONOR
		 WHERE T.5MON_HONOR < T.6MON_HONOR;
    COMMIT;
		END IF;
		SET VV_COUNT = VV_COUNT + 1;
  END WHILE;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'5',NOW());
-- 	COMMIT;
	-- 最近6个月中4个月不连续获得的奖衔
	INSERT INTO AR_CALC_LV_HONOR_HIGH_MID3
	SELECT T.USER_ID,
	       LEAST(T.1MON_HONOR,T.2MON_HONOR,T.3MON_HONOR,T.4MON_HONOR) AS MON_HONOR6
	  FROM AR_CALC_LV_HONOR_HIGH_MID2 T;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'6',NOW());
-- 	COMMIT;
	-- 会员的最高奖衔信息
	INSERT INTO AR_CALC_LV_HONOR_HIGH_MID4
	SELECT T.ID AS USER_ID,
				 T.HIGHEST_HONOR_LV AS ORI_HIGHEST_HONOR_LV,
				 IFNULL(T1.CALC_ID,0) AS ORI_HIGHEST_HONOR_CALC_ID,
				 0 AS MON_HONOR3,
				 0 AS MON_HONOR6,
				 0 AS HIGHEST_HONOR_CALC_ID
	  FROM AR_USER T
		LEFT JOIN AR_HONOR_LEVEL T1 ON T1.ID = T.HIGHEST_HONOR_LV;
  COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'7',NOW());
-- 	COMMIT;
	UPDATE AR_CALC_LV_HONOR_HIGH_MID4 T
	 INNER JOIN AR_CALC_LV_HONOR_HIGH_MID1 T1 ON T1.USER_ID = T.USER_ID
	   SET T.MON_HONOR3 = T1.MON_HONOR3;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'8',NOW());
-- 	COMMIT;
	UPDATE AR_CALC_LV_HONOR_HIGH_MID4 T
	 INNER JOIN AR_CALC_LV_HONOR_HIGH_MID3 T1 ON T1.USER_ID = T.USER_ID
	   SET T.MON_HONOR6 = T1.MON_HONOR6;
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'9',NOW());
-- 	COMMIT;
	UPDATE AR_CALC_LV_HONOR_HIGH_MID4 T
	   SET T.HIGHEST_HONOR_CALC_ID = GREATEST(T.ORI_HIGHEST_HONOR_CALC_ID,T.MON_HONOR3,T.MON_HONOR6);
	COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'10',NOW());
-- 	COMMIT;
	-- 记录会员最高奖衔
	INSERT INTO AR_CALC_LV_HONOR_HIGH
	SELECT IV_PERIOD_NUM AS PERIOD_NUM,
				 IV_CALC_MONTH AS CALC_MONTH,
	       T.USER_ID,
				 T.ORI_HIGHEST_HONOR_LV,
				 T.ORI_HIGHEST_HONOR_CALC_ID,
				 T.MON_HONOR3,
				 T.MON_HONOR6,
				 T.HIGHEST_HONOR_CALC_ID,
				 T1.ID AS HIGHEST_HONOR_LV
	  FROM AR_CALC_LV_HONOR_HIGH_MID4 T
	 INNER JOIN AR_HONOR_LEVEL T1 ON T1.CALC_ID = T.HIGHEST_HONOR_CALC_ID;
	COMMIT;
END