CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
DECLARE VV_TIME_STR VARCHAR(32);-- 当前时间的年月日时分秒数字
/*--------------------------------------------表说明--------------------------------------------*/
/*
AR_CALC_BE_BE_MID1：能够得奖的所有用户
AR_CALC_BE_BE_MID2：会员得奖情况
*/
-- INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'1',NOW());
-- COMMIT;
-- 能够得奖的所有用户
INSERT INTO AR_CALC_BE_BE_MID1
SELECT T.USER_ID
FROM AR_CALC_BONUS_E T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_PE T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_SE T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_LB T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_TB T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_PB T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_SFB T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_GPB T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_CRB T
UNION
SELECT T.USER_ID
FROM AR_CALC_BONUS_EAB T;
COMMIT;
-- INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'2',NOW());
-- COMMIT;
-- 会员得奖情况
INSERT INTO AR_CALC_BE_BE_MID2
SELECT IV_PERIOD_NUM AS PERIOD_NUM,
IV_CALC_MONTH AS CALC_MONTH,
T.USER_ID,
T12.MEMBER_LV AS LAST_MEMBER_LV,
IFNULL(T7.LAST_ELITE_CALC_ID,0) AS LAST_ELITE_CALC_ID,
IFNULL(T11.LAST_HONOR_CALC_ID,0) AS LAST_HONOR_CALC_ID,
IFNULL(T8.HIGHEST_HONOR_CALC_ID,0) AS HIGHEST_HONOR_CALC_ID,
-- 总奖金
IFNULL(T1.BONUS_E,0) +
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T2.BONUS_PE,0) END +
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T3.BONUS_SE,0) END +
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T4.BONUS_LB,0) END +
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T5.BONUS_TB,0) END +
IFNULL(T10.BONUS_SFB,0) +
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T13.BONUS_GPB,0) END +
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T14.BONUS_CRB,0) END +
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T15.BONUS_EAB,0) END
AS TOTAL_BONUS,
-- 总积分
IFNULL(T6.BONUS_PB,0) AS TOTAL_POINTS,
IFNULL(T1.BONUS_E,0) AS BONUS_E,
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T2.BONUS_PE,0) END AS BONUS_PE,
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T3.BONUS_SE,0) END AS BONUS_SE,
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T4.BONUS_LB,0) END AS BONUS_LB,
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T5.BONUS_TB,0) END AS BONUS_TB,
IFNULL(T6.BONUS_PB,0) AS BONUS_PB,
IFNULL(T10.BONUS_SFB,0) AS BONUS_SFB,
IFNULL(T9.IS_ACTIVE,0) AS IS_ACTIVE,
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T13.BONUS_GPB,0) END AS BONUS_GPB,
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T14.BONUS_CRB,0) END AS BONUS_CRB,
CASE WHEN IFNULL(T9.IS_ACTIVE,0) = 0 THEN 0 ELSE IFNULL(T15.BONUS_EAB,0) END AS BONUS_EAB,
IFNULL(T10.BONUS_SFB_UNITY,0) AS BONUS_SFB_UNITY,
IFNULL(T10.BONUS_SFB_APP,0) AS BONUS_SFB_APP,
IFNULL(T10.BONUS_SFB_OTC,0) AS BONUS_SFB_OTC
FROM AR_CALC_BE_BE_MID1 T
LEFT JOIN AR_CALC_BONUS_E T1 ON T.USER_ID = T1.USER_ID
LEFT JOIN AR_CALC_BONUS_PE T2 ON T.USER_ID = T2.USER_ID
LEFT JOIN AR_CALC_BONUS_SE T3 ON T.USER_ID = T3.USER_ID
LEFT JOIN AR_CALC_BONUS_LB T4 ON T.USER_ID = T4.USER_ID
LEFT JOIN AR_CALC_BONUS_TB T5 ON T.USER_ID = T5.USER_ID
LEFT JOIN AR_CALC_BONUS_PB T6 ON T.USER_ID = T6.USER_ID
LEFT JOIN AR_CALC_LV_ELITE T7 ON T.USER_ID = T7.USER_ID
LEFT JOIN AR_CALC_LV_HONOR_HIGH T8 ON T.USER_ID = T8.USER_ID
LEFT JOIN AR_USER_PERF T9 ON T.USER_ID = T9.USER_ID
LEFT JOIN AR_CALC_BONUS_SFB T10 ON T.USER_ID = T10.USER_ID
LEFT JOIN AR_CALC_LV_HONOR T11 ON T.USER_ID = T11.USER_ID
LEFT JOIN AR_USER T12 ON T.USER_ID = T12.ID
LEFT JOIN AR_CALC_BONUS_GPB T13 ON T.USER_ID = T13.USER_ID
LEFT JOIN AR_CALC_BONUS_CRB T14 ON T.USER_ID = T14.USER_ID
LEFT JOIN AR_CALC_BONUS_EAB T15 ON T.USER_ID = T15.USER_ID;
COMMIT;
-- INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'3',NOW());
-- COMMIT;
SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
INSERT INTO AR_CALC_BONUS
SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
IV_PERIOD_NUM AS PERIOD_NUM,
IV_CALC_MONTH AS CALC_MONTH,
T.USER_ID,
T.LAST_MEMBER_LV,
IFNULL(T1.CALC_ID,-1) AS LAST_MEMBER_CALC_ID,
IFNULL(T2.ID,'-1') AS LAST_ELITE_LV,
T.LAST_ELITE_CALC_ID,
IFNULL(T3.ID,'-1') AS LAST_HONOR_LV,
T.LAST_HONOR_CALC_ID,
IFNULL(T4.ID,'-1') AS HIGHEST_HONOR_LV,
T.HIGHEST_HONOR_CALC_ID,
-- 总奖金
T.TOTAL_BONUS,
-- 总积分
T.TOTAL_POINTS,
T.BONUS_E,
T.BONUS_PE,
T.BONUS_SE,
T.BONUS_LB,
T.BONUS_TB,
T.BONUS_PB,
T.BONUS_SFB,
T.IS_ACTIVE,
IFNULL(T5.COUNTRY_ID,'-1') AS COUNTRY_ID,
T.BONUS_GPB,
T.BONUS_CRB,
T.BONUS_EAB,
T.BONUS_SFB_UNITY,
T.BONUS_SFB_APP,
T.BONUS_SFB_OTC
FROM AR_CALC_BE_BE_MID2 T
LEFT JOIN AR_MEMBER_LEVEL T1 ON T.LAST_MEMBER_LV = T1.ID
LEFT JOIN AR_ELITE_LEVEL T2 ON T.LAST_ELITE_CALC_ID = T2.CALC_ID
LEFT JOIN AR_HONOR_LEVEL T3 ON T.LAST_HONOR_CALC_ID = T3.CALC_ID
LEFT JOIN AR_HONOR_LEVEL T4 ON T.HIGHEST_HONOR_CALC_ID = T4.CALC_ID
LEFT JOIN AR_USER T5 ON T5.ID = T.USER_ID
WHERE T.TOTAL_BONUS > 0
OR T.TOTAL_POINTS > 0;
COMMIT;
END