CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_BE_TB`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
  DECLARE VV_TOTAL_PV,
	        VV_TOTAL_BASE,
					VV_TOTAL_TB,
					VV_TB_RATE,
					VV_TB_BISECT_RATE
	DECIMAL(16,6);
	DECLARE VV_TIME_STR,-- 当前时间的年月日时分秒数字
	        VV_USER_ID,
					VV_PARENT_UID
	  VARCHAR(32);

	DECLARE VV_COUNT,
	        VV_TOP_DEEP
	  INT;
	/*--------------------------------------------表说明--------------------------------------------*/
	/*
	  AR_CALC_BE_TB_MID1：会员的级别，对碰比例，封顶等信息
	  AR_CALC_BE_TB_MID2：对碰计奖基数
		AR_CALC_BE_TB_MID3：会员左右市场的会员数和总业绩信息
	*/
-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'1',NOW());
-- 	COMMIT;
	-- 会员的级别，对碰比例，封顶等信息
	INSERT INTO AR_CALC_BE_TB_MID1
	SELECT T.PERIOD_NUM,
	       T.CALC_MONTH,
	       T.USER_ID,
				 T.TOTAL_1L,-- 1市场总业绩
				 T.TOTAL_2L,-- 2市场总业绩
				 CASE WHEN T.TOTAL_1L - T.TOTAL_2L >= 0 THEN T.TOTAL_1L - T.TOTAL_2L ELSE 0 END AS SURPLUS_1L,-- 1市场结余业绩
				 CASE WHEN T.TOTAL_2L - T.TOTAL_1L > 0 THEN T.TOTAL_2L - T.TOTAL_1L ELSE 0 END AS SURPLUS_2L,-- 2市场结余业绩
				 CASE WHEN T.TOTAL_1L - T.TOTAL_2L >= 0 THEN T.TOTAL_2L ELSE T.TOTAL_1L END AS TOUCH_PV,-- 对碰业绩
				 T1.MEMBER_LV AS LAST_MEMBER_LV,-- 用户Member级别
				 T2.CALC_ID AS LAST_MEMBER_CALC_ID,-- 级别对应的序号
				 IFNULL(T3.VALUE,0)/100 AS TOUCH_RATE,-- 对碰比例
				 IFNULL(T4.VALUE,0) AS TOUCH_CAPPING, -- 对碰封顶
				 T.IS_ACTIVE -- 是否活跃
	  FROM AR_PERF_MONTH T
		LEFT JOIN AR_USER T1 ON T1.ID = T.USER_ID
		LEFT JOIN AR_MEMBER_LEVEL T2 ON T2.ID = T1.MEMBER_LV
		LEFT JOIN AR_CONFIG T3 ON T3.CONFIG_NAME = CONCAT('teamTouchRate',T2.CALC_ID) AND T3.TYPE = 'bonus'
		LEFT JOIN AR_CONFIG T4 ON T4.CONFIG_NAME = CONCAT('teamTouchCapping',T2.CALC_ID) AND T4.TYPE = 'bonus'
	 WHERE T.PERIOD_NUM = IV_PERIOD_NUM;
  COMMIT;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'2',NOW());
-- 	COMMIT;
  -- 对碰计奖基数
	INSERT INTO AR_CALC_BE_TB_MID2
	SELECT T.PERIOD_NUM,
	       T.CALC_MONTH,
	       T.USER_ID,
				 T.TOTAL_1L,-- 1市场总业绩
				 T.TOTAL_2L,-- 2市场总业绩
				 T.SURPLUS_1L,-- 1市场结余业绩
				 T.SURPLUS_2L,-- 2市场结余业绩
				 T.TOUCH_PV,-- 对碰业绩
				 T.LAST_MEMBER_LV,-- 用户Member级别
				 T.LAST_MEMBER_CALC_ID,-- 级别对应的序号
				 T.TOUCH_RATE,-- 对碰比例
				 T.TOUCH_CAPPING,-- 对碰封顶
				 T.TOUCH_PV * T.TOUCH_RATE AS ORI_TOUCH_BASE,-- 封顶前对碰基数
				 CASE WHEN T.TOUCH_CAPPING = 0 THEN T.TOUCH_PV * T.TOUCH_RATE
				      WHEN T.TOUCH_CAPPING <= T.TOUCH_PV * T.TOUCH_RATE THEN T.TOUCH_CAPPING
							ELSE T.TOUCH_PV * T.TOUCH_RATE END AS TOUCH_BASE, -- 封顶后对碰基数
				 T.IS_ACTIVE -- 是否活跃
	  FROM AR_CALC_BE_TB_MID1 T
	 WHERE T.TOUCH_PV > 0;
	COMMIT;
	--
	SELECT IFNULL(SUM(PV_PCS),0) INTO VV_TOTAL_PV FROM AR_PERF_MONTH T WHERE T.PERIOD_NUM = IV_PERIOD_NUM;
	--
	SELECT IFNULL(SUM(T.TOUCH_BASE),0) INTO VV_TOTAL_BASE FROM AR_CALC_BE_TB_MID2 T WHERE T.IS_ACTIVE = 1;

	SELECT IFNULL(MIN(T.VALUE),0)/100 INTO VV_TB_BISECT_RATE FROM AR_CONFIG T WHERE T.CONFIG_NAME = 'teamBisectRate' AND T.TYPE = 'bonus';

	-- 团队奖总奖金
	SET VV_TOTAL_TB = VV_TOTAL_PV * VV_TB_BISECT_RATE;
	-- 比例
	SET VV_TB_RATE = CASE WHEN VV_TOTAL_BASE = 0 THEN 0 ELSE TRUNCATE(VV_TOTAL_TB/VV_TOTAL_BASE,6) END;

-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'3',NOW());
-- 	COMMIT;
	SET VV_TIME_STR = DATE_FORMAT(NOW(),'%Y%m%d%H%i%s');
	-- 团队奖
	IF(VV_TB_RATE > 0) THEN
	  INSERT INTO AR_CALC_BONUS_TB
		SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
					 T.PERIOD_NUM,
					 T.CALC_MONTH,
					 T.USER_ID,
					 T.TOTAL_1L,-- 1市场总业绩
					 T.TOTAL_2L,-- 2市场总业绩
					 T.SURPLUS_1L,-- 1市场结余业绩
					 T.SURPLUS_2L,-- 2市场结余业绩
					 T.TOUCH_PV,-- 对碰业绩
					 T.LAST_MEMBER_LV,-- 用户Member级别
					 T.LAST_MEMBER_CALC_ID,-- 级别对应的序号
					 T.TOUCH_RATE,-- 对碰比例
					 T.TOUCH_CAPPING,-- 对碰封顶
					 T.ORI_TOUCH_BASE,-- 封顶前对碰基数
					 T.TOUCH_BASE,-- 封顶后对碰基数
					 VV_TB_RATE AS TB_RATE,-- 比例
					 TRUNCATE(T.TOUCH_BASE * VV_TB_RATE,2) AS BONUS_TB,-- 团队奖
					 IFNULL(T1.COUNTRY_ID,'-1') AS COUNTRY_ID,
					 T.IS_ACTIVE
			FROM (SELECT @ROWNUM := 0 FROM DUAL) R,AR_CALC_BE_TB_MID2 T
			LEFT JOIN AR_USER T1 ON T1.ID = T.USER_ID
		 WHERE T.TOUCH_BASE > 0
		   AND T.IS_ACTIVE = 1;
		COMMIT;
	END IF;


-- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'3',NOW());
-- 	COMMIT;

-- 	UPDATE AR_USER_PERF T
-- 	 INNER JOIN AR_CALC_BE_TB_MID1 T1 ON T.USER_ID = T1.USER_ID
-- 	   SET T.SURPLUS_1L = T1.SURPLUS_1L,
-- 		     T.SURPLUS_2L = T1.SURPLUS_2L,
-- 		     T.TOTAL_1L = T1.TOTAL_1L,
-- 		     T.TOTAL_2L = T1.TOTAL_2L;
-- 	COMMIT;
  UPDATE AR_USER_PERF T
	LEFT JOIN AR_CALC_BE_TB_MID1 T1 ON T.USER_ID = T1.USER_ID
	   SET T.SURPLUS_1L = IF(T1.USER_ID IS NULL,T.SURPLUS_1L,T1.SURPLUS_1L),
		     T.SURPLUS_2L = IF(T1.USER_ID IS NULL,T.SURPLUS_2L,T1.SURPLUS_2L),
		     T.TOTAL_1L = IF(T1.USER_ID IS NULL,T.SURPLUS_1L,T1.TOTAL_1L),
		     T.TOTAL_2L = IF(T1.USER_ID IS NULL,T.SURPLUS_2L,T1.TOTAL_2L);
	COMMIT;

-- -- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'4',NOW());
-- -- 	COMMIT;
-- 	INSERT INTO AR_CALC_BE_TB_MID3
-- 	SELECT IV_PERIOD_NUM AS PERIOD_NUM,-- 周期
-- 				 IV_CALC_MONTH AS CALC_MONTH,-- 月份
-- 				 T.USER_ID,
--          T.PARENT_UID,
-- 			   T.RELATIVE_LOCATION,
-- 				 T.TOP_DEEP,
-- 				 IFNULL(T1.SURPLUS_1L,0) AS SURPLUS_1L,
-- 				 IFNULL(T1.SURPLUS_2L,0) AS SURPLUS_2L,
-- 				 IFNULL(T1.TOTAL_1L,0) AS TOTAL_1L,
-- 				 IFNULL(T1.TOTAL_2L,0) AS TOTAL_2L,
-- 			   0 AS MEMBERS_1L,
-- 			   0 AS MEMBERS_2L
--     FROM AR_USER_NETWORK_NEW T
-- 		LEFT JOIN AR_CALC_BE_TB_MID1 T1 ON T1.USER_ID = T.USER_ID;
-- 	COMMIT;
--
-- -- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'5',NOW());
-- -- 	COMMIT;
--   SELECT IFNULL(MAX(T.TOP_DEEP),0) INTO VV_TOP_DEEP FROM AR_CALC_BE_TB_MID3 T;
-- 	WHILE VV_TOP_DEEP >= 0 DO
--     UPDATE AR_CALC_BE_TB_MID3 T
--       LEFT JOIN (SELECT A.PARENT_UID AS USER_ID,
-- 			                  IFNULL(SUM(CASE WHEN IFNULL(A.RELATIVE_LOCATION,0) = 1 THEN IFNULL(A.MEMBERS_1L,0)+IFNULL(A.MEMBERS_2L,0)+1 ELSE 0 END),0) AS MEMBERS_1L,
-- 			                  IFNULL(SUM(CASE WHEN IFNULL(A.RELATIVE_LOCATION,0) = 2 THEN IFNULL(A.MEMBERS_1L,0)+IFNULL(A.MEMBERS_2L,0)+1 ELSE 0 END),0) AS MEMBERS_2L
--                    FROM AR_CALC_BE_TB_MID3 A WHERE A.TOP_DEEP = VV_TOP_DEEP+1 AND A.RELATIVE_LOCATION IN (1,2)
--                   GROUP BY A.PARENT_UID) T1 ON T1.USER_ID = T.USER_ID
-- 	     SET T.MEMBERS_1L = IFNULL(T1.MEMBERS_1L,0),
-- 			     T.MEMBERS_2L = IFNULL(T1.MEMBERS_2L,0)
--      WHERE T.TOP_DEEP = VV_TOP_DEEP;
-- 	  COMMIT;
-- 		SET VV_TOP_DEEP = VV_TOP_DEEP - 1;
--   END WHILE;
--
--
-- -- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'6',NOW());
-- -- 	COMMIT;
-- 	-- 结余表变更
-- 	UPDATE AR_USER_PERF T
-- 	   SET T.PERIOD_NUM = IV_PERIOD_NUM,
-- 		     T.TOTAL_1L = 0,
-- 		     T.TOTAL_2L = 0;
-- 	COMMIT;
--
-- -- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'7',NOW());
-- -- 	COMMIT;
-- 	UPDATE AR_USER_PERF T
--    INNER JOIN AR_CALC_BE_TB_MID3 T1 ON T.USER_ID = T1.USER_ID
-- 	   SET T.SURPLUS_1L = T1.SURPLUS_1L,
-- 		     T.SURPLUS_2L = T1.SURPLUS_2L,
-- 		     T.TOTAL_1L = T1.TOTAL_1L,
-- 		     T.TOTAL_2L = T1.TOTAL_2L,
-- 		     T.MEMBERS_1L = T1.MEMBERS_1L,
-- 		     T.MEMBERS_2L = T1.MEMBERS_2L;
--   COMMIT;
--
-- -- 	INSERT INTO AR_CALC_BE_LOG(CALC_ID,TEXT,CREATE_TIME) VALUES (0,'8',NOW());
-- -- 	COMMIT;
-- -- 	INSERT INTO AR_USER_PERF
-- -- 	SELECT CONCAT(VV_TIME_STR,LPAD(@ROWNUM:=@ROWNUM+1,8,'0')) AS ID,-- 年月日时分秒14+排序8
-- -- 				 T.PERIOD_NUM,
-- -- 				 T.USER_ID,-- USER_ID,
-- -- 				 T.SURPLUS_1L,-- SURPLUS_1L,
-- -- 				 T.SURPLUS_2L,-- SURPLUS_2L,
-- -- 				 T.TOTAL_1L,-- SURPLUS_1L,
-- -- 				 T.TOTAL_2L,-- SURPLUS_2L,
-- -- 				 T.MEMBERS_1L,-- SURPLUS_1L,
-- -- 				 T.MEMBERS_2L,-- SURPLUS_2L,
-- -- 				 0,-- 1MON_HONOR,
-- -- 				 0,-- 2MON_HONOR,
-- -- 				 0,-- 3MON_HONOR,
-- -- 				 0,-- 4MON_HONOR,
-- -- 				 0,-- 5MON_HONOR,
-- -- 				 0,-- 6MON_HONOR,
-- -- 				 NULL AS EFFECT_MONTH,
-- -- 				 0 AS EFFECT_PV,
-- -- 				 0 AS EFFECT_ACTIVE,
-- -- 				 UNIX_TIMESTAMP() AS CREATE_AT
-- -- 	  FROM (SELECT @ROWNUM := 0 FROM DUAL) R,AR_CALC_BE_TB_MID3 T
-- -- 		LEFT JOIN AR_USER_PERF T1 ON T1.USER_ID = T.USER_ID
-- -- 	 WHERE T1.USER_ID IS NULL;
-- --   COMMIT;

END