CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `CALC_LV_HONOR_HIGH`(IN IV_PERIOD_NUM INT,IN IV_CALC_MONTH TINYINT)
BEGIN
 -- 20241121
  DECLARE IV_HONOR_1ST_CROWN VARCHAR(32);
  DECLARE IV_HONOR_2ST_CROWN VARCHAR(32);
  DECLARE IV_HONOR_3ST_CROWN VARCHAR(32);

	SELECT
    ID
    INTO
    IV_HONOR_1ST_CROWN
  FROM
    AR_HONOR_LEVEL
    WHERE CALC_ID = 70;

  SELECT
    ID
    INTO
    IV_HONOR_2ST_CROWN
  FROM
    AR_HONOR_LEVEL
    WHERE CALC_ID = 80;

  SELECT
    ID
    INTO
    IV_HONOR_3ST_CROWN
  FROM
    AR_HONOR_LEVEL
    WHERE CALC_ID = 90;

INSERT INTO AR_CALC_LV_HONOR_RECORD SELECT USER_ID,PERIOD_NUM,LAST_HONOR_LV,LAST_HONOR_CALC_ID  FROM AR_CALC_LV_HONOR_RECORD_PUSH WHERE PERIOD_NUM BETWEEN IV_PERIOD_NUM - 11 AND IV_PERIOD_NUM - 1 AND LAST_HONOR_CALC_ID >= 80;
COMMIT;
 -- 将最新一期数据INSERT进记录表，以补齐12个月的奖衔数据
  INSERT INTO AR_CALC_LV_HONOR_RECORD
    SELECT
      USER_ID,
      IV_PERIOD_NUM,
      LAST_HONOR_LV,
      LAST_HONOR_CALC_ID
    FROM
      AR_CALC_LV_HONOR;
 -- 初始化AR_CALC_LV_HONOR_HIGH表
  INSERT INTO AR_CALC_LV_HONOR_HIGH
     SELECT
       IV_PERIOD_NUM,
       IV_CALC_MONTH,
       U.ID AS USER_ID,
       U.HIGHEST_HONOR_LV AS ORI_HIGHEST_HONOR_LV,
       H.CALC_ID AS ORI_HIGHEST_HONOR_CALC_ID,
       0 AS MON_HONOR3,
       0 AS MON_HONOR6,
       H.CALC_ID AS HIGHEST_HONOR_CALC_ID,
       U.HIGHEST_HONOR_LV AS HIGHEST_HONOR_LV
     FROM
       AR_USER U
       LEFT JOIN AR_HONOR_LEVEL H ON H.ID = U.HIGHEST_HONOR_LV
       LEFT JOIN AR_CALC_LV_HONOR T1 ON T1.USER_ID = U.ID;
   COMMIT;
 -- 1st_Director - 1st_Crown比较直接取最高
   UPDATE AR_CALC_LV_HONOR_HIGH T
    INNER JOIN AR_CALC_LV_HONOR T1 ON T1.USER_ID = T.USER_ID
   SET T.HIGHEST_HONOR_CALC_ID = CASE WHEN T1.LAST_HONOR_CALC_ID < 70 THEN T1.LAST_HONOR_CALC_ID ELSE 70 END ,T.HIGHEST_HONOR_LV = CASE WHEN T1.LAST_HONOR_CALC_ID < 70 THEN T1.LAST_HONOR_LV ELSE IV_HONOR_1ST_CROWN END
   WHERE T.HIGHEST_HONOR_CALC_ID < 70 AND T.HIGHEST_HONOR_CALC_ID < T1.LAST_HONOR_CALC_ID;
 -- 2st_Crown2次直接赋值最高奖衔CALC_ID = 80
   UPDATE AR_CALC_LV_HONOR_HIGH T
    INNER JOIN (SELECT USER_ID,80 AS LAST_HONOR_CALC_ID,IV_HONOR_2ST_CROWN AS LAST_HONOR_LV FROM AR_CALC_LV_HONOR_RECORD WHERE PERIOD_NUM >= IV_PERIOD_NUM - 11 AND LAST_HONOR_CALC_ID >= 80 GROUP BY USER_ID HAVING COUNT(LAST_HONOR_CALC_ID) >= 2) T1 ON T1.USER_ID = T.USER_ID
   SET T.HIGHEST_HONOR_CALC_ID = CASE WHEN T.HIGHEST_HONOR_CALC_ID > T1.LAST_HONOR_CALC_ID THEN T.HIGHEST_HONOR_CALC_ID ELSE 80 END,T.HIGHEST_HONOR_LV = CASE WHEN T.HIGHEST_HONOR_CALC_ID > T1.LAST_HONOR_CALC_ID THEN T.HIGHEST_HONOR_LV ELSE IV_HONOR_2ST_CROWN END
   WHERE T.HIGHEST_HONOR_CALC_ID < 80;
 -- 3st_Crown3次直接赋值最高奖衔CALC_ID = 90
   UPDATE AR_CALC_LV_HONOR_HIGH T
    INNER JOIN (SELECT USER_ID,90 AS LAST_HONOR_CALC_ID,IV_HONOR_3ST_CROWN AS LAST_HONOR_LV FROM AR_CALC_LV_HONOR_RECORD WHERE PERIOD_NUM >= IV_PERIOD_NUM - 11 AND LAST_HONOR_CALC_ID = 90 GROUP BY USER_ID HAVING COUNT(LAST_HONOR_CALC_ID) >= 3) T1 ON T1.USER_ID = T.USER_ID
   SET T.HIGHEST_HONOR_CALC_ID = CASE WHEN T.HIGHEST_HONOR_CALC_ID > T1.LAST_HONOR_CALC_ID THEN T.HIGHEST_HONOR_CALC_ID ELSE 90 END,T.HIGHEST_HONOR_LV = CASE WHEN T.HIGHEST_HONOR_CALC_ID > T1.LAST_HONOR_CALC_ID THEN T.HIGHEST_HONOR_LV ELSE IV_HONOR_3ST_CROWN END
   WHERE T.HIGHEST_HONOR_CALC_ID < 90;
END