CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `TABLE_COLUMN_COMMENT`(IN IV_TABLE_SCHEMA VARCHAR(255))
BEGIN

	DECLARE DONE INT DEFAULT 0;
	DECLARE DONE2 INT DEFAULT 0;
	DECLARE NOT_IN_MAIN_TABLE VARCHAR(50);
	DECLARE NOT_IN_MAIN_COLUMN VARCHAR(50);
	DECLARE NOT_IN_MAIN_TABLE_COMMENT TEXT;
	DECLARE NOT_IN_MAIN_COLUMN_COMMENT TEXT;
	DECLARE NOT_IN_SECONDARY_TABLE VARCHAR(50);
	DECLARE NOT_IN_SECONDARY_COLUMN VARCHAR(50);
	DECLARE NOT_IN_SECONDARY_TABLE_COMMENT TEXT;
	DECLARE NOT_IN_SECONDARY_COLUMN_COMMENT TEXT;
	DECLARE IN_MAIN_TABLE VARCHAR(50);
	DECLARE IN_MAIN_COLUMN VARCHAR(50);
	DECLARE IN_MAIN_TABLE_COMMENT TEXT;
	DECLARE IN_MAIN_COLUMN_COMMENT TEXT;
	DECLARE ROUTINE_TABLE_NAME VARCHAR(50);
	DECLARE ROUTINE_TABLE_COMMENT VARCHAR(50);
	DECLARE ROUTINE_COLUMN_NAME VARCHAR(50);
	DECLARE ROUTINE_COLUMN_COMMENT VARCHAR(50);
	DECLARE ROUTINE_TYPE VARCHAR(50);

	DECLARE
    RS
    CURSOR FOR
				SELECT
					T.TABLE_NAME AS NOT_IN_MAIN_TABLE,
					T.TABLE_COMMENT AS NOT_IN_MAIN_TABLE_COMMENT,
					T.COLUMN_NAME AS NOT_IN_MAIN_COLUMN,
					T.COLUMN_COMMENT AS NOT_IN_MAIN_COLUMN_COMMENT
				FROM
					(SELECT
	A.TABLE_NAME,
	A.TABLE_COMMENT,
	A.COLUMN_NAME,
	A.COLUMN_COMMENT
FROM
(SELECT
	T.TABLE_NAME,
	T2.TABLE_COMMENT,
	NULL AS COLUMN_NAME,
	NULL AS COLUMN_COMMENT
FROM
	information_schema.`COLUMNS` T
	LEFT JOIN information_schema.`TABLES` T2 ON T2.TABLE_NAME = T.TABLE_NAME AND T2.TABLE_SCHEMA = T.TABLE_SCHEMA
	WHERE T.TABLE_SCHEMA = IV_TABLE_SCHEMA -- AND T.TABLE_NAME NOT LIKE '%MID%'
	GROUP BY T.TABLE_NAME

UNION ALL

SELECT
	T.TABLE_NAME,
	T2.TABLE_COMMENT AS TABLE_COMMENT,
	T.COLUMN_NAME,
	T.COLUMN_COMMENT
FROM
	information_schema.`COLUMNS` T
	LEFT JOIN information_schema.`TABLES` T2 ON T2.TABLE_NAME = T.TABLE_NAME AND T2.TABLE_SCHEMA = T.TABLE_SCHEMA
	WHERE T.TABLE_SCHEMA = IV_TABLE_SCHEMA -- AND T.TABLE_NAME NOT LIKE '%MID%'
	) A
	ORDER BY A.TABLE_NAME ASC) T
				WHERE
					CONCAT(T.TABLE_NAME,'.',IFNULL( T.COLUMN_NAME, '' ))
					NOT IN
					( SELECT CONCAT( A.TABLE_NAME, '.', IFNULL( A.COLUMN_NAME, '' )) FROM ibs_calc_serve_dev.REMARK_SYNC A );

	DECLARE
    RS2
    CURSOR FOR
				SELECT
					T.TABLE_NAME AS NOT_IN_SECONDARY_TABLE,
					T.TABLE_COMMENT AS NOT_IN_SECONDARY_TABLE_COMMENT,
					T.COLUMN_NAME AS NOT_IN_SECONDARY_COLUMN,
					T.COLUMN_COMMENT AS NOT_IN_SECONDARY_COLUMN_COMMENT
				FROM
					ibs_calc_serve_dev.REMARK_SYNC T
				WHERE
					CONCAT(T.TABLE_NAME,'.',IFNULL( T.COLUMN_NAME, '' ))
					NOT IN
					( SELECT CONCAT( A.TABLE_NAME, '.', IFNULL( A.COLUMN_NAME, '' )) FROM (SELECT
	A.TABLE_NAME,
	A.TABLE_COMMENT,
	A.COLUMN_NAME,
	A.COLUMN_COMMENT
FROM
(SELECT
	T.TABLE_NAME,
	T2.TABLE_COMMENT,
	NULL AS COLUMN_NAME,
	NULL AS COLUMN_COMMENT
FROM
	information_schema.`COLUMNS` T
	LEFT JOIN information_schema.`TABLES` T2 ON T2.TABLE_NAME = T.TABLE_NAME AND T2.TABLE_SCHEMA = T.TABLE_SCHEMA
	WHERE T.TABLE_SCHEMA = IV_TABLE_SCHEMA
	GROUP BY T.TABLE_NAME

UNION ALL

SELECT
	T.TABLE_NAME,
	NULL AS TABLE_COMMENT,
	T.COLUMN_NAME,
	T.COLUMN_COMMENT
FROM
	information_schema.`COLUMNS` T
	WHERE T.TABLE_SCHEMA = IV_TABLE_SCHEMA


UNION ALL

SELECT
	T.ROUTINE_NAME,
	NULL AS TABLE_COMMENT,
	NULL AS COLUMN_NAME,
	NULL AS COLUMN_COMMENT
FROM
	information_schema.`ROUTINES` T
	WHERE T.ROUTINE_SCHEMA = IV_TABLE_SCHEMA) A
	ORDER BY A.TABLE_NAME ASC) A );


DECLARE
    RS3
    CURSOR FOR
				SELECT
					T.TABLE_NAME AS IN_MAIN_TABLE,
					T.TABLE_COMMENT AS IN_MAIN_TABLE_COMMENT,
					T.COLUMN_NAME AS IN_MAIN_COLUMN,
					T.COLUMN_COMMENT AS IN_MAIN_COLUMN_COMMENT
				FROM
					(SELECT
	A.TABLE_NAME,
	A.TABLE_COMMENT,
	A.COLUMN_NAME,
	A.COLUMN_COMMENT
FROM
(SELECT
	T.TABLE_NAME,
	T2.TABLE_COMMENT,
	NULL AS COLUMN_NAME,
	NULL AS COLUMN_COMMENT
FROM
	information_schema.`COLUMNS` T
	LEFT JOIN information_schema.`TABLES` T2 ON T2.TABLE_NAME = T.TABLE_NAME AND T2.TABLE_SCHEMA = T.TABLE_SCHEMA
	WHERE T.TABLE_SCHEMA = IV_TABLE_SCHEMA
	GROUP BY T.TABLE_NAME

UNION ALL

SELECT
	T.TABLE_NAME,
	NULL AS TABLE_COMMENT,
	T.COLUMN_NAME,
	T.COLUMN_COMMENT
FROM
	information_schema.`COLUMNS` T
	WHERE T.TABLE_SCHEMA = IV_TABLE_SCHEMA


UNION ALL

SELECT
	T.ROUTINE_NAME,
	NULL AS TABLE_COMMENT,
	NULL AS COLUMN_NAME,
	NULL AS COLUMN_COMMENT
FROM
	information_schema.`ROUTINES` T) A
	ORDER BY A.TABLE_NAME ASC) T
				WHERE
					CONCAT(T.TABLE_NAME,'.',IFNULL( T.COLUMN_NAME, '' ))
					IN
					( SELECT CONCAT( A.TABLE_NAME, '.', IFNULL( A.COLUMN_NAME, '' )) FROM ibs_calc_serve_dev.REMARK_SYNC A WHERE A.IS_DISENABLE = 1 );

	DECLARE
    RS4
    CURSOR FOR
			SELECT
				T.ROUTINE_NAME,
				NULL AS TABLE_COMMENT,
				NULL AS COLUMN_NAME,
				NULL AS COLUMN_COMMENT,
				T.ROUTINE_TYPE AS TYPE
				FROM
				information_schema.`ROUTINES` T
			WHERE
				T.ROUTINE_SCHEMA = IV_TABLE_SCHEMA
				AND T.ROUTINE_NAME
					NOT IN
					( SELECT  A.TABLE_NAME FROM ibs_calc_serve_dev.REMARK_SYNC A );

	DECLARE
    CONTINUE HANDLER FOR SQLSTATE '02000'
    SET DONE = 1;
		OPEN RS;


		FETCH NEXT
			FROM
        RS
			INTO
					NOT_IN_MAIN_TABLE,
					NOT_IN_MAIN_TABLE_COMMENT,
					NOT_IN_MAIN_COLUMN,
					NOT_IN_MAIN_COLUMN_COMMENT;

			WHILE DONE <> 1 DO
		IF NOT_IN_MAIN_TABLE IS NOT NULL THEN
		INSERT INTO ibs_calc_serve_dev.REMARK_SYNC (TABLE_NAME,TABLE_COMMENT,COLUMN_NAME,COLUMN_COMMENT,IS_DISENABLE,TYPE) VALUES (NOT_IN_MAIN_TABLE,NOT_IN_MAIN_TABLE_COMMENT,NOT_IN_MAIN_COLUMN,NOT_IN_MAIN_COLUMN_COMMENT,0,'TABLE');
		END IF;

		FETCH NEXT
        FROM
            RS
        INTO
						NOT_IN_MAIN_TABLE,
						NOT_IN_MAIN_TABLE_COMMENT,
						NOT_IN_MAIN_COLUMN,
						NOT_IN_MAIN_COLUMN_COMMENT;
			END WHILE;
    CLOSE RS;


	SET DONE = 0;
	OPEN RS4;


	FETCH NEXT
    FROM
        RS4
    INTO
				ROUTINE_TABLE_NAME,
				ROUTINE_TABLE_COMMENT,
				ROUTINE_COLUMN_NAME,
				ROUTINE_COLUMN_COMMENT,
				ROUTINE_TYPE;

				WHILE DONE <> 1 DO
				IF ROUTINE_TABLE_NAME IS NOT NULL THEN
				INSERT INTO ibs_calc_serve_dev.REMARK_SYNC (TABLE_NAME,TABLE_COMMENT,COLUMN_NAME,COLUMN_COMMENT,IS_DISENABLE,TYPE) VALUES (ROUTINE_TABLE_NAME,ROUTINE_TABLE_COMMENT,ROUTINE_COLUMN_NAME,ROUTINE_COLUMN_COMMENT,0,ROUTINE_TYPE);
		END IF;

		FETCH NEXT
        FROM
            RS4
        INTO
						ROUTINE_TABLE_NAME,
						ROUTINE_TABLE_COMMENT,
						ROUTINE_COLUMN_NAME,
						ROUTINE_COLUMN_COMMENT,
						ROUTINE_TYPE;
			END WHILE;
    CLOSE RS4;



	SET DONE = 0;
	OPEN RS2;

		FETCH NEXT
    FROM
        RS2
    INTO
				NOT_IN_SECONDARY_TABLE,
				NOT_IN_SECONDARY_TABLE_COMMENT,
				NOT_IN_SECONDARY_COLUMN,
				NOT_IN_SECONDARY_COLUMN_COMMENT;

			WHILE DONE <> 1 DO
		IF NOT_IN_SECONDARY_TABLE IS NOT NULL THEN
		UPDATE ibs_calc_serve_dev.REMARK_SYNC SET IS_DISENABLE = 1 WHERE CONCAT(TABLE_NAME,'.',IFNULL(COLUMN_NAME, '' )) = CONCAT(NOT_IN_SECONDARY_TABLE,'.',IFNULL( NOT_IN_SECONDARY_COLUMN, '' ));
		END IF;

		FETCH NEXT
        FROM
            RS2
        INTO
						NOT_IN_SECONDARY_TABLE,
						NOT_IN_SECONDARY_TABLE_COMMENT,
						NOT_IN_SECONDARY_COLUMN,
						NOT_IN_SECONDARY_COLUMN_COMMENT;
			END WHILE;
    CLOSE RS2;


	SET DONE = 0;
	OPEN RS3;

	FETCH NEXT
    FROM
        RS3
    INTO
				IN_MAIN_TABLE,
				IN_MAIN_TABLE_COMMENT,
				IN_MAIN_COLUMN,
				IN_MAIN_COLUMN_COMMENT;

				WHILE DONE <> 1 DO
				IF IN_MAIN_TABLE IS NOT NULL THEN
				UPDATE ibs_calc_serve_dev.REMARK_SYNC SET IS_DISENABLE = 0 WHERE CONCAT(TABLE_NAME,'.',IFNULL(COLUMN_NAME, '' )) = CONCAT(IN_MAIN_TABLE,'.',IFNULL( IN_MAIN_COLUMN, '' ));
		END IF;

		FETCH NEXT
        FROM
            RS3
        INTO
						IN_MAIN_TABLE,
						IN_MAIN_TABLE_COMMENT,
						IN_MAIN_COLUMN,
						IN_MAIN_COLUMN_COMMENT;
			END WHILE;
    CLOSE RS3;


		UPDATE ibs_calc_serve_dev.REMARK_SYNC C
INNER JOIN ( SELECT A.ID, A.TABLE_NAME FROM ibs_calc_serve_dev.REMARK_SYNC A WHERE A.COLUMN_NAME IS NULL ) A ON A.TABLE_NAME = C.TABLE_NAME
SET C.PARENT_ID = A.ID
WHERE
    C.COLUMN_NAME IS NOT NULL
    AND C.TABLE_NAME = A.TABLE_NAME;


END