CREATE DEFINER=`ibs_calc_appl`@`%` PROCEDURE `UPDATE_TABLE_COMMENT`(IN TABLE_SCHEMA VARCHAR(255))
BEGIN

	DECLARE DONE INT DEFAULT 0;
	DECLARE DONE2 INT DEFAULT 0;
	DECLARE NOT_IN_MAIN_TABLE VARCHAR(50);
	DECLARE NOT_IN_MAIN_COLUMN VARCHAR(50);
	DECLARE NOT_IN_SECONDARY_TABLE VARCHAR(50);
	DECLARE NOT_IN_SECONDARY_COLUMN VARCHAR(50);
	DECLARE IN_MAIN_TABLE VARCHAR(50);
	DECLARE IN_MAIN_COLUMN VARCHAR(50);

	DECLARE
    RS
    CURSOR FOR
				SELECT
					T.TABLE_NAME AS NOT_IN_MAIN_TABLE,
					T.COLUMN_NAME AS NOT_IN_MAIN_COLUMN
				FROM
					(SELECT
	A.TABLE_NAME,
	A.COLUMN_NAME
FROM
(SELECT
	T.TABLE_NAME,
	NULL AS COLUMN_NAME
FROM
	information_schema.`COLUMNS` T
	WHERE T.TABLE_SCHEMA = 'ibs_calc_serve'
	GROUP BY T.TABLE_NAME

UNION ALL

SELECT
	T.TABLE_NAME,
	T.COLUMN_NAME
FROM
	information_schema.`COLUMNS` T
	WHERE T.TABLE_SCHEMA = 'ibs_calc_serve') A
	ORDER BY A.TABLE_NAME ASC) T
				WHERE
					CONCAT(T.TABLE_NAME,'.',IFNULL( T.COLUMN_NAME, '' ))
					NOT IN
					( SELECT CONCAT( A.TABLE_NAME, '.', IFNULL( A.COLUMN_NAME, '' )) FROM ibs_calc_serve.REMARK_SYNC A );

	DECLARE
    RS2
    CURSOR FOR
				SELECT
					T.TABLE_NAME AS NOT_IN_SECONDARY_TABLE,
					T.COLUMN_NAME AS NOT_IN_SECONDARY_COLUMN
				FROM
					ibs_calc_serve.REMARK_SYNC T
				WHERE
					CONCAT(T.TABLE_NAME,'.',IFNULL( T.COLUMN_NAME, '' ))
					NOT IN
					( SELECT CONCAT( A.TABLE_NAME, '.', IFNULL( A.COLUMN_NAME, '' )) FROM (SELECT
	A.TABLE_NAME,
	A.COLUMN_NAME
FROM
(SELECT
	T.TABLE_NAME,
	NULL AS COLUMN_NAME
FROM
	information_schema.`COLUMNS` T
	WHERE T.TABLE_SCHEMA = 'ibs_calc_serve'
	GROUP BY T.TABLE_NAME

UNION ALL

SELECT
	T.TABLE_NAME,
	T.COLUMN_NAME
FROM
	information_schema.`COLUMNS` T
	WHERE T.TABLE_SCHEMA = 'ibs_calc_serve') A
	ORDER BY A.TABLE_NAME ASC) A );

	DECLARE
    RS3
    CURSOR FOR
				SELECT
					T.TABLE_NAME AS IN_MAIN_TABLE,
					T.COLUMN_NAME AS IN_MAIN_COLUMN
				FROM
					(SELECT
	A.TABLE_NAME,
	A.COLUMN_NAME
FROM
(SELECT
	T.TABLE_NAME,
	NULL AS COLUMN_NAME
FROM
	information_schema.`COLUMNS` T
	WHERE T.TABLE_SCHEMA = 'ibs_calc_serve'
	GROUP BY T.TABLE_NAME

UNION ALL

SELECT
	T.TABLE_NAME,
	T.COLUMN_NAME
FROM
	information_schema.`COLUMNS` T
	WHERE T.TABLE_SCHEMA = 'ibs_calc_serve') A
	ORDER BY A.TABLE_NAME ASC) T
				WHERE
					CONCAT(T.TABLE_NAME,'.',IFNULL( T.COLUMN_NAME, '' ))
					IN
					( SELECT CONCAT( A.TABLE_NAME, '.', IFNULL( A.COLUMN_NAME, '' )) FROM ibs_calc_serve.REMARK_SYNC A WHERE A.IS_DEL = 1 );

	DECLARE
    CONTINUE HANDLER FOR SQLSTATE '02000'
    SET DONE = 1;
		OPEN RS;


		FETCH NEXT
    FROM
        RS
    INTO
				NOT_IN_MAIN_TABLE,
				NOT_IN_MAIN_COLUMN;

			WHILE DONE <> 1 DO
		IF NOT_IN_MAIN_TABLE IS NOT NULL THEN
		INSERT INTO ibs_calc_serve.REMARK_SYNC (TABLE_NAME,COLUMN_NAME,COLUMN_COMMENT,IS_DEL) VALUES (NOT_IN_MAIN_TABLE,NOT_IN_MAIN_COLUMN,NULL,0);
		END IF;

		FETCH NEXT
        FROM
            RS
        INTO
						NOT_IN_MAIN_TABLE,
						NOT_IN_MAIN_COLUMN;
			END WHILE;
    CLOSE RS;




	SET DONE = 0;
	OPEN RS2;

		FETCH NEXT
    FROM
        RS2
    INTO
				NOT_IN_SECONDARY_TABLE,
				NOT_IN_SECONDARY_COLUMN;

			WHILE DONE <> 1 DO
		IF NOT_IN_SECONDARY_TABLE IS NOT NULL THEN
		UPDATE ibs_calc_serve.REMARK_SYNC SET IS_DEL = 1 WHERE CONCAT(TABLE_NAME,'.',IFNULL(COLUMN_NAME, '' )) = CONCAT(NOT_IN_SECONDARY_TABLE,'.',IFNULL( NOT_IN_SECONDARY_COLUMN, '' ));
		END IF;

		FETCH NEXT
        FROM
            RS2
        INTO
						NOT_IN_SECONDARY_TABLE,
						NOT_IN_SECONDARY_COLUMN;
			END WHILE;
    CLOSE RS2;

	SET DONE = 0;
	OPEN RS3;

	FETCH NEXT
    FROM
        RS3
    INTO
				IN_MAIN_TABLE,
				IN_MAIN_COLUMN;

				WHILE DONE <> 1 DO
				IF IN_MAIN_TABLE IS NOT NULL THEN
				UPDATE ibs_calc_serve.REMARK_SYNC SET IS_DEL = 0 WHERE CONCAT(TABLE_NAME,'.',IFNULL(COLUMN_NAME, '' )) = CONCAT(IN_MAIN_TABLE,'.',IFNULL( IN_MAIN_COLUMN, '' ));
		END IF;

		FETCH NEXT
        FROM
            RS3
        INTO
						IN_MAIN_TABLE,
						IN_MAIN_COLUMN;
			END WHILE;
    CLOSE RS3;

	UPDATE ibs_calc_serve.REMARK_SYNC C
INNER JOIN ( SELECT A.ID, A.TABLE_NAME FROM ibs_calc_serve.REMARK_SYNC A WHERE A.COLUMN_NAME IS NULL ) A ON A.TABLE_NAME = C.TABLE_NAME
SET C.PARENT_ID = A.ID
WHERE
    C.COLUMN_NAME IS NOT NULL
    AND C.TABLE_NAME = A.TABLE_NAME;

END